apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: cert-manager
spec:
    interval: 5m
    chart:
        spec:
            chart: cert-manager
            version: 6.1.1
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        resources:
            requests:
                memory: 100Mi
            limits:
                memory: 512Mi
        # cainjector:
        #     resources:
        #         requests:
        #             memory: 100Mi
        #         limits:
        #             memory: 512Mi
        # webhook:
        #     resources:
        #         requests:
        #             memory: 100Mi
        #         limits:
        #             memory: 512Mi
