apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: cert-manager
spec:
  limits:
    - default:
        memory: 256Mi
      defaultRequest:
        memory: 50Mi
      type: Container
