---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-nfs-pv
  namespace: media-qbittorrent
spec:
  storageClassName: downloads-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_SERVER_IP}
    path: ${NFS_PATH_DOWNLOADS}
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noresvport
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-nfs-pvc
  namespace: media-qbittorrent
spec:
  storageClassName: downloads-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
