---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media-qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 21.1.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                QBT_Preferences__WebUI__AuthSubnetWhitelist: "192.168.0.0/16, 172.16.0.0/12"
                QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: "true"

    # service:
    #   torrent:
    #     loadBalancerIP: ${TORRENT_IP}
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: selfsigned
          homepage:
            enabled: true
        hosts:
          - host: torrent.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    addons:
      vpn:
        type: gluetun
        excludedNetworks_IPv4:
          - "192.168.0.0/16"
        env:
          VPN_TYPE: "wireguard"
          VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER}
          WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
          WIREGUARD_PRESHARED_KEY: ${WIREGUARD_PRESHARED_KEY}
          WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES}
          FIREWALL_VPN_INPUT_PORTS: ${FIREWALL_VPN_INPUT_PORTS}
          SERVER_COUNTRIES: ${SERVER_COUNTRIES}
          FIREWALL_INPUT_PORTS: "10095,8000"

    persistence:
      config:
        type: emptyDir
      # downloads:
      #   enabled: true
      #   existingClaim: downloads-nfs-pvc
      #   mountPath: "/downloads"
