apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-iscsi
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    controller:
      externalAttacher:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 1Gi
          limits:
            memory: 100Mi
            ephemeral-storage: 5Gi
      externalProvisioner:
        resources:
          requests:
            cpu: 10m
            memory: 50M
            ephemeral-storage: 1Gi
          limits:
            memory: 100M
            ephemeral-storage: 5Gi
      externalResizer:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 100Mi
            ephemeral-storage: 5Gi
      externalSnapshotter:
        resources:
          requests:
            cpu: 10m
            memory: 30Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 100Mi
            ephemeral-storage: 5Gi
      driver:
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 100Mi
            ephemeral-storage: 2Gi
    csiProxy:
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
          ephemeral-storage: 1Gi
        limits:
          memory: 100Mi
          ephemeral-storage: 5Gi
    csiDriver:
      name: iscsi
    storageClasses:
      - name: iscsi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
          detachedVolumesFromSnapshots: "false"
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses:
      - name: iscsi
        parameters:
          detachedSnapshots: "true"
    driver:
      config:
      driver: freenas-api-iscsi
      instance_id:
      httpConnection:
        protocol: http
        host: ${TRUENAS_IP}
        port: ${TRUENAS_API_PORT}
        allowInsecure: true
        apiKey: ${TRUENAS_API_KEY}
      zfs:
        datasetParentName: ${ISCSI_ZFS_DATASET_PARENT_NAME}
        detachedSnapshotsDatasetParentName: ${ISCSI_ZFS_SNAPSHOT_DATASET_PARENT_NAME}
        zvolCompression:
        zvolDedup:
        zvolEnableReservation: false
        zvolBlocksize:
      iscsi:
        targetPortal: "${TRUENAS_IP}:3260"
        interface:
        namePrefix: csi-
        nameSuffix: -talos
        targetGroups:
          - targetGroupPortalGroup: 1
            targetGroupInitiatorGroup: 1
            targetGroupAuthType: None
            targetGroupAuthGroup:
        extentInsecureTpc: true
        extentXenCompat: false
        extentDisablePhysicalBlocksize: true
        extentBlocksize: 512
        extentRpm: SSD
        extentAvailThreshold: 0
    node:
      driver:
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 200Mi
            ephemeral-storage: 5Gi
      driverRegistrar:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 200Mi
            ephemeral-storage: 5Gi
      cleanup:
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 200Mi
            ephemeral-storage: 5Gi
