---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas
  namespace: external
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: ExternalIP
        externalIP: ${TRUENAS_IP}
        useSlice: false
        ports:
          main:
            protocol: http
            port: 81
    ingress:
      main:
        enabled: true
        tls:
          - clusterCertificate: wildcard
            hosts:
              - nas.${BASE_DOMAIN}
        hosts:
          - host: nas.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          homepage:
            enabled: false
            name: TrueNAS
            description: TrueNAS Scale
            group: Infra
            icon: truenas-scale.png
            widget:
              type: truenas
              # url: "" - defaults to ingress host 0
              custom:
                key: ${TRUENAS_API_KEY}
                enablePools: "true"
