apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:JetQyC/QaOIZStLO4RfF5HK+JQlYh+5Z5Le8HMAm9FjZrj4uQXE6dyGETqyb+GL5no8OwuXuw7zpmgJSffMjCPk=,iv:IWvG51TOifswg4IkGRNisLUXWLTX80yp2dmbX9iq+wc=,tag:zQQHfbJsa3boHh7HqRtElQ==,type:comment]
    #ENC[AES256_GCM,data:yudL6xMayMI9230/t63a1CfW1umNqyKK8lCtJT7wb8PgSIr5gHrKsHDxx38=,iv:awzRcufVcmz0Iry9bENQpi+PCGxdb93NaC7VKx52jMo=,tag:Q5y5qZHqUyMMdQnpJny2fw==,type:comment]
    VIP: ENC[AES256_GCM,data:wFVLNS1nZtigeVmE,iv:lLGfmN77W65toh124JQMLqMpyfCA1HVO0DbaeM+6mBo=,tag:r5cMKyWHfXVgaB3UyKQvag==,type:str]
    #ENC[AES256_GCM,data:uPcFa0AYMqNcuuSP/JiMoDAr9b1VkF9ZAmM=,iv:4FlVOXcZdzDnb2eqSDDaRZJIQTYWflNbvIW1UqDOuzA=,tag:3oLhvqEKgl8H8vfjm0qs0Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:XIGCHJgiXNNXUo2o,iv:5JGId+W6Fsj85/cbiVu6qooZQjL/1arSba+PahqbJMI=,tag:CNLHjblGMudiVtSNLI+M5w==,type:str]
    #ENC[AES256_GCM,data:NlFi/5cuIIAcWZpkXz5jYGxzFCEZ0GnSeWdlT9shssd7wQ==,iv:yVQWYdJLMWs07tDVDr/8TmQ1i6jRZUULN6BmcRJuxnY=,tag:NbiiUgVrSnL3mukz66TpuQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:NGrWG3vKMbOEfYg=,iv:I3STCoZ+LA8uhwGS8t4xHKF472wZW0d9yP+7WTqWuck=,tag:seZmmMkpXkZD89hjc4dGSA==,type:str]
    #ENC[AES256_GCM,data:JmCtXVsgWA6VtCr9uGo2cxBLBFSWXCbrAiblSh/DwcmY4bIefBxs6wdqseekdj4=,iv:Ngm/qd5BN0lDMbvgfRa+ktSYxukVHpnC+Nt2IIC7c8s=,tag:0leVtneANlw3Qu5Wy0tCXA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:NXxoxpSDvvyXw0sLjeQawyE6t2Jc3mm29w==,iv:9c/m4fYXcxV2NQCV1WPONzqyKKpijJNlhm1yxRyMy8I=,tag:cRgakWOzcMhtx+ZQNNiqoQ==,type:str]
    #ENC[AES256_GCM,data:PJ6XXTRyjnr0Xiiys4quIEFO6U74Ls8uFTx/4ggK5s0aGDmvGK+iYRv/5OrVFw9esllEnXJ87+EKNlqCGJEMRhPfzPTu/kFroAT6Xw9IMa0=,iv:wmBRw9rSNRNQCswA5cXQO758ZE4AxU0YDl5WfgmvawA=,tag:VUkAaMXnKDp/rLi6YrvWkw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:5YLqV/toXXe6DI6O,iv:LyFEDVuG3DaJtGc1bMo9m9s4wvgqbuEzb9qIdiwtmec=,tag:Ki6C/NDmy0F1oluMWEP3Fg==,type:str]
    #ENC[AES256_GCM,data:kd7/LCGTykovyrWZ/hyUo5Bb7Frtd33PUG3+BW7MD79JOmFNBNzTcsaol016OiIOYYkCiZrqfU/Q1Eia1PBYrv3QTLk=,iv:YhXI5okeDYDnygKyI9EGo3UhYiYg6o3HPsdZKXwuHbQ=,tag:U77L/XIfONZTtrDvHh7Jtw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:CISkN3rAR0M9FCPn,iv:YPotkoc9sQPk8jpYNa91oTXoRJjmYdh7Wng9tW+XWm0=,tag:p7hahJK2YQTPcy08ZJ4mxw==,type:str]
    #ENC[AES256_GCM,data:8kqE68G2ELlbO/bj+xmBBxMYBszyUUgP004yTQhIt1Fghzuj5L3yoX4H2HcNMUFNIjw9Bug0GjE=,iv:3WR0/g2EjYU8R2Fp2Qjq3JBrdrJL4n1GWSDUr3o6I6I=,tag:hkmQgc5VS0+BkQYQ5Ugvcw==,type:comment]
    #ENC[AES256_GCM,data:lnvTdKW+ElJ7O7x3v+hXpURP+JymumRroQ==,iv:AFGP/WtT3lYtX0sBjqXERHRQoFP7lu5R7V7Ms/JFDkI=,tag:Sm9nwrKZGea/qlrfVMjYZA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:m5DbnDq77/+MJJpJNp6sPJ4e6D2qLuoWOhcxVwlGDHWGuwzieO8sbWk=,iv:yzxsLBZdHda+jFavARUTGfxJDhuYDUw9bArr1QxOfOM=,tag:jNTiZqmoDU4ciVNoY4bEww==,type:str]
    #ENC[AES256_GCM,data:uapyn0r6kPiJoGd8gA==,iv:p/+PHFFbfT6Aa93un0VP5JrSboxpxYr64fvDo5LlXEM=,tag:jo2kNJzCQQ8voiSDZTNu8w==,type:comment]
    PODNET: ENC[AES256_GCM,data:NOnNQ1VDS+Q/wboIQA==,iv:4bWET8Z+P8MyWsYrdjEpTMmo3+8178SlQdl5fx0pNKk=,tag:30CvYadMp8kF60lT2ux6Hg==,type:str]
    SVCNET: ENC[AES256_GCM,data:pRJPsTIN5un94oOOoA==,iv:qd12sr/+6M6LNHfrEES+G3akNqvxJXDQDo+lS6x5ew4=,tag:Uy0hK+mkkijF4f8x9a890Q==,type:str]
    #
    TRAEFIK_IP: ENC[AES256_GCM,data:0bHjvqNTENDDwH/K,iv:UkqPbFH5nQTGXi0aWtPQwd9kinjmX9ilHJv7+uqOU1Q=,tag:oRQK7lLjT7GuhlXyTmMkRA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:1SI8q5rwQ9PyM1g=,iv:brbIZenk0frU/tCyvvHIAY3vPgIhS3vcrzGWNetKcdM=,tag:amYkMk4tgHrD2VI2j5pk1g==,type:str]
    #ENC[AES256_GCM,data:bIB2Zbs=,iv:NGHitcNE/0j4fvWGj+jZWtyEDuofSA88Ub800QObMeI=,tag:KpzIoTxXgt6gyfUH2NS+LA==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:kI5m4OHOEF4+UPNM,iv:CYdkILGqIlkmgMrNToSUJDp1p3tN520fVzsOlYae0Rk=,tag:gKJzZdFGJkrkyP2s25ZHLw==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:m0fGEkY5zG4oPBLFjIuY2jk9kgz/AGluSVxJ9rKzPDvzn13cSpBrHBuh37EYJBNdiH/vL/Xh,iv:DPDuBih5xccTmOL3RMi6kf2PBKdnwIIoo4PlXEUWbQ0=,tag:OdMFvh73M+Xub+SJYiLh4w==,type:str]
    #ENC[AES256_GCM,data:TabFbL3hOEiacgM=,iv:sUWhZ+/q0AR4lBlua7BvG3bENxKm/umIyJSxF99OQ+U=,tag:z/g3JTH7OPJALCArF2R40g==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:mHSWBGyqo6ruIwaO,iv:UWZiXirPT322KcR5kQ5KCGyTwPNCeGTFORRKPh9pMfY=,tag:lksispVEMRYwwXUGRYdo1Q==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:W3wLGXj12olQcbxloWDwSZCBfg==,iv:dlyqqxJuSrcFzm/Bj+09+3iUoUWAxWoK6wFDkhOFFnk=,tag:RTCJkIPtI7+lfOKZf1VLIw==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:kD9TWZG6kImgQJ6lB8vnNw==,iv:1ZOb2ePlMrgAxmPd+D/HA8w4pTfHjIzFGaL1u2CtQp8=,tag:tIbl4YN7WKeyj6tW5blMNQ==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:+X1fNB3TymjAsNFuMKNUrPubnwTUie19FtTQGmYl/c1P,iv:etbc4BoYqrhNAtZ2QbBEXKros9nrQ+f4Jah28SWJvFI=,tag:hGLFz4fJf32nBnJICQSHrw==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:VZ4e20r6TJ0wPc8jPa9OWiawDVrXy+7IstohHKUHbbxs,iv:hihpGm6i/lIZJOpFbSyasjDP2i+ubIeGHpm/unHsNYA=,tag:K/iE6MC9j4kcEYkMTHzRAw==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:T4ts4B6X7MOFjqYN+rXeEw4E0rZtVHjCnB//HE6u5nw=,iv:s74Bk3BvZocXrmkEgSfo/twLtrv3ZPA7HqG2KhUfPAg=,tag:imvn3IQwj0PjUbZO7QWSXQ==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:UJvwztGojJ+9H+CxzCImZzxOW5ZXDw==,iv:QauwFR1LZYNLyjj/p33TJTUMbvhnoFLg+Ki9H4XQPaM=,tag:NwXys9HLyYla5KLtSV7Qkg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK0x4Q1dvcWdPQytWdTVs
            bDlBbW1LbEZFMmVFcWgyUkVDbk02VmIzMmxBCklJeUY5ajkwVURKUkpaTjlnbURq
            TFJoVFhBWlpHVWtiVUI3K1JneEgxbkkKLS0tIGFyTHNhSjM5WVRsY2hXSzRzd3hI
            QTlYcThQOUZpMWFmaTBOZ044V3BjUTQKj6ESTTl7XxHM/MbEO3z2GAbdlILooRTj
            wHhLFD9rTxpY0cNa6gUPrnK4TzFC3IILVpNFBblcTeErQZqPnakLtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T21:58:34Z"
    mac: ENC[AES256_GCM,data:gU4KCGtWVEEcQAGpGsUlB7vMCN0dZEbXricTlr312CdvWncshslSNVnHl3pG7AX0MJO7mHEMG9/yBdRiKQb3gQiF3x6dx5M7ijUUk18U6B+AuvJIdPSmasAvQ6UIZXKNuf/CqTmjaJG+KrX479HrFq7AiUZtuL3VAG9VI31P2bM=,iv:KfnY6XfI6pB+5A43gw5ZlMoLdi8HUVObMAP4LXDchs0=,tag:/9ybFLo4uxG9hp+Fs0LPiA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
