apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:1Wvx/hz+wlGpw+tqJqBtfB5VYyjQ0hscRWrCRDik7sNYYShpd5OlLMw+47LrMXNKgC6Dy0Hvkks2f/xgTvhyNc0=,iv:plJKoo8BaC99cF9VwQ6G7+EBLebGGbcsT6W8Gwhd9bQ=,tag:SKrEl+VPPwVHfHqB1DPrfA==,type:comment]
    #ENC[AES256_GCM,data:fN3m1kKPuR9ZltOuT+ZdxVPjDjEEjzvZ1Cd2r0mHNzcR6tfXZxAIOTN6x/s=,iv:79ofmuY392URziOdpuvH/LYQCxaFaJxPjTbZB52ilBI=,tag:XD/EBxBn5spvCmxhWNJ67w==,type:comment]
    VIP: ENC[AES256_GCM,data:JER+9VsQ+m3Xw6MP,iv:LqYJNQmfU4Q6mFO/op6/5X7fAQpAGia2hlNkE49mVWU=,tag:FXGUSciL9t0c/pF56L258Q==,type:str]
    #ENC[AES256_GCM,data:PhhCTUgDLhp/PQxLZu3idRgsuuoErD5xOAQ=,iv:/7n2ps+qB6p19TtRIWQdgRd5Qc4wj2Gv06xnHpDYBOk=,tag:oBjMVXtKm6QvzzI6cuhyUA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:PjDPCJGdEtseBXRC,iv:Btj3TdAJ4CddvDv1pl12gErvkSqzFqo9HooYaC22Kr4=,tag:YM25XL2gIz3AqoI1CUsyYA==,type:str]
    #ENC[AES256_GCM,data:VYx+iIbi4MTk0GCVI69XoeYt5hPn+7CkW3/b91i4t+Nm5Q==,iv:54Zp1fX3CrK/i6cKuOB5j9msg2Q9ilkyB5VHF2ltzCo=,tag:VUE8WXm+YUG4JU8Yip5ClA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:K+TsAeYVZIRuSUU=,iv:DHkF5LcsRrDA4mRxvxqdwjS94hGb0JMAMBWdv3zJZEI=,tag:qo0cGDllXnleeJ2mACnISQ==,type:str]
    #ENC[AES256_GCM,data:s6WSlC8titGg7sfJibD+OSbWP6rIVg114RFXXQnRcvel/Po4tZaizgs/NdZHGOQ=,iv:2su7yKqnu1QNALBH9EdmlqNIRuEY5IKYYXeXTMXLIZ8=,tag:sg6NdiMECsQotqMAgEmB/Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:o0IBpkJvTbJm8rQmYxHD6hOd0+tnHq4Scw==,iv:Ona9nx5CFtpvSvwiYtnH4nNsGWWkSTr8Aa6VG9QY04M=,tag:5851d1RAeCWU9ZF+1lXApg==,type:str]
    #ENC[AES256_GCM,data:jtm3wiE5T0Buzw/ankze3k+dhX02Q0PWk0U5nQHlWO2Xf3t1DoAg1PaVg8jyGWxX9RoufUmwlmau3ABFHlVSu+1X54ZmICIlwfPlXKWJU9Y=,iv:FODVTdVNu1BkhSXU01ETLoEuzO3L9qEkg2nZrKHQb6U=,tag:DLPWXxRIxFJM6i0bcupkJA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:WsqfAeMp0HRa2zx1,iv:XAoj/s9nSP/VPdwiZnWmk8AFPOfIWS6xePDt+ET2Ymg=,tag:YGmguLBQhqiNZQoesDlUNg==,type:str]
    #ENC[AES256_GCM,data:wl1z4e6I46bBKsymM1xd1i++RyxGNOmqkINBLHrUqBlwP+dRo82v5gDWKkmUyNwLu+aox0orNmpTvb+epUmflAydnzM=,iv:54CsuGpKn3dJNxYEfhO7b1wT1EWd2H5HMtedrNcIyFc=,tag:dmqrT1x2ND7mPYr4Ju2zOA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:hZ6G9wu1bnwz5dmE,iv:+Xwe+Apmx75VXCIIPvxwzid12j+1g0j3QjelJGi0uEw=,tag:Wsl7mkONfpw/F/JHBn5Y+g==,type:str]
    #ENC[AES256_GCM,data:ZNQr6V31t/MAvaY1wTPcQ86vjPuPdyCuZqrDJh7jj0La3jghF/yJbLloPy6A2KGIVWJYBcul5cE=,iv:TdBEkfcLdBd/zBN4Fms/AXo5WTC0LpVBIjORxqf+w7k=,tag:1CqN7UBwXcef96Bk19DjiQ==,type:comment]
    #ENC[AES256_GCM,data:NKzn+h6rYuqwvdL1/dwU476gVYBqndkiYA==,iv:yGp7IOqdPR/u2P5YHHYReNxcQiUeY/E1kaLFnNTx2CI=,tag:mGxN/Ug0BgXs984fcK5LcA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:zDHurGrG9adSLQMNXyOFWIKKFvsbQaLQU3F29H45HQJoJltiub40+Jg=,iv:YrOsbDOBHBZaPoc+WxwPnVm3GkEkRMEzr7WiNDFfKHM=,tag:KMudIcIL5iwa+9WlFSs/bg==,type:str]
    #ENC[AES256_GCM,data:lH4OH68lv8v92mPzgg==,iv:LwdRgdKStfPOjsrLJZYQ6wNWyJxjW8Hw5Wqw7+yl07o=,tag:XwyE0mHriEiIzJi7U5YMCQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:B7CJP8w+rJddoFz39w==,iv:QOP6FZlBHEvaU0jzdcQkFiMR8jsHQCyW+2Hv/FNrHlA=,tag:IlpO61MDCAfmVmZ7Kb1Blg==,type:str]
    SVCNET: ENC[AES256_GCM,data:4g8K0UMyjiSUjiF4gA==,iv:/mKjgxtJ497Ut/MHqFYC1o0TzxYR9swyo/XaLNDKmkQ=,tag:Cu9CTGSKEbNX4ZsyBez2Pw==,type:str]
    #ENC[AES256_GCM,data:9amAN6Gt2Bs=,iv:qpOU9cksT7+WAlWMnd6JpmbhXTGg0Rb+F67VWKMiKWg=,tag:XpgpxnwjIFx9Moo4d63LNw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:xw+yhir2OTu7p/sZ,iv:4WzMlOlNQfzG1ENauhlrU5RjELQHA+FVp1i05c4GtsI=,tag:+zsnfChQqbYEy58kzlzusw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:/Lub6r0Oos+c8tTG,iv:yevHsANjNloUwbqYybaIFtDmp/VqiAwSU6QEc6SOMcw=,tag:kTIN0YIwhBq2XO0lcPjOdA==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:sTsiqsZEOoviUmY=,iv:5rAzhikiTAj/k04lAws8ympuDXgZdq8Qyfu+piyUb5Q=,tag:/t+pN2kjhinjRN4BYsYY9g==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:qRdM9UE5aM/WKQ==,iv:2pA/x+QS3plKLza4ctqHW6I6W+99Rq6Aenalsh+wd8E=,tag:/kjjsLW8N0Ivcsbhm4JLaw==,type:str]
    #ENC[AES256_GCM,data:5u/oURY=,iv:IcTPh6yqeYAvxjuorfi+aHD+Rlu/pTtR7O7blAUep+g=,tag:p91YjhagY2Qc0bCoiw3cEg==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:nlVWWMxsnmPr3kdH,iv:+FSrkWaBaV01JX1V7KMKR6u/XWA56EwJRzL3JKmAXLs=,tag:g52/FhDtRqAs66I88rn3iw==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:JsY/YwvLiz4LWc2BLnM3GO/A1U/w/Y70Vkxtvt4rrX8bZY3BCXPRF+itIyHN7Geuc4Wyj/C+,iv:ABfKiql29P7HpbBQDkvuYfjqMnKk1P9tVP/mVc71nCE=,tag:nGD7VuFOlu9fP3sBpXWexQ==,type:str]
    #ENC[AES256_GCM,data:voMS3QwOR5gOriU=,iv:GBSeGnb0+D23l/pa+WclJPORLlVRYaG9Me0i02Z186c=,tag:kspzPs7M2QuzaEv1EwNChg==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:in3hJnDA3MqmOtEc,iv:RJCDLWFSQgwF69yIvP5Td75SBUpbSIf/wo8hlvRoruY=,tag:HfYY+dXTo77tZ1R6+SxyvQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:HZYW11mW0epB5eFnP5GmyVGUfQ==,iv:OiF/CXEKrHPxDCGomWmzmhZrjB9LeCNqyPBb2OV+0ks=,tag:fXY5adMxI4HFN4CMkbM6DA==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:P/bEp5YYRY+Admd39cqrJw==,iv:VKJr1YT7R4JV8QzzPdHnrCbzWzSuh/UyvlGQaWKtYb4=,tag:J6tMAEOPxurc5HnZIdnavw==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:7u51wh2fL3lgRhVEzmW211fPaDNiW04F/68wFTigITaL,iv:G0dh41VpoYVFdRr6+g2ZmwE3A/QIbkfpV8UNOJ3r03w=,tag:VdiMZr+hCidRN+QPaHWwVQ==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:4uRChqwcQevot5XOAAVeJPsq/ugfYl9qCoHKi164vtU/,iv:1+hLwh/90XqemVudMxodTC+LVLWO9i0SSzPo5UE6SCU=,tag:WBdLILdshwpfbcMlW5Y26Q==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:k5cbz0W/H64TDhdyj80/peu0KzIy+lIdbAc+kU5x5nk=,iv:Q6yHrNaCgc6mcg1SHOl6sWeVbSPSkJtem7JAXLYxdWw=,tag:123+aE3QxOtxQBURyaJ3Qw==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:FvQgDuOA1seII96uOigFlIKxs5kRUA==,iv:iZOwkknwmp1yuQ8kycsImMznib/hScBcjSZvEUlW/yo=,tag:Fpxsc/Ly8u6/Ud8Sk4NazQ==,type:str]
    #ENC[AES256_GCM,data:ulxzSA==,iv:VgJD2lC0K87/N8yrfxzljVCOG3V7XCGUgi4XEq7G5Fk=,tag:3vXhbMj5uOowXNFdbafNpQ==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:4vfmCLuX,iv:PKL/CCciagLIeQhH59k2pubeyr3n6MDuLQGJtje4y+0=,tag:/cWxDibv+9kdVfcKrIz56g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:T/ht12KHJrLE30jJNGW5CgmePXeEVjpxh1wIkiaiBGV1CPt2aBleneId8Lg=,iv:LhSGulloVvOeol/s+FpIhUPdGLdO5PNXOzkpgaVOfBg=,tag:lFBSYDVapEQvjD0iv2Zyhw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:MPHWibyNvsTUhTIimQ4QfT+R1R1aesvXXfUe3kC32hG1ITpN81h/rKghb/c=,iv:oBQK4f2MF+hWpLetIOq0BjlZArcBLlCdeCIxxm8DoAs=,tag:Xc1S1Dt9tB7rz59HyM33Qg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:JHDp9nj9s2jwCyPstpMPpYA=,iv:AclBTTVoZeC0DdXwfoVdaDwHL98x0M3uk/YkVi6X3i8=,tag:dMJYlMSgdDmNc3vTgsCNgw==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:P+U/DlQ=,iv:yrfUeeU5v7MsBEI9MGFZjHOAvhqZsHWXapq0tie8e/g=,tag:K1J97sI/t71OjzCB071/6w==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:H12raffEHn2dbv5Dlna4z28fejZIo58/k2bM/ZruLkt1,iv:GGzXmC/BRs1YsLaS9tnnf1/R65DRzHpBCSzpI52I6Bg=,tag:kEznmAEHVXW5vwCkvI/10g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdHBiWVlKV084VnZTakJn
            Q1BCeW5udGkxZHdNcWx4VWMwUlk4a1EvbVV3CkVTaDZubVFaanRvN0FjKzV5TnE0
            UjRmSm15UGUzc0tVZ1c4UWtGUmhPZ0EKLS0tIHg4NE4xc1EyYUpnRzRWb0tmSzFi
            UEVqOHg3WklUSnNIaFM0b3FJYXdJcUUK1l0eDcR/rVnSGYBaNYRXCpXrSweMASOI
            qL8+SMxpFxYQ3Pb5nvZdO1squUAkBHHSzLcZFfK4c02jx6bYeLRT+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T08:26:44Z"
    mac: ENC[AES256_GCM,data:jCcp0kdGInLV3X6iVNgEF+3APMEE5l8QJkvEPG+4ODLufwMCseu53Lg/BwF504BcEYfiHweTabAqzIQZC3QR6p9SFcw67LQp9nqNhwud0g6fWbVA8rtLU3LcdeQe8eSo8ZFSJHeWYjQCnkB4fwmb8X4d/PWWjyCzK3wXG3W8BsY=,iv:fRk5UaAXCKBrGa1cBdGFXmvEr72DQIvnIFuOFGkVX20=,tag:xL4H09r/cyrcIiY8rLW3Hg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
