apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Zhm/iqi6Hxk3ryks55V2DHrWrSt1FZXY1ZgaVKOEojKfP8qtW7w0x5r58cRZ+FbnYQyiIGulX1QgwhgnWR9/AOI=,iv:v1CgU76JPIxVnjaQgI1TyhKQen9TnM0n2CoFgiASThQ=,tag:5BIGMZzB/uMhOaMDElrLpw==,type:comment]
    #ENC[AES256_GCM,data:NVAT3hXDijP6uF/wc2j7yPqeT1iI6Lyh4KqCJaCluPPr+hOiLlQNESJ6T/g=,iv:8tiF53BdpBJ9J7T5oIL4jNTEXbL60b1A2KVLoLllpUs=,tag:DUZB3WcWPutDhJ/G1byzBA==,type:comment]
    VIP: ENC[AES256_GCM,data:hHBE9148wfZEl9Sz,iv:yzmuHFzmZ1j8MJfn/cokQTH+xQDUNX9XwKseMT5w+4U=,tag:fGNCntRr3SGFo8WvrKsSTw==,type:str]
    #ENC[AES256_GCM,data:YDx0btaxJ0+/ASUUbQpc8lcqEvwV9Hiu+iw=,iv:CXBd/Vdb5LetOjjHTA4xnvmX3jHhwHu5jVIPrSq0F70=,tag:rtVxlgBekOPaD54swq9UPg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:6oKNgBoRDhJZYxCR,iv:/ca5klx5Xc3t6N2NxnDYhuaBbgn6W2qnKHOzzkbiYCg=,tag:kZI5gsaZW+QE3f2RQqe2zA==,type:str]
    #ENC[AES256_GCM,data:zkwOZGBMXSI+rAWjYsoKRZqFo3JXtO/UM8fI1OSh46OX+w==,iv:vCIL4i4+TDRDe89DrhOV6LpORTMy7WWFBYeMHbgK4dc=,tag:oitg7Eppk7dhm+dVZGhzyw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Ccb7ph/oQhs5rPc=,iv:5bDgFIus+DJ1yLwUFG1xjoA3LTZ4rq1BoboiC4ED1zA=,tag:wticrjWa6SKGIdjDAIeCMA==,type:str]
    #ENC[AES256_GCM,data:poTBMz5So5pNrbzv7R0kiV/Z6/9fld4wP1P3i1kBYfKfq4PKndXE6ybK9jgW9zQ=,iv:SSV7mTdrDKgtfP8h7tBiq7PBUrZ+zMMMY7ziV64eEts=,tag:e9NYh6fSbpEf5rI7u9DvBg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:QomT1bwMNvQAdagUFrOXq6oyJzNRyACodg==,iv:fmCIQ/DFJTobDVHzxRaBAsd9Fl7Wg9k3FYa3moJZ+4A=,tag:mnA8iBgDMT95J/2LyFudVQ==,type:str]
    #ENC[AES256_GCM,data:v6LwZ1r4JWVH0rx2l/noOCkAQDAmIc82/fs8q1Te1a19JSfhlsDDat/MCXUvZ9MN3Q/IW8vF5wFBizoZ2Nqp7sgLu630ZXMFpJYPsdPKnuk=,iv:j5cTk7WNpeoM4UBYj4HITs5bepNttwu3uFhW5s1/EI0=,tag:ca+akdsN4hZbnKfGQizzwA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:22G7AchNYwkPi6jk,iv:8YnAI/N3+PByIHjKY7Fkz8N58kAzdcn3qNxKV0L582s=,tag:0H0hore5SMkq9y3CbgEVnQ==,type:str]
    #ENC[AES256_GCM,data:fIRunw8Ttp/lY6FI1vwON3F4FIEykUKPzo/mEio2Ds0jvrKNDLoHtGVADGaT1s4oOZmSfUZM0unxv3AdzAGR64SPrqs=,iv:H2iF7KVII4ftKAKO4D3wUxwPuxjKLx4D4D5NwrvDgWo=,tag:NgaPS5I+vOBmbADcHUsM4Q==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:Zplq5Yx+qSBHof5G,iv:n7H8PHiTpEOkWc1y/h2nqxAZIaLwCGMED3DatkzXl4s=,tag:PBer3S1AZ24RzcgBORZwKw==,type:str]
    #ENC[AES256_GCM,data:JbVIgIh6HrenFvYXPO+6Bzg6bWxW0xrqssYnINoVj3WsEsNvhZpi3AAMPmLiVzYLty25DRBi+bA=,iv:Asqyc9uFBC/aL2Y6g93pLPy+19v67gvqqNWZ7DsvL4o=,tag:qaGFWoRL2Lss2zAXhbB5Nw==,type:comment]
    #ENC[AES256_GCM,data:hmyysaslh2U4BzE/f/b3oOrrMqtp3F1UqA==,iv:/RKIt5onvcGggmkU/+8blComjK27Nihux+/RvOkU414=,tag:FWkZpsEYhWnLYl97qMSktw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:KEnWzA2+ZNZOEBNUtYADfUd8AvCZYEFgDFfT9L8U2wjk7MIwTw18DYg=,iv:Zs83he519EHTHUOoZrAVWo5zYAFHMJM3DEXz9+S3wKY=,tag:qqR0HcDa1qOpVvScxBKf6g==,type:str]
    #ENC[AES256_GCM,data:Ga0RdwuoOwmMD/xu5w==,iv:faV+bPv8Te+1gWgk6zsWBxIumGRleHjwQ1C7d1RBzX8=,tag:myuYh3jB/QgFRMl1ZpnTVw==,type:comment]
    PODNET: ENC[AES256_GCM,data:OTlNnR/JTylmBL5y9g==,iv:w3QqGZlW6vLgI069PCe8Usa6m+uokPZ9Dh43+vt9UCU=,tag:nDCXJT0W45qKPWWOsX38vw==,type:str]
    SVCNET: ENC[AES256_GCM,data:hXsZ98EpQjaZRao25A==,iv:tSLd4i8Okdt7367y8WBrguYXNwGGpgH09I3dmBaitak=,tag:9libV87N2tfrEHhZlj3KDw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:L019jA==,iv:5BZD7KqKcMyRHcDUWji+8oudhxqIFnvuEpCj3Y8lMF0=,tag:4w6Ob+82XC2czKdwNaN/bg==,type:str]
    #ENC[AES256_GCM,data:KSmOODJoWAw=,iv:PJFnf+fJI9u2hAASURunI/EtEYqlHBmQSCe+0kVP4Z4=,tag:qS4SdEFInHFJZlivLgwrew==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:dmQ8Sc+RdTKZg+kx,iv:NmjFyzyIx/ODsJ75UFp5im61Oy9exNWZTl33lR9MPys=,tag:nuvqeUd5mueBP/BARRsdmQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:WDlNjIdzfFrklQwn,iv:QD/d12EQP7lqPnCIuMA5uaBgxryzajBP4Mm512/H4Ic=,tag:peqpL2zf481mYO6FFiBKBw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:J2OVkI0rKSuu00k=,iv:URuv3wNfF8/a6BAhqONt7/DyN/fN9Vfen7AKwwnGPNk=,tag:QBOk5yJJAn9oog+OlpTOTw==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:p89cFX5In/VkIw==,iv:J0MIKgS3GpUbNwYuuWTtbikGjglG5nCxECrsXSCRHU8=,tag:3OtOhCj6GO+qyS1UAmQOrw==,type:str]
    #ENC[AES256_GCM,data:rbNZEnU=,iv:OA5kVjX00M9zOfxiZfScLltd68cutd+gNNvPMisbxBs=,tag:M4XqawO6ZNvjhxroyA0WEw==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:fx7+qDQcdt6FLZwW,iv:l3xrj7YqbalGjR+ZGR0jAGulCnS7U6F+CgNrvgiH3VI=,tag:MN4n+7ixOMNJRVcnRp8wew==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:nmaw8WD8gjMQ7R2Af3PL95YW2yNCjW6jYpIczeru1GhEcLk3AWPBpi71oiGR+BdKDO43bhwr,iv:bpSAlho82cb0+5AAKfSGrOu3Vh/1x0/Kc8oVyA3VrvE=,tag:g4ezSoT2lUmcMyBwXLFsHw==,type:str]
    #ENC[AES256_GCM,data:0dtyjacq6vYFcJU=,iv:Tml4CcQeMcKcQ4usotxLyFfl9BC5PaUPJk6bWSnMqZI=,tag:4oPbetHPuRMbPQmf27p11w==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:NQoCipKaHzMElYN1,iv:zbaHCM564SuQu9xF9FIlhnnXbFasC7d5i66rvJLr3g8=,tag:nJIPf0ZcoX77ArkvHympGQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:ydLAhRMYdGBmJCVuGQiW3mBsMg==,iv:ZlnTcEySUxybir8Ibq0Z817/IOJyhWI35URvTC9dELU=,tag:7L9JoRCr7xa99YOkJnIOlw==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:FZC0qDhyhQvSkeJWGKNgsQ==,iv:XECEjYRclEr4BC8ED2IledsSoetkVfkOCNRg3UQGeO0=,tag:VMSNFQ4q7kpNyz7ks9U0AA==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:QpGjXo4pmRCdXSJ1XxXd45KmG8IEHwdC3A8SIQAOX8W5,iv:bUNEoKzl1gEqjaVx7bFt3PBRsRhlyQhK5FG+cZ9915E=,tag:+sV0MMA5TaNnZKW2H0GbAg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:q49cAIxbGM8TB6zRWSBpJV6tnt0sWVUQK+19KWfGdEZK,iv:4/ww7UPP+YV9m43u5LncwuGy1a8OWFo+0dnKtQSvy8E=,tag:eswsb7edatS05bc4jMKmGw==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:20Qcmkb18WAGBHBrTO/NEucJZTGSL1aZSNpmkvmHhfg=,iv:nAwo0lm/T8l4jdd1zykauXRIAU93Kux/AgVbnxFWXjw=,tag:ax3vxHqceEDUMPOIGmc2Qw==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:Zy8d+2tt2erj5h8b8udQ7pQ/tyvefg==,iv:xCuF72Zz9kEvHrKy6yRMY+bwjxGg3vajdvNmxVtNeVk=,tag:h9KskriIpGl1orjjX3QNMA==,type:str]
    #ENC[AES256_GCM,data:+5Esqw==,iv:hF9OS0gs7KB8DK6ATI5WKxpFOehuQigtnn+4ByoYrjw=,tag:eys5J44YsO2EJpDbqR9DEA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:v3S2qIdB,iv:rvaYAxhTgMsYseSzJHVAo+d9dXViA72JM7mWIdLSHNU=,tag:o40awvTHwfjv+CD1qivn7w==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GAzTtCcBx8f6zeIPuQBKbV93LPlGJKRCXmwo5NRlT7IDAQsDvDgtpQP+Zmw=,iv:L61jqAcewvuv/V7tdP+Dy/WIbh7jul3Md6rHmkxZZso=,tag:kwGFoQHW/5rOAOLv4LZHxQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:jRacZW2XbTo8uCsaQ60u6vuzeAxWua2ki6qN/+ovAq0jf9+wVCwtzlF8eA4=,iv:mc9zCFZ8g3Lp1XF5trZZggQfARBHdynzicJxq4A2Wt8=,tag:qPtCrU0i6nqitJlCpz1Kmg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:J7qdLm5fNhm3yh4dyeNNOhE=,iv:798q2TeKW13sYGIPA0Zn043RnSv6/vVor8YMsDAoC48=,tag:TqTCqRoRt7tYIGP8Nx5k2Q==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:c+fQt60=,iv:KjkJdiofVIc4tTyh4e9rtnTEeUvm0UaiMMLeAvYfQNQ=,tag:WZC97EUYr63qIYzusglpdQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:KxeNAqlukvVBbDw5ljKhD8zXaxVTCrQvVBWHj+cko7OU,iv:yplKaXgog5KMzCid6Uzeq6QjRTbJKQpl4WSMrcmIEww=,tag:8ITa1sY3kzYT10MxK+eq/g==,type:str]
    #ENC[AES256_GCM,data:VmsW,iv:r31RI9O+Vht+hWo0Z+idx0yN3Fw3reMEe9a3fWHe4no=,tag:hKRZ9I8CFEMSE/Wp4vGEAg==,type:comment]
    S3ID: ENC[AES256_GCM,data:bLAAMqaS3Z+YNsbsC26vLsC9f80=,iv:lQPMztpW7+h5FBlWAffCc+LeA9R2TEPNQbIxcTXJiUM=,tag:CIbxGLoRDvSwqH0mS+Yeig==,type:str]
    S3KEY: ENC[AES256_GCM,data:xZg104ddcGh3pw03oJ65Hj8YzUBOd3Vslw6yUJNYsnLWsg4gFbKceQ==,iv:2ABY1Wl3SV2wBKoPkuYhb4GYmJ6f+eprZHbCUNAzaS8=,tag:Iiva1cVXDz7ZNYtQ6aShiQ==,type:str]
    S3URL: ENC[AES256_GCM,data:/jQjXQQJSBQ8meLEEDT6wvP6e65w+Yt8qQ==,iv:UqMMgmx+EafjgeJkGF3OJN/WnUe9vnjwrUnaj3KsRlc=,tag:4G0vc3Gng8tWISdxQjy/9Q==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:gKUgpYfV,iv:rKE0WrXrVef08pklwQe3A8nnsdgeE1EZ92bIR2VVH0s=,tag:9rQv4OTa2e/ZOzgVoZwj6g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bHNKTFNWU1JadUp0SGhm
            ZU9mTDlPcTJWSGU2c01ZNkZOZlBsZjRlTEVzClVQVWNNa2RVLyt5Tmswd1U1T2J4
            Sit0SSticldhTEUydkpJcGh0bGYwVVEKLS0tIEJGS1FLckRHMUlUb2o2REtmSWh2
            Y21UWnhQVFlMTm1RMkpxd3A3dzRvdFUKtaiXH2a4q8j0U1P+k9Kio7qSfkSGfoJM
            89/ZTjZEGnR3gWkpAtVwncxbaaqbjY/r9nwPPUBWJAv3QxlUOQhrLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T19:07:03Z"
    mac: ENC[AES256_GCM,data:4viEuGEAvfj1ZbORp3rf7fRc79YRkMXnWdx+zv4C5NisFBi4KA0OVIDpu+CN5GXIuuI+eWcQn7p0jZdCfHcRdltMWOq6tzycqi40wTY815nR8bsI7lqGOYyFLdSVvJ6kBgPTzT0eDhCMvGQme/kblWyxJ4LOUgKpRmY4xxMGeXE=,iv:GrXHV/o2DR89CXHL1I6ZJLjtaaB10qarCMGvjgI4fHM=,tag:toi/icrzNYcRAdU+tR7TRA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
