apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:zJXdDA30fmIV3mqPblZxjmLQMd7CKMHX1QP4TpSeXh02zjk/vY0pP0YochyfXtwcxCFWmKqpk8HNmjLzeb1WOSg=,iv:YaOqYrwsy9PoFNP4IC1epazVugiCQK7k/9L3/JtqbhE=,tag:bKG5Bc/+uIi1sMu7a33JzA==,type:comment]
    #ENC[AES256_GCM,data:Wdz4+s6SIb9qI8pqdcLSX40tigESCyHwrwD1QPy3IJEsCGuRVhNeQ/eeVMg=,iv:6lbN+BXDxe42tf2g+0/pRpyc6PlnjQV0dlHnx1stjsY=,tag:Ux1T1C2d7+Tt8mAOjqvzIA==,type:comment]
    VIP: ENC[AES256_GCM,data:acmlY6x+a+V3DGoV,iv:9LiU5gMK/+NAnOea1KX75ZHhh4dGhXRRHEaMydukijM=,tag:HB0pP9ySOPmgcJuxy9+ETQ==,type:str]
    #ENC[AES256_GCM,data:F9+DnkSZwShiAfsKA5c5MwYsOAuIe3jCRms=,iv:Jv6QfsWQs596zkiF2i6HeS31QmHjaaoxvrmc/qZVtfM=,tag:I548IO/ZRpHpHgC1DjLE4A==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:kgZrgx3W3EzJyZTc,iv:OmpHkL++n2ciiFjpWDtLsCE5HYLCfI7L4QgH7aXuEeY=,tag:WGOlFD6fe+Dz4VdjQD1Eyw==,type:str]
    #ENC[AES256_GCM,data:cSipW/xQvAChy8VO4gRvQ6LQxwHoHVZuRdPV4N2UfzuzRw==,iv:5br89YzoUyHF4q3wG4Iy9Z9dLovB7WfMzad8veAXtso=,tag:XNUXIG8MXcoi30ZXuWOQnQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:hy6VqzuuLNDOprQ=,iv:lqxtQjJ09CdhlzcrxL6g5NTzDBzkAGlVVXFoUDP0bOA=,tag:6fglU8pEY4zxu2jeRutxkw==,type:str]
    #ENC[AES256_GCM,data:oL5E8GQlowH98Vz4JhWeX6HtWRFjjUyAQuES1vOYfBnPc0xcxogIeuKnrZKvJD0=,iv:Plb1SxJsN4TqtZiN7T+fWHA4mdIQjJ2K4+YU24Ta8/o=,tag:bXVzqRN/PoYMp+IMJur1Ew==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:lCE5gABKmJarvAz9juIGCnUH9DPPea4Q5g==,iv:gF6L3lCGerQphiWTd1KsOo7DG1AYbh2ecqfM9eMT8II=,tag:IR/aru3asf87OJjM7wdjug==,type:str]
    #ENC[AES256_GCM,data:SeV/ypJr2fQG5lDXyxk/gymZZNTZS9+9MtK1de/sVIFh6vFEJTvnV2OiGeE3J27i+AEUQHEBP2UtjPM1EUbvwbWvbLRfqnczDV9nxVH5VF0=,iv:CglLK5/+fhqAWcinEbIOs3DRNWGVkoTS7aYJsZXK2XI=,tag:Y2MBbDsaSpqszmtB2r36Cw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:pYMzU/vM+iAYxIWj,iv:bLjXlh10n3ARD8nMQMEBhorTdd2KHvMVsTcQiJjdKDU=,tag:f8PYhBCOcCTaNZ9s+S1ktw==,type:str]
    #ENC[AES256_GCM,data:WrWAWM1gKmh+eP7AJjk5p3nCb3rSxW7oxbLjL3aW0F957JVuPaU6OX1NhMwRMGMF6NDxm4ILkZ7ido8E+n8/W/E3EKE=,iv:y6fMP/wT3bFq6XaT2VSaJ6Y9hQ0f/AyCAFuD5E4kv0c=,tag:hf4Fgef3IYdGIl7P6qC1Gw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:/oRRCQqQ6r1KV7D1,iv:MLC0rSe1DKsCVNJQ7Zf3qFFfkNq1FzidSSE63f/6X34=,tag:Fta1M74gnbLQsjhsVgpQJg==,type:str]
    #ENC[AES256_GCM,data:COnKFnzl0TM8+GPafo2eWbCxMRwMUZ5ZM/kZ7i+qJIbwLO1QuSBBrFDHeYuZkv5X2//yF1bn4ok=,iv:51i/ZPo2T/e9qNp1Bxaqn+PMQMzWs8tESDJtQBG2GzU=,tag:7pOQ94JGzvMtuKkxw4K2fA==,type:comment]
    #ENC[AES256_GCM,data:Thv3vOhynwoP+8RPoMRBJISZygiiPrcI9Q==,iv:nvZW9h0e3sDinAFEcJKKXslGXVh+CAejqAWPy+QeCN0=,tag:5rBEYG8t3NsplzFIMGS2kw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:ULffmdAutPgzU1rJoFBIyFF3sa6wAOEus4kVKQRTgvZx0DGHzgUmjIw=,iv:OEpG5mkQXSjoLCs+s79YjGfGGsfrcyV9IZ/WIUiEROc=,tag:CQqZTIb13tE0Hqe8QQY4Hg==,type:str]
    #ENC[AES256_GCM,data:pVV08x+FZ9kSZRqTeA==,iv:x+uzWJbbdc/IIfHR0WsQKWKo+s/SwRHxDght8x5zkNc=,tag:g7lEEScw9xssM3XncZIU9g==,type:comment]
    PODNET: ENC[AES256_GCM,data:RSmdiHVkuki6ZqwBtw==,iv:2f4YJID966o352GS5suIz5ao2FuXBhSIhECnNMacfWQ=,tag:KCaye97ghkWC6SOOM8gQXw==,type:str]
    SVCNET: ENC[AES256_GCM,data:9ToM3ed+gQ/WQEFgGw==,iv:O97VL+A516UWMVzBIhvBvkroG+UFU/bHldkIE8XwRSU=,tag:QqkW6OPFzI8wnIE46ZTWFw==,type:str]
    #ENC[AES256_GCM,data:NBRC+kNJ+8U=,iv:AaB14tnxI7DAaF4tpZJH+KyGOFfTvWp4Bu9nf1nGjBk=,tag:SKtLHRkYaNqquJGgFuWbSQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:rimaRTXcN+Wc9Ujx,iv:raKpTCnsgICx7whcfekuEoEzBLkAsaCzr7ypnatrX+M=,tag:vOM1Cfnr+t4HQiLyCS7caw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:BjWuJNvHrtIjRugB,iv:LR/EWcOU2CTPzZ7zy4l2SGys0wNnTxP6/Gq7+tospkU=,tag:SP8/iSIhTywz/IhSJ6Kp7g==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:wicXJ/jiDJcZZf4=,iv:OjEy9RSNKK69/dtlj1wVIXjXdn/UZ0psYRyjtW4+x0U=,tag:HTGomUrerlZIwLbg5b1vmw==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:zwBecxGGu5d2bQ==,iv:CmoCnJRmmZlN6AP3V0D2riw7ajAsqUjOi6zT+JbvTkI=,tag:SzwEqjkTMNgtTbJILjPIUA==,type:str]
    #ENC[AES256_GCM,data:yn+By/g=,iv:xs8ZzdrsqL0RYuVtjRxbXADRBNGGZ9YahVVpeT/uoMQ=,tag:RmQj8UdyyCBkUrntB6AQDQ==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:6KQbE9Nt1s5otKfT,iv:H+kWO32O7r7IGYmq1YVYF9B+eYh8UGqXAQQHC3ZYgAI=,tag:zkBzhoCeYnMNffqVhlhaeA==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:vH7K79LYYOEVaBD4pme2xELXsUphOhBL8a9xOdk7SNzZkQs2wA3rHpYtWqNriKdM6Kvmj/OQ,iv:qYqFzEYrjFww/4Pivz8y5+/BltZel6meIhkiOYp1nZI=,tag:6X9CZBqlRC+UBOmZlujs6A==,type:str]
    #ENC[AES256_GCM,data:l+L4rDBtRdXqmQU=,iv:HHjXUKdO0EGo/F4pKmkulD0g+TG7cHXbJwSZ2uL2hz0=,tag:1vAKvEenAIklO9ssYtKWpQ==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:4v535U955QTBV35G,iv:KIbzRUuY+cr1EW3zCtSInE+XbhhjNEzqUgzb1IkOQrc=,tag:W1ZZtCbywxx5pAoOlLbIcA==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:YnqI6ZPyMa+KN55HOZcByP+GXA==,iv:LWRyFPBQiGt3H49XW/tD5CkVV5+nq0KfXyv53LNX+bM=,tag:leMQRBVh4J5GEyCH/O5J3w==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:pKCRUbq0bj/c9Qz0NoRoWA==,iv:EizH1rnvPrNaFqDO93YVMVayXaazhND4WSaPJr8MZ3g=,tag:tg22ckLTEEG9ZeWH+zVutg==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:AvZt4ihLoHimMWDjdTVkkuZqDqCeDo4Lq0RT9Za34ssc,iv:vY0ZW6w84NHJfbB2JX32sPdvqZ1L37BcLwWYQ+dGdMQ=,tag:oUNxT0Zmp5izQlyaPGEaWg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:PCjLJazWkVJfWgJIy9UA+pBa9JYDiWY+6Qy2lc4lcSUU,iv:s/vx+v4D44OV1l4HW+GxhFhUnOENCCY9vHeAGF/KOTk=,tag:WM4mNLfd3dsq4yZnR27eQg==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:Y6lg+Yg4GRD8w9Xvg4mLz68eqXLP/+4qZf71LZX8new=,iv:o/4L/98nBdfXFYUvPJ/jkuG+25RYZ6CVi6AIdeWLAFI=,tag:wNpHHmBJza/h76kkdhQqrA==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:8VCPc8k/BwXSMBMdbJQAMvCmxW/hKA==,iv:FR1CTRomxDsjUFZSS7Qvo+Q8mFPN8TAAmeKrJqDkjmk=,tag:ajdK2x0WMqShjYiRf6jwbQ==,type:str]
    #ENC[AES256_GCM,data:Cr948Q==,iv:l87SihJW3hz4MTvs0nEWDJnogHXBk/2CWSDeeTp4I24=,tag:jC83w8k1jNwKX+nhoo4FzA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:+Ofs+p6t,iv:Y7a157TekjrUHezzELT2+3/FNT6O+swOANt+IHN431k=,tag:IeFOmM6qT1jjjGn7RLtA3Q==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:pTQl7ecy+2kKvvGIOxEo8DdD1qr3ogf2IEack7sPm1fqNFe+4SjMkeDz0XY=,iv:vxd/RgUaWBjgn/NQIcF//2bpYgC2YYSFJ0GHd5W0GcQ=,tag:grA6kAQc0xNxriIl1SJepg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:CmCCecfzuk6/bWAAaY2+ZFVmRbqum5Hkz3eq3hHXdVzCq7cohqJSDzquDRc=,iv:YxNgCXoP4gq0VDBCix5zZNRl6oTBBuMsxZbL4fTrBFw=,tag:jC1nDjFWOSMV2DJzqNTsCg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:D/StAMuGyK0GDw6BiIq1uzA=,iv:31hFMXWSgHm3EISVXVdzmRuQ4Dv84ZNKyqy0I+QfwXc=,tag:8UtFqTGAyR0+5NCiCxj8Eg==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:2UdPVWQ=,iv:5+5eNWzk2WZncCPoYFT5GZTtHj+teDykKWPDWUWrykA=,tag:Ghije/jjN007xjSFCbrnlA==,type:int]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:8NnAUJh6iGdlpB+39swnuwyRB1SDmT7ysvIRMD7eU72x,iv:lBy7Dqx94cAwxSDb+FVA2l4ADR4H4gHcjNDqjUx5UJg=,tag:mOH3hdpy7/BV1Jq5HSET8Q==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVNXb1ZZMGdpdmFOR01B
            THJXRHF4ZnZFaStqMXZWNEQxeno1VkprQ2xjCkluQXgvM01Va3JEU1RXdnFWMTV3
            ajlod3pPWldKd1hRTmJLOUNPR0Q4QTQKLS0tIGM3SmkyWkhpaXhBb2lIcjY4Q3JN
            NUppdllqMTRvSE1QUzVJQnlvMzB0cGsKfBP6VDPi+ybgLT+kWdLCyJzNW4Sw2PBJ
            hEDuwjoo977KkcBegJ2NF2MfAXD2Y8SjrK6NVdgTzrT7ouYozZmrSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T08:02:49Z"
    mac: ENC[AES256_GCM,data:d+/Ddorq5Sc2YsRZma0VFNXu2EhmGju0ReLjyIncqnlmode8PmpMLq10eCuO2Z857tg0KGKdbqH7VU1+NPTUKbwKa4tSN0RWmr4GnreYz2TLW2rXvvMHjz4P54rp2AERvfTYzToMqe8Voqm8p0DtvPlq2EwWrjcXefX5x7DNfOo=,iv:wJsRYi3FO4CC7xB3Pg0ovryWnQdldp5M5VCgtcwZjo0=,tag:3lHIgvuWYuTHLjw02BdZDg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
