apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:4dagIxDNWNXWr9eliEpRo4htnJnPpTOEqhWgi4TS8Y0QvfOiGm2h4tCFV5dOTvffwmBii11HJ/0BEicM81hxTG0=,iv:aXhf5RVu9jRGgTVIMYwMGxSMOyjA1yz7P6lI3Nyv5IQ=,tag:GX4+2sFD4Pv/0emXtXhHEg==,type:comment]
    #ENC[AES256_GCM,data:0VlIgXQ+CuZ0tSuHX5A1ogZICQkiRgWo+CFpQPlERQRHsmuNAE6iaOXfyQg=,iv:VukpF7Jm4UJIV17TZM5B7E7Ct1t0KFlhd5rtsihjYVE=,tag:zbTsTzOH2kRrWTvqQv+oXQ==,type:comment]
    VIP: ENC[AES256_GCM,data:CMT7XYy2DQ7TvzsO,iv:LsVdKqZReSKkBN5RMV4009xPD7ZGj4pvfsol0Iu7lqs=,tag:+I00LDcEcdueIQ7Q7zCdOg==,type:str]
    #ENC[AES256_GCM,data:fLz7E00O7RvVVEm466EMsN/dQDDZUZ9o+I4=,iv:3EEHhcM3uA2AGVv3Ok7JqeVFeAT2Cx4hgCy8kKm9pOg=,tag:FFksxU2QnbrHInRwzUUirw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:J/e5y2zt1RLatocu,iv:WFQDJO8R0sfIV8BVq/TCFIIYCkt+zc6gBoIge4eyeeY=,tag:MP15OaI+fRLqliGm50Q4Sg==,type:str]
    #ENC[AES256_GCM,data:V0lSTQH/20UtmyV5KCP0IQgfVFvOGI1d7PMpMkZRqSOfMQ==,iv:n2oVdOMgJ990sObFjDQmWRCvu2d27xnIkCoHoCnshwc=,tag:GxDD2Ez66PEjQ7QJ9384XA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Ar0B6kCdNvXycYw=,iv:XyMfHGeF8HDPij20Yl8KkgiFdm+QEPVGqw/6jFXee0Q=,tag:oCnsY2DRMlEHJR0hwCd/0w==,type:str]
    #ENC[AES256_GCM,data:L7mU5Y36IufIl2i0vfetKxqNY/u0S7JDVTa5/IT/DPnm8R39lIFHOcF3mD1ePjc=,iv:5CRRiDmNoantZ59R5WXElx0SDAUYyHPwC7Lz5yqxn+Y=,tag:OWjWJBRCkk5BEatA9mtEAw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:isWz5/7hQ6IMOPtHPVy8Nv5GWN7hvHFQCg==,iv:vheCR3+1iOFORgnRl2SWcUPsV1WAfJue8ItJAw4MYLU=,tag:Krcekxi8Gq659mDi1E2a2g==,type:str]
    #ENC[AES256_GCM,data:ZvfEt4Z1mhNOgsLmnLiVSlSbx9KxXWdqWIfh8t7YFrnYfdXqlWvaUCRBFGg91dActp3pQvUQDPHL7kg76D+BAj8VwhiwzN3HZaKUjirCvFs=,iv:O4atofovIKlVPoR/IawFeB86/9CCVBejlK4KWQHEe4g=,tag:CugrwOhh3upbfpB+koRNYQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:5DYeFpv8smdrJkTu,iv:cnBnUSJgS86YMlCytkLqlzv0K7/Lk6BIK9w4AUnF6KE=,tag:WGIcP3PbwBuvAgLWxIzdWQ==,type:str]
    #ENC[AES256_GCM,data:+0KMYmaL6PFw/gtHd6fUY0c4S6/j1A8HZPA7eAIktEOMW2pzTvPqXoNR5U1tH94meHEVzhvrFsLWNKXa8eIca7IMFQ0=,iv:ITCW0SQbPgq5l9y5LLFGr+644zZGRU4IgN6hUhfX3O0=,tag:UwgPvlIU4eg3V0OB/ABeOQ==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:GGD6I6TiI+L24uJ4,iv:OQ4hGUD0lg6lV1w0ViMhg/eU/5aaOmr9Jg4qEbmraW4=,tag:tG7OedJ0Q2sR5MfxsfZOPw==,type:str]
    #ENC[AES256_GCM,data:IvceNw/5EDf8Jd2M4IJ6LNN/ICcFu2104hcaH6N/KAv95j17J3/R48rjsNjVtuz0ZloIkKOlcKw=,iv:XxyhQLcQkMmJ8so+SDuvVdEqBaPOyXsv7TJe3twoERo=,tag:dP89nkIzcrLq0KOO++lZPw==,type:comment]
    #ENC[AES256_GCM,data:POCF65gInfUcFzJMkpertLi241UA6+DzMQ==,iv:TJx3llZXBmq94rPWk9k4cT1u/aUz049n5yCnRGr+HnA=,tag:oO5Mj48fQ9BrlYvkIbSz6w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:q4FaQZCroQxW9LcpuAKjcmn+ag397XjxOUq9YzefQMU/WL9AwZT6MZY=,iv:EsD7tE91cuLP5fkL/vOqRIMIbEdAMSGbO+XrdRn3tcM=,tag:LiKvBN9Sg+ar9o+m76+eaQ==,type:str]
    #ENC[AES256_GCM,data:O5b2Wh7GWEnYKBjtqQ==,iv:4DfL3pSWlr4UBF9qqUVv1xffb+vxPjPBpalOhSCMPwA=,tag:Ts5QqdzNruBXI5uijOK/OQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:4gf8EvqgcXwZTLBG9w==,iv:INnB4BukxzoMb8SDexOhwwoFUkJgJc9uNan1CUyaA10=,tag:3NYWCKA4/eYDeazcdrIAvg==,type:str]
    SVCNET: ENC[AES256_GCM,data:oTE5qoyPjQ01nTzK8A==,iv:BMsDETXIXSVKg8QXba/ppw7Qcs9pxM4xfU3y4VbdYpY=,tag:6WVKT+3o0LsgNQ24ipG4cw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:8pzoZA==,iv:KIQM87Wg1Z5o75p7fb19hZbSJ7SjsD4PofBent5o9KY=,tag:B8jVUCtZjKoPerJAkdEvAQ==,type:str]
    #ENC[AES256_GCM,data:1v/mmKNkrAk=,iv:FQKEEY6zem8uDiX9W0nDVGk0bOD8coYOKdS4e73wYZA=,tag:LIVbIKulKhr/zuw7FV6LZQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:j0o+fL+kCq3l6zrQ,iv:KOxCZdFY4LGi0Gc/bKtkCr67mcw+gA9Qdo7073JBpVc=,tag:y7t4USbsBlI57vpjZi7mDQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:SOW5ciFUtvZo0D3n,iv:znX4qtuQqU/r5nNiWNdmgTlKZBRkVmz0Nz07MBMAxxY=,tag:K3ybySYYlq5Fy9hPU6CYqQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:yfmyKB7m2M37mlk=,iv:dpTqQxk2l11Q2nRLUy9U3scOAbnSpiPbIKfmDT64xaU=,tag:Fv9+Sg2tzpHaNR8C1c4CiQ==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:VlTJKO479Vor4g==,iv:ZCfaZfcDmMYFxt1NtCcehb0JJ18VnVWK5xx4cVJ9S+4=,tag:585Ouc4mLEm4eGqWG6CLQQ==,type:str]
    #ENC[AES256_GCM,data:zAcAuas=,iv:wI7vi2aP6fkOjdoyg6iwBwvPwfr4oAlB27T1dBtKWws=,tag:5LXXrZAwGNTNNE8nrgfosQ==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:vgGlTzFryFCfX6uL,iv:z15gNHCXeuUPYYYBso2VSyy6HUfK6R0KltR+MRiklqw=,tag:/AXkF4AZ8d21GdjXaNL/gw==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:oGIX6yoKT7uByGf+p+X4jh8WEUC/Jtm8KiuRC9eWY5Tkb83/LZIgk3+dW99kz0FutJxVqS2D,iv:mIuKLTv5bcjy8tW6D0VfxBBAk7YMroTs2jp61Z7hAl8=,tag:ljyC/NPSTjAr/OxlAcYgoQ==,type:str]
    #ENC[AES256_GCM,data:vy4p4E44QEo0spg=,iv:vy3Ng9NQOVXVMFqSwvt74Z5EMh7EVsGhAsczYk/4Kcg=,tag:BAFgkZDGx/On5bWrIUlnmQ==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:2UxfXCPTFE8p4il+,iv:+EkKVmr8ovW1JeC0MeEeDFKLPsMPDEHdsiGtnJD7NGY=,tag:UGGlnH/Jn9gQDyDu66L+/A==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:W2BvBFPlCt4OQnOl4Ccl0+txbA==,iv:X0D3kMkSdZGiJFN0ISP0oO5GmaV5CUSnbXsv95VvUx0=,tag:q4rwmiYiqwZ6A/Dyh0i5Ag==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:XVX+B75U3cQZtDxIE3vOGA==,iv:BoRPwrsLoGVKCtPJiFbseiyNJeO2yddrKSETAVi3WQ0=,tag:j+JIpEOuLCe2sl8sb04oWg==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:BtGZnQqx5OyFxl/PYW+1iaf8bq9g4CM1hcybZuF2sTYM,iv:clv3GgDEiAigFjn0r9xgCkBYIhfBgWBfRjFpVL/7Yh0=,tag:xy3aUl0zRKdK+EIh9VIZsA==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:WIqsn8z33Hpa3o5eiCvDDEGLUlVHM6CtHpjeaZv9OUz9,iv:kdyRy7R2RYVmkciDXXg74/wkkwoJeG6oZHz3tIOfOLw=,tag:06MoTcB2nZb/yNIUbdwbLw==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:bw6JPNsp4uNzUj09vIqiZm+OorglOfnErMMm2i1J5NU=,iv:DW/ka6HBPn0jHcYWj3KMV/F/X+g0965SEFXwK3VK8dU=,tag:02uC5P6ByJb43NOtPV3NQQ==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:USle16aSSApLzWr6R5AtmBta5a0ySw==,iv:mimb79b19SUa1rXO61rEkslmpjGKsSaC45Gxdxzsu3o=,tag:sDNz+OyVWzuIYvltsdaisg==,type:str]
    #ENC[AES256_GCM,data:3Ih+5A==,iv:Dq2EOoSTTvpo712DeDz4fWPbSOtK7Tztb+vw7wYQmXw=,tag:41zgxHnpDGmCQhUs34qZew==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:eIxxVTXH,iv:SJRZtCw9mNZC7dZSUxD6rb5qbI5we9GOpAeThxshzIk=,tag:ZiDj0KQ8qyyyInqS0kLwcA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:JLfvgG+HltlgSLcP/ndqfrardWoqQ0fdOUAerxkn0beI1xyUT4Qno3cqOiY=,iv:34XXo/ka045l53xjA7xUH3o4FPm9qIg9lcI21WOBReA=,tag:t4QFKFO90oRqjuXdT/QSoA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:2Vi+9I/yyM2Oxn579bdUWIjUTRT+vVeb+mqtcC4c2DN6+yQhogjDjpCNgGk=,iv:l4Eg8QHgecgLe4C5IV1eAapUAX8qDfDiFmpdw8J6My4=,tag:xUnPuZ5dzLGz7pVtQLw5HA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:THNiVXwWtvA00WVlPcov8S8=,iv:MAzIHbmB6h0FW9DvOvbo7Fk6qYbtxLRgn6u4wXwvUDI=,tag:a0jHcyQtUDKwydFbXwJgAg==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:X1mlhXw=,iv:OGOgdIFHZ6C6JZEoAVdNYEPMGm+eB+IaLIQAVpv9mT8=,tag:R8isLCWF3eIdnbFDei7leA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:puJYKDYfwTQS0Fhmil6I/iIeSeTNSY1RqGSHOK+fPKX9,iv:7DUjE7O5kLCx905GZBP+ifI93AtsKimUhIl3XOYhxJ4=,tag:racjD0dfJBGtwXQbrYz3oQ==,type:str]
    #ENC[AES256_GCM,data:4Db4,iv:vN9YoeJDCZa9bRybJQSJF254oRlidTqpQTAG1txppT4=,tag:XjLzDuFxR9ZWJqCq0lDCFg==,type:comment]
    S3ID: ENC[AES256_GCM,data:sWoE7aFTkbYkG2HLesE2hKJN9LI=,iv:rl33hknIqYq5TMRtvpMhVeTCpk1NHaN5+Ao70ehUJ3s=,tag:+oVN4e4j7IEKyP+A69SHUA==,type:str]
    S3KEY: ENC[AES256_GCM,data:yP0aPEDj9NWGGgvIt7i/fM3dqCgbbq2MDJ5Av0iwjnjyAx/pBefvLw==,iv:pNjNfA+4ygtovev2xg2DWVdIjg194pQLCx15+VG4tjA=,tag:kZ0N9C1afs6gsGKVC3/DHA==,type:str]
    S3URL: ENC[AES256_GCM,data:Z/bWVVsoP6hgdsKKLy4NdMtnTpjostctrXyFZSZGNRnb6QNCSngm6NGV+y2cBQ==,iv:UYXZiLxp+TqcGilw0gAODJau5D1D3wFlwpw+aiVBsGk=,tag:4SJYWb5NtS8KsS376Zw34g==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:a/ywbJbx,iv:9HFtETPuC7YhicBEoAj7nwdyHbweUUbqtBXcuXZVUzs=,tag:fbMGH1HdO3u7kwB0mDKhNA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:M+htZbkZHmy+BgjhzkEXlwA9ag==,iv:jHV3oM7yj+Rck54Gf04lVyp3S08Ij6wqGQWkW6vx118=,tag:fc0Rum12m6TK7fDPd/qomg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNmhjeUhKaEtWazZoeTAz
            MVZjNStvcnN6cWhGZ21sZG5UVTFXYUdZY0FZCnVzd29EZVIyQkRPdEEzU0JKN3kr
            TGtDMktIdHpxUW44WktNNmJGVk45aDAKLS0tIHU4cThVdkw0bXBNNmw2NGtMcy8z
            Vy81VENEcWt1Y0tDT2RKMWxMdXhNQ00Kf+7ENUYjuFKUzqOl4Q8NWgT292t2xrpe
            0veKEX4NdoDV70GTxYtpBD8eog2T8WGmYSVmtTBBoExhsJBo21f8Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-12T17:59:30Z"
    mac: ENC[AES256_GCM,data:4nT1WagOmxx1UDkiymBRPFGFViis+nE/CljdG0nPeWpoBeAgvY7zafH1RQ03wlD3/2BLce9A7bCjYDCPXlK+us98J+wX4oisKF06RevhfyzxuQy39w4lSy4V6HQs65tTIBxKgvPGyGowH+dKdtM79OdLMuB+CS3Z4v4VfI9DbRE=,iv:pOo7VbzgzpR5bg8Dm1zfYDVdQnT2ZpewfGd1nY4AQnc=,tag:id6FqBL8c9LL7Z91uGO/CA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
