apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Euz4ukFcSE47+AUq76A+AEsOoLnkVUzMbe/bR4YZ3vvo2Hyp1t377UP6NwzsSxftzeb5mRuXABdQhBVh2ia+AyA=,iv:tYRS4ZfV14ysPZ5NAjX/q4i5rUREpWDeUagwCw3sKnM=,tag:8owfDlJfDdwWGR8haw99tQ==,type:comment]
    #ENC[AES256_GCM,data:LZnyyuxhfPAQDhQWNIEHXYLQ2Dq2nTVw9WkGiqMkSEXzX1Cxs7TOG7Jvmy0=,iv:+76hIBLxk0PLQn4DNWkVNkqcQJwrl5+dFmqjbv28eA4=,tag:zGqAKe2ZYxdlUW69WvtY0w==,type:comment]
    VIP: ENC[AES256_GCM,data:f0pxSLvyfRahQYeS,iv:yRd7v38J30wSedXAxFN7sbj9RHZ15yWeLTHjn8HQo2Q=,tag:AR/Za1heNMD7PK10EqH6Nw==,type:str]
    #ENC[AES256_GCM,data:JPYZwZTYLTQjr8B/cWmLFQS2XY67FTyDUL8=,iv:BLj0ml9mPv06lC6qiDxFk7WrIRmZvfdC+2rSCH5/mTg=,tag:R0b/ndWidVcOd89VEHKRgw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:V3ydhTobZ4KkT0CY,iv:ms/Ok1dY1lR5ry9imcgLN/jJVsxOunqesHzFEq/K4rY=,tag:VoTIWwu5k+8HnBkhSR2xEA==,type:str]
    #ENC[AES256_GCM,data:KdJWjNVedJoeMTFvYrLz/I6V4JoGLlcgHQWZAAN4onL8MA==,iv:bCfBNz/qox4l8PRqHOnt2oihU/KJqcZdEC/8Cbejfl8=,tag:B2wBgIauiByhR6rAuSMEWA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:UuCGci9DJvhFJyU=,iv:7+RjB43Q/6ITkZ6i9V86o9aBR2MtdeCytwZVkgtmBk8=,tag:elCMqgdnBEVKVrGhdS0T/g==,type:str]
    #ENC[AES256_GCM,data:G4tgT1HaMgCFPQ4ZObJmWsKlGY5cYUyLXVFn38LRudQJ8HsE5fzb16mpDxLb804=,iv:V0k7CCt0aHA8jxEiOOtR2iY0gRQp02Ew++q+a0hsi88=,tag:9AHqap+P0e2NCYUSr8UT1w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:bMZeGUDsxo6YGA54xOsOTcmWDkd4ywyHNQ==,iv:WHmNhjPlCVx7OAHJjrwqHC7dIIdffSZ6g2a7pP4cV1I=,tag:AObuSacVi6dqF2AsYBGRkQ==,type:str]
    #ENC[AES256_GCM,data:Z3wrRXfYH/+cv0o49gQnPQOxZyOriAURlqsxs4urdXlbpJ9aAFBcEEAHFtaoWPB8CbjxrvwOY5K7YVMqdwEhrqzEtadu7p/b/CzAmWfKHxg=,iv:IaknCSYf84vgmyxEZUBZy17IQfkP5329slWUfl2Zx0U=,tag:Rcev9AYYwRIgwuvVvyMa9A==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:WizIiAEtwi3vTlXA,iv:f+O/zJizSzQQSUZkaKIeGeqcHBZUI62eEem0f8pykdU=,tag:5U5ZX7wIqkCZUPgePcQt9g==,type:str]
    #ENC[AES256_GCM,data:zOcIhcbnb4wcvyp82ZFVG0wB+DptFJC3CIa1Fu9CcglbkGBmtZeQxJeuf/1AdyUv3kcpBWCgbpMz3lAt2h4MNYrekMw=,iv:Tjq0PAmc7NnmECRN/PUyYc1QsAxdF3yqqg90YTERkhk=,tag:aFJ4VDXzFB6484QT8FLDBw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:4IIojF2/M32Cit34,iv:yDqzQB8FhPaIEV75GBLHJANeGq6YH30PNrA9TuqUWPk=,tag:9nog0h9jXt/ui4+D2dRTIw==,type:str]
    #ENC[AES256_GCM,data:XY3PMrQ7tbNZwXQtJQE2wYKFwnUBBseEMjLRoYd2/eI1S2JBDn7/WIfNntZYCkq1m/BJWBedA8A=,iv:JWQIPBbg2ds7p/OY7omRwQVNd9k7fay2FXVzMP1BrYc=,tag:SsdWrC1cteKpkpKTmbr5zg==,type:comment]
    #ENC[AES256_GCM,data:I5+QGfaBffMMrCLQK7zkf1+doVKq3shDJw==,iv:UbG/iDZR+y8AEs9zmfdlDL92NM+uxbsP9MFI2j3f5lc=,tag:1EcNmkiEIGHz7BAZ8tHNXQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nMQJ9s+/cCJPxDJupJqJoDZB9a92ZYNh5LUW64NXgkeCic6Ke2Wyt6s=,iv:FV3/EdgneJzQMdy+pUzzSmO8MHPGn9OqzAXQqhuIqzE=,tag:+bShz+5GvkPeLABbyWyLyQ==,type:str]
    #ENC[AES256_GCM,data:7fbxobpV4bocFJtsxA==,iv:jlLiCy8m1QelAr47V2BU0FP+JyGBpD+SQQbemL7quLk=,tag:BkySQ8W05Dv/XA2jbYkZ0A==,type:comment]
    PODNET: ENC[AES256_GCM,data:aBJ65wKvjazr41U1YQ==,iv:uY+LzyRJ2k8CkTwoWyAsBMECuq4qujgbMBgM9MPnb6s=,tag:roeWSzGwY5/RaXcvcMjcNw==,type:str]
    SVCNET: ENC[AES256_GCM,data:efWt70Yf0wiseY2eYQ==,iv:1PvhbZlvEcX1XNCFYajgBVjXahxc/ULjiBExOpTMw9w=,tag:NoivrUrfA0t2tC03Ki4YYA==,type:str]
    #
    TRAEFIK_IP: ENC[AES256_GCM,data:RcGLhsL8YnQlIHNq,iv:m6QChWz5CF/dy0Yhb4U/aIkZm7BqvGxDNJYo4LqCsOQ=,tag:iDz/IxI8nOi7Sj3Ije6DZg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:3qZY9w01XdEVhKM=,iv:OuwMvZ0Aslh7eIG9eu6m2S0ixqRAQtOr/FoGaLW68RM=,tag:OmiG4QD9Ep4ioI2LQ1eLvg==,type:str]
    #ENC[AES256_GCM,data:m/V/t0/g6ak3Nd8=,iv:wXtI/y5SdRtuAze0A10AMc5OkHv7Mo9us01adSHobhc=,tag:8o+yWX7/WsdWKZtt2qGRgQ==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:E4CzhuUU3CA+q+pe,iv:z9LitXz77Ny22auKR6MW771War5GJodgxznp9JagF1A=,tag:LOuWFLHJ3GSxZ4c8IP/zQg==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:risAusDgNhmxKgHtW274dQr1yA==,iv:yKcGF0dhHC2oskxUUzEeHA2mx4SUMYb+obGWCJit2no=,tag:gZdxNMVIAeYfnb0isl6pbg==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:ZH63pRwzJpBxjgaNhT9v5g==,iv:QMONNDyN7Tm9kizFseggO+4U4nCRa8yKZMOPGQGAjUc=,tag:ks14G/6AWBBBgrbllfpGZw==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:WDyeniVhRSZgJC6osSwx+7UeWH2IooAvl/jDIAW06mie,iv:Dva8bXvic/CAaZPjU9OSUnuz8htLVvWd1PdtY+5DSuA=,tag:zrQHQ9bzIe0RSKkDkA61Pg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:XDA/DWs5s48D/hFXpe7APY2BxpdSDZgrdNzxfvr3b80i,iv:pUdbbnOqocFGIesxmGZiVVEubT5iVD6L/geCrNu61PI=,tag:qzwxFKmy56Gio4TbshK18g==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:5NwA6xkMtCtxhvIBP74UX8S1STrNcWJDFIW5d7OSw4c=,iv:BBv80WxzvgEoDL5VjFUssvg4T673DbeYhESjzMzwpA0=,tag:TE9FYANPuZVuFMn88+38ow==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:4k/7CWY+GoT3ELrZX3OvU/RC6gbAJg==,iv:HezmZTrV8cmlWiLo1rCotOtIJ3vlmpYlkdoVmXAtv5A=,tag:GS4EMX1LUuqq9RqkhQRoCA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRU53ZEEyTTNIamlocHlQ
            a2xqUGk3V2syak5EUmo2aXZZQnYzU2M4T1VzCjhxblR2YU1oRHFnOTdzNEIrb1ZI
            TkxuUVl1UE93OTlOY2VnY0VxRDV0VzgKLS0tIDdFa2ZtbHQ5RXRNOUhmQ3RDbDhP
            SlFacTArZXM3QzJueU0zdVlQdHZoUTAKLnfClwpjgqVyWashVYk97/3L/bBplD0q
            xwRs9XnhSFoM5U8bP8ZZmGXCa6lU0YNeA7tUJFA/DgjmKs/FOANwdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T20:49:22Z"
    mac: ENC[AES256_GCM,data:lvjJR7wmzloN6JI5cqR9QKV4Lho8qcm4K5QsH5l7n5c6yeAD0CrxRWKZBxwwa11I9jpDPveeG+PyZ9+bACK9vg+e52SuGsbF11iMKl7Az1UTSZxNjHrqiR+s2PfIXERyTsSC2UJisUMmiNdDuQ6kvZqjxWl+OzhVpXns8GnIC30=,iv:2cK4m7ApgW4d2cL5ZrHeSvfYfcxRVB+nY/tZcMA32Cs=,tag:v0E1ho2qsW7Nogzx/yIpXw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
