apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:69tSfa0scLz5Glh4bWzpJq63Qcwqjpkm72rXR3wWDjWvzTGISEWEvpYoNksSbIeX2nwIiT7YFIKCaur39URHhm4=,iv:bbYBRSzCZrZFdvU0xuOh1t1Nffnw3+jo7nWFymlAFqs=,tag:aZrYjcwE5cUuQcLVe/A9hA==,type:comment]
    #ENC[AES256_GCM,data:1Wni+fD1x+zROTEPmFzXC0qO+3wrGiKtMiQvyVh/nG8U+D2K22edfQSgp8o=,iv:29IewpDfs/pdnEfaZDpfLm1FOUTij2ZXvBEZV8IZBlY=,tag:Z6sQRyfrDsELRat84tl8zQ==,type:comment]
    VIP: ENC[AES256_GCM,data:mnFk5wCZ4A1Wu7Ia,iv:mQERV76wqFLiuWZrnOwan9eOYIXkb2fkNqw7JIqB5nE=,tag:ei+YanEA3MMmhEHqEaL6NA==,type:str]
    #ENC[AES256_GCM,data:BWW1BgvwOBOD62+I89zGFMafkyDI80SLWK0=,iv:BkM4e5B107Y47y7n3zC89CQq9qHPq49+lUQv0my5nNQ=,tag:LoA3sPYxlGRtPZwbT+XcUQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:bokSmp5YxxBcQIb9,iv:QuP6YNQCIc429wC9SbnIcIQRYKqOs/ULnUkWPXHsnOM=,tag:0KEGjWBlxuItQwgjNm9TUQ==,type:str]
    #ENC[AES256_GCM,data:8zLd0cx+HCiavmvD74sloOY1Q179fF5O7IKox8DGCTZUqw==,iv:Dc7ma2eVLnG8dYqdY5gD5YonT1NOQweAzO2nRgru8qU=,tag:c/cYv1olP0QuXZm2wOfmdg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:CNT5Smdzq+L/FEs=,iv:CDnlwqo9o7I+Vk+pnZKdSrBi+rHXkr7odpa/ZgWgeyc=,tag:k0EWbNybEw/ZpUcqB0qlcw==,type:str]
    #ENC[AES256_GCM,data:z0R630vcg6ZYhVrqHYuJjuMlqE+++SguWmMz8krql/ePNL+/oUAfoDmnJXtYptk=,iv:Yz1oLGRyKEOsjTbvRdos5CjRT5+M5ldGhv1CrNSip98=,tag:frdws/cCKCsgTDzTFTBIdg==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:M3pgB/w7VnG7plVi0NK/LbCuWA9pEb2WVg==,iv:DAJ2dVzDVXVLie7i9XnHz/94qYFNQJqjJPe2FoYpMyA=,tag:zY3Jm9HTxdiclac4vONUtg==,type:str]
    #ENC[AES256_GCM,data:ygQWNBglQIBDWmAsMxBguvSqW/4aZxM3t7yS2vXuHwkJKDuIKeLgyjBbfVWHRUTO9bnckh2PD7qcK/odSo1NCkuMGGA9PvKkEMoBFLqdAqI=,iv:slJv012cC6fhyBgJLRdhH2vWjwhbRiY8tt/tP2LaWjQ=,tag:tBRI7WlP4BJxOpgrcmP7Uw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:xuU8TYoLZNU5Tw5B,iv:sXtTbCwaX257iGRe//7ppGFPIyZqX4I8C+DUSlv2ThY=,tag:0whKAf2E3c4AmGza1U05xA==,type:str]
    #ENC[AES256_GCM,data:Jy2Ir4xg9fhlJ2VfZhK1OGxgjClg/JWIex4COiIlaLEXoZ812GisogqXRz26ql8zsCg0DeQ4l+I6BgTZu6EaxRn3XTM=,iv:RGsVHb3eimtCeozWagLWX68OYVaS9yl+Z97Xucy9yHQ=,tag:dBVsU+mp9M4Mzq1fs5oaGA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:E1fI8zLfEyR1gA2z,iv:WI3d0+V8h4+0mjBjhJFOBHxLYwYrHT1WkcU/CTurqzo=,tag:XKytg4AlW2a/KT+H9bB/7A==,type:str]
    #ENC[AES256_GCM,data:bUJcOZzV+E63xGO0CteYFqtfHgmJ/E3Wot9pk41jzUANySWt4TzWt9vSekbL2jAVS6e0SQ4yFio=,iv:u+Ttkujb8jW87dq4L/VLpcgnC0w67rZP+u6c7+tqQm0=,tag:WcLwZ95TM+ZLPCQeoJsUpw==,type:comment]
    #ENC[AES256_GCM,data:JyyG8LsRgF8dK58nndCpPJVPwp9icbJC2A==,iv:UG4OEd8qCDHgtcyjbniP+BRXz/wpPKiJc2rD8qIedZ8=,tag:H08p3xFa+/QNxxFZrMPQdQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:4xwXcXgiKAFwpBEMowxnrn4t3dOZYp/wSU2yMnYRQTy4XGcu014jcc4=,iv:dKkT3nZvUXKXNe3gIbyGWcRlZmxAUEJZIKdb2weFTbg=,tag:9on/CmzZr0f2o6UCMICZQQ==,type:str]
    #ENC[AES256_GCM,data:2Xk89Eh9AIrPx7K68Q==,iv:b1aFzsijLvOcnZgNcZAIWmmvc4z9DKvML2q5GPQTjNU=,tag:lM2mYHPGszjbauPPGR6ozQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:s4AA45hFvBNbQSzUPA==,iv:aLUPBO0tB575jMuqezb1+wtQrVZZgJ+oi28WhlcDKaY=,tag:69T82x3Pl2sX6n3n+rWQZA==,type:str]
    SVCNET: ENC[AES256_GCM,data:hCpp2HUb/i4xJCkIgA==,iv:8vgH2PNab6TyrhZ0mYYBB7BevlKRXbssgzjQn9pvkWk=,tag:6t3rYhkvzWwia4VhiJUN3g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:VZLIhw==,iv:6GRf1kRZNuUiccrB0kYM1AcP9Z6Q5OwIgeqDytD/+G0=,tag:JcmmYRX0dVDzvZVW/P4/jA==,type:str]
    #ENC[AES256_GCM,data:0/imm+ouqiQ=,iv:/NJqe/5vN8FvdJov1PmQ3gX1yAIxguUVoVLFzm6u7OU=,tag:YREfqI+IdCx1sBSJEdSjtg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:H8wTTr0bm2i2ho7Y,iv:jjrevnfU3hLbxBHKHNnLfm0KUnykkuenurV0wgnlsZg=,tag:EyjKwUj22RvYjMVTJK68gQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:YlVEoOMoc1dPjod6,iv:G4VLUM4oesPBmaVAqNzeK90RgcOha1kv/nfU5xKKA0w=,tag:kqW+GWokuIiFW5RSxDRGlQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:QPkJwBYHbBdMtos=,iv:t9mLeL5vEp7c7eUgrjw/QAVtA3OsvoNIkjTq0F5kHDM=,tag:UYAF8vpSF/D/OqGD7crNTg==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:x+ohE/K03zvsEA==,iv:gNiqCffGA2CLtPLQWFRZ4DYUc1q8G1cQCL+N4TEaZds=,tag:YLQo8EdBaV3Hbo0XXy0W/A==,type:str]
    #ENC[AES256_GCM,data:yI4krio=,iv:WUs8mbtAvznvyZVJr/bElu5gEN1DVHnL5esVdlG+N5E=,tag:MRHs36DI58sXIT3HtRQdiw==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:PMWD+OrES8wQlmwr,iv:UZwu8M6Yl4GBk3kUvVJAujZQB8YFDjcQxzDEnExU6rk=,tag:/o4vrWmTuJnAUrqyfD/G0g==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:sXDomQxqvTKhP3yS7X1wt3Mgt7JH1WIDZESpsPfdbkJZbFzO8KgUYQ4XnREB6Ri+yyF/WcJK,iv:yqYc20dkNCDzlkCkIw4lUEdxxQHGhH2mAsZ1k1ypUyw=,tag:lZVFISbOgYIs7jM2ebsPAQ==,type:str]
    #ENC[AES256_GCM,data:IqQjjlgSe7HEOhs=,iv:4HSpaD9CF5aVD/fYQpsaISVh90ioyk7Yew286mwdY1o=,tag:cyQpAxy5BvIsMgyyx1dkFg==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:tayapE4gMR8GhlNJ,iv:l3nmfDfJB8Kj4ywRMduJEYV/V0vONCpRt5C0LhRDzik=,tag:aEgUvRBeWNYX3CPc0U7nfw==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:FPiSR7eSnV3LwYn3DKafV9tYMg==,iv:xTHwpJNF2NF/vWEqIZvuSj05LpntTlDhyIjG5g13+EE=,tag:VHj6gEVPsNH639mJHolCBQ==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:2TWuCAUmRoicdixLjJfdbg==,iv:vL9RM1UKgbRuHlXkiPZaWUnvUEBzxl3cIp3GadSOlG8=,tag:+HxOfl8tdK0msRdE+nRIGg==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:nnRnwnp1piFNfm2iJqIGgJRxN7crv/ci+04NLzDH/GVl,iv:0U72nFGjQSfKbCnazCL6pricUrFgMCXaWqTlM1qfWv4=,tag:/fARLGlHZaWVMo02auYDxA==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:2VnJPFuGzXQG9MmVnPPRtNdOY1+aXaKgc5GBlEMLpkTj,iv:2hoBnTyZeOq5fGyVtRqwiiNx+jC5zQM3KD5zBtT7K5k=,tag:OWShAzlpjYG2HO4Uw+m6rA==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:fUBY/Y9aCesaR4EMdkOcVCNG77B+PoaXal8UTftadZc=,iv:uvI+NZufYz8A07d7WIEMnbgyEF8+DNZYV/DG8KGRFTQ=,tag:/KXGaZT2XwOgOtuWQ8PQGg==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:5tcrW2hoO5uULhO/Fb0oGRb6klbvTA==,iv:sJz24dIM2aLO7BAyDDTp6J28h3YWIrN+M5tYf+QpfEk=,tag:lh7LNaYCZmEYAotLnZdNPg==,type:str]
    #ENC[AES256_GCM,data:0HJzzw==,iv:C/6NSIXOdwhY9TY+XUYjqdAREuRetN+r5pbyxcs7xRk=,tag:3Yu/LOnnpsCzPT8vAZJ+sw==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:yoGRgPcu,iv:phR/yKat7vFGZ2x8KB1yFOyGE8Mj5WvplOVdcU6u+uU=,tag:JJIORdAKGNyVn3T2CbA7IQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:BzUKv04CzGPeQjd0vynR06p8rSymbxZ0o3/xwllAKNKHVzZ8e7sQ2L3lENw=,iv:FENAaWatmAI4ApUpQtan/BIgygqyAYGfecho/1a+akQ=,tag:xVDfmMA7d2qkrhyvss1vKQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:eOTDzvIKEQlZRb2w4pxbm8VBb0hI9rHvRtKHhkwnd4Dd2JvpjRF3cLgBHAw=,iv:ZrkQXLMV8VVvJsDcibfPQQZQshOMk2jUDv1Pwkbpozk=,tag:MTa2UiOzs50QfIWjmd3CsQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:mf4LEYK9N3U7vh/MH6ijAPM=,iv:EKRbNcj75HgEIK3e/lOgz+C9Ome3sxTuLVW6iWjxqgk=,tag:vpPsfTNVLANd0RArTbImiA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:iGUC5Nw=,iv:B6YMnqDOw9UuZCOZxCuWHxY4Z6zdLruCRweT3Z8qlsg=,tag:dzpIVKOVnztJY57DFDIAfA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:hMcH5+dDUyJNR/CFxf2lI/1kbmqk4BLQQKT7MeEtDGg1,iv:FkVyaYIXGCoz9I/KL4ooQH1ELxWlqcgN+IFPp3hRv3A=,tag:vDR+D9pEj+dYfCJ1NptMMQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWVhZYnNqL2s1UVBTZ3Bs
            akJXam9VSms5QzdoS1dyamJPcnE3SUdMZURRCkI1Q0lNbWg0OHpHOUtndzdKQXRX
            WWhRNXpYeFlPTDhqRUVXcTZ5WUxvTUUKLS0tICtqWjQ5Tkl2R3EzSU0zdVhZWHJx
            TzZ1WldWVDUzbFpuTWhJeEtwSjFwVzgKKq6LmBS976DpcaBKuiRqvHy+MI3mx0J6
            2qkPi0bSsfdnao/1tjhQiaEotfr5ovrClQz1YYh7xUXMx8ovm0uQLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T11:56:31Z"
    mac: ENC[AES256_GCM,data:IFJIzsNNm1PZGeXVQkgUgVPPwmO5WUcQVzXgrcn0rts4Tryssxaae/yUlVbqWuaT74XodHtd7sC8mfn+2AGiKI1l8kM4KhjcAJ0fR7kwvFoFsx2uS5yCz5BkObHMa+0RTQsh12PPKmpINVwsqMxE39cLo1oPIwM7nyw3sqwGnSU=,iv:OxMRYlR4LujUlnflq6SDgTd7ULqt992FuWlFSM9gIrE=,tag:LpPj3rtCikgWEqR/qQ8TLg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
