apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:CXnxWTMXcb+qVxGmnccEldaXaeb/08SPatpxXEPTVVMGp4tsa+k6Bpnxh8JOzkysBC0qQwDhCyW+ztWTgwkhn8M=,iv:CEyg8LZQDyLAmb3sIBzJmCuc/ahhCktELZwmzVbjrFs=,tag:t/8J0sSXThEZHMkIjUXN/Q==,type:comment]
    #ENC[AES256_GCM,data:zGQi6PSh3WZsAtq6qeLGCI8g1yZZdDY+Lib2u1F5pdEs9EXRTpwtmu4g7nc=,iv:CNUOuRJKsqUnO+S3Zd1gvocKM53WtdUg3e50xwmF6iI=,tag:IJNcSoZGAiyMwn0RbPkHMg==,type:comment]
    VIP: ENC[AES256_GCM,data:Vl5OgFklqqNpSpJs,iv:/PwItWGsxx9dTLejMeEcP0EuKj+rrkEZu8hVq+cn83k=,tag:ltNW/QNVbXZ5i9PrF/MfgA==,type:str]
    #ENC[AES256_GCM,data:f1bsFfpvsCIH58oNeas100PYigZT759klUU=,iv:6gbXhHjo6r2gupAwHTkJw8dSPLlywdP+a0GUqAFzyaA=,tag:8Kz/ia5CDNKK00d+Gclh5Q==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:mM74fZ5Wd64u543K,iv:InE8G0Qzk5YBwowVk2nfs7bVb+SAYJfnHocMl/dyn18=,tag:PwNG4vlAXU6n3s6gcpNvtg==,type:str]
    #ENC[AES256_GCM,data:fQAiZn6ROHX3gElb+6IUUAMWCqhleW8DUJJSuCX1fxPAcg==,iv:KX36F3su5qqoDWM9VFJMNSiky+YKBcv2pjyXhUvJqfc=,tag:d3g69oS29n/qfTzxGOrujA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:9zHlbiAcMxDU+yM=,iv:I+7wDz/qjB8CsoJzQPsNsiyiRkB8cuHe2Vc4TOTBjqA=,tag:6Guvvkhfx8VQsVAu+HrV8w==,type:str]
    #ENC[AES256_GCM,data:O8QOdNb90gz73VkUW39eS4pGXCzuuwltABWwqClf9DvnEMnQxRfYJuHWED8ssqc=,iv:R3J5T0RToLPA0zFXSdvHeOvVPLpEn9tGlo4jw1GqRBM=,tag:qxaXghKBNxLrWNue8NzG3A==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:OVpa4bHLhlwNVoMuIq1pQkJgXD3g4tnf0Q==,iv:qHVUGEU9YDYwrJ1PoaNIqAOttmV935qs3uMbyXzG5a8=,tag:WMDQjO4yY4fuM9wVxvztrg==,type:str]
    #ENC[AES256_GCM,data:DKYLxEWQ1CpA73lL/cn6MHdiIMieM3i401tRsMMizWMr6znZZljAeE8BSCvi05bdFHrKpYTyZSeNpfw3nr322c4A9D0B1Qy6H2VI5TR3lZc=,iv://B+IRcZmL8LFa9sD+ic5KN2zk7l+nhHJz8sOMYiCDM=,tag:VRG48k1vK/n5cyIfu1a+nQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:F6cndsAX84gRs7uJ,iv:9rKFhnNG0BIedcrXr/ad/vj26sQ+vcb/sSvUSNYAyOw=,tag:KWlJ4r0tHtgij9PVFSvD8g==,type:str]
    #ENC[AES256_GCM,data:qnrq4nhNAlZXu8kZO4pglXboiDXbwDMT/LM9zogLg6RZdALvOGSOe0tS167bXU5oat9XAOoy3sILHEQK4negE077Zcc=,iv:O40SRcOnSaKh12/fsqhUmas9vtjnudRmhjMnEaTEY34=,tag:ah/pRgmU/OlhstChzzgNDg==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:3t+UpBK6Pk7y0UdX,iv:+hjUBLbtqZs/hbhIT9derjYACPEaz+yes+8UzBkIXWY=,tag:5nlsiKpnSBN5MTiFr4dccA==,type:str]
    #ENC[AES256_GCM,data:z6EH/6zUZwypczkjRcTiFqXoF7cx73Nt2farl8zf2ndtekDFYb7nwfsjqYK7XehFi0HJOU7HJ/4=,iv:op1X7kiltpasiUZ3yxHYuLzmmn/TAEwbQLvgt8GK4bA=,tag:5c+1h7suqWVO6Zyk1jaepw==,type:comment]
    #ENC[AES256_GCM,data:V8GWw9yBhQMfLdktCoy9nAHp90L0XUj++w==,iv:EQSBlW5AKjHjmjv1bWzm25n2HpaAWfVpRrNO1T1qyCI=,tag:TeNERx5yX94ZMpAErtoQRA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:M9DfYi1sdZI7Ben3u8T2yIr9lsALUfBX4IaA5uKElCunqZrlZs7Opa0=,iv:p6FBpOPy5ncDcUdhjNKBVKeJKP3FjLhS61t5s9Mt6WQ=,tag:xhKiTwVYIso2qQVXMWd6nw==,type:str]
    #ENC[AES256_GCM,data:H4TExd2JDMnJl3+SIQ==,iv:pH/YVWwOSGQO1T/zLa1SY7MFnRkSTYi57eCy9s3A1cc=,tag:v+SAHRILUpBuXEStYROSRQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:8soIeUGdwoR02CzEvA==,iv:LLFrf+UtJhgWUmYn/bK7loVDA/GGy7UeYo89J+4xiSQ=,tag:V+R5gKiPwXwM0Z+Obx0Q1w==,type:str]
    SVCNET: ENC[AES256_GCM,data:4ZZmafkxthgJ0PFHDw==,iv:gmuZ4fb/h9mRHOgXYA6IEL6ll85KMde2DPIVlNmZ3Vo=,tag:9VhlhbG03eVhSHxXoyd3pQ==,type:str]
    #ENC[AES256_GCM,data:+bw8WAseWbY=,iv:8EHSTbRK3LJ6E4erqOvjwVcMykLOUfbXmbjeRCzFkTs=,tag:/q43UT9mhqkEb6DRlwoTGA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:nlcF/l44R9gb0gVp,iv:0Ezmp2ms9msWF5kDrXorHoKubjumtCtKDZSLka7+sFU=,tag:lE1r/vkk9fB31KhYGjoeBQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:I3H3o086svTl1YRw,iv:VcTNUM7c0dmX0uOeLJoAV3J2bqdT1heJrAYF66R+nWE=,tag:czUjnLoAbfuHOwlwonIfvw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:pDd0hJ3sRS1MY+A=,iv:lzPFU3zPZ/OuqVHUVGfdSNw6qyOd8tdZKztuU/mbWtQ=,tag:f7/d2ihelUdtc/0B2EvGTA==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:SBK+AvMlme6dpA==,iv:bIXSYe+IDF4HfbEXYw8uPmDcrttP/DOiS8twNajnMVo=,tag:NfZHjitEHUxfeP+N1FL0MQ==,type:str]
    #ENC[AES256_GCM,data:vro9njE=,iv:15HjdsEceaPJ3/7LFBy4/EnBpjchzQCpwbPmJb79O5M=,tag:0UmA+oeKwxvaikUhASUptw==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:wLv5dGjPpWfs5Xk0,iv:eu2IM9RXQZIkaxsUx0LSaUCHTgbZf8kKIZrRhmlL3TE=,tag:mIVS3ZG3FDDh5hBUkROU1w==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:IQHk7O+h9uSqhYhFvvk0V6aBlRhtpke+rE7dexX6U+irAtenRNaDetd2/EvhxSHegqj+YfJp,iv:hlfSgnY68uXH2YW+aHjTsc2uRjBfpbXD4uTYlHpHmMY=,tag:Ju5CnCA4gFntkgDYaqK87g==,type:str]
    #ENC[AES256_GCM,data:He/8MuZvo75rPV8=,iv:oIIlGhLrMxnFOOjtkqJ1Wo+00uUlrKofgEasdM5oZZw=,tag:IpdpRF++Xw8eDzU5O/Jenw==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:iYMenw7TdFKnjjnt,iv:Vi4Mjym2YL6KqH6Ie4TvvbfYhZFmJSaA3AnAsVEcFMc=,tag:5GmOgMNeYGSUezbk2F7Qpg==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:Oi1KHvrpXcZa7i5weEBZlIi6jQ==,iv:DAxxowYyWOyyl3P8JYR/v3FMlRw0PD3dGaawxk+mLH4=,tag:V2rPBx11nFK2FZFMTTlMGQ==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:w42CFa3SDo4ljv/muGmikg==,iv:pE1YkGNSCZWCdJTsvrhBuTOYttCkz2mYv2CY+qixZi0=,tag:eP4tqhgnTebx5GIqw+p9rA==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:25pQyTm3/6VTHdDAxYbQXeir6vqCMbuPBftSnY2xx+JW,iv:ua8JO6Fo9LwnGmVnwR1cnLGyTg2UI3UNZGdlYydNTTE=,tag:XaIDNyZUTM7u6IyGPdBGiA==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:5AUpa8LnMk7COBGCHRzDFmP0tpXCosCbS7jv3lUPlLJU,iv:3m7faY14jUcmb2sPvwKqOwVIL1cIxl93ygft8F7us9Q=,tag:q1EyIl2WVrsZFurHWqL17w==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:Hebt/JadKCfCsHlDq3Q8EkpmCcXSYTUykNcyOu5bZd4=,iv:5z3NfgIfrUf23YgwQ0GYyuurK+qigey5+X36wFD40cU=,tag:yiZhv5ytMZWuTbvqp8buLg==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:wfkrdi/8hURKS0zEM/XgbNVGnQOkWA==,iv:yR0/Bjx8eWSw3/1j+s3P0u+3VCJPT5McVB1eUXSIuTg=,tag:AKiIl3LAxfDmTE3AOPcSZA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T1AvUURQM0haL2hEWW9z
            am9uMlJNR2VyUVVrS0JrME5XWjFOd1g3UnlJClNnU0xWWGpNU3htS0Qra0k3NEY0
            RlIxTlpnK0RzVm1DMDhvTDhFeGhWZFkKLS0tIFpWcWxiSzhnUmZTNjdSOWpOWWhi
            STVMTHFXVlFVNnFhZFdleURvUGRXNDAKze0JRBlKiyvrYTrhYo44yO+Y+MekhPnd
            ALeofCcEBN81UfSw1Cb+qdvfWPeJZFV2oNqZ4UlqYQ24Rv3dAVRtyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T15:06:50Z"
    mac: ENC[AES256_GCM,data:jZLDxMnM1iO2DqSz7XYyOp1I1eHsjygx4KjKP/mI6mzYdc6vcIKN8yZg4IKQzAUVzzZIWSX7ShHrr/bUzY6II0rHC2Yyeb1GyYZyLaEnAtp9c64AXKnEq4LFkhWXE9uzWMMvTBLIfng0Q83Tdqu/ThXu3kvqSE4orupqhiHg364=,iv:UNMRDD0rDV1U3SxzbMG920gRfCBrqNdEtgAmR982ooo=,tag:mf8AD6vqsKOM4D58MGIa3A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
