apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:yX6f65F/OZY+R/FGL4Ju0yxZhFAVEWK8kMoljGFj7gARgDAORxSmho1FZNerM+HnOf0ng3uSbjCuBJa/GUkFqCg=,iv:SCtNju0EDFeMbFHLwwJgPH617hDR0qPoNfxgk2r1VyU=,tag:NWxlTyX/7rNbWENctszwew==,type:comment]
    #ENC[AES256_GCM,data:dU6ImijDgiQyGblnNQmU48tCHLXu5O1ewViHvKYfdta8M4PyHpwe81l4UPw=,iv:xthXpITA9zEHHl6TiYhAkvH14HkSNkGi2nDu9+Tyyb0=,tag:trIaWQS7yJP8/rU0gM77tA==,type:comment]
    VIP: ENC[AES256_GCM,data:YwCx8JX/fp5QnOr8,iv:Gjte74JEKcLXRGP6dEt9R4lnx6s6W8rqQwv6wi4+Epg=,tag:GqmcjL1zCwSfskfpTWAHOQ==,type:str]
    #ENC[AES256_GCM,data:68PdzVinrFYjszBHSYOFJ8gUAbe8uBMNstM=,iv:BPjrRZn6DOiB6dan12IV53KrjNLzkdNyUhVQGNsSdSk=,tag:kw9AOnMOP9xao1fJ5iW5wg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ZJ3CFJo4DvtqctHa,iv:Lpxvv7xnZ+OKBQwLbO17/xjr+0G7I5RACiXAibhD88Y=,tag:Ym82r9pt4H5mrTdAD8r3iw==,type:str]
    #ENC[AES256_GCM,data:puXoCbYCnI9oBCq3LZ6kyEZ8qoI3V7t/dCgtM+ZS+laMvA==,iv:naZZkLDxJWMWYpwNy0YqyMiOZ31pYVBn4ofR/UGvvbk=,tag:yh9NRcVFcx20avys11JLog==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:a2PbvSMlIAasvDM=,iv:fN3DaAW0Y9ob5LSYS8LRmSv3DCuTXZs1it3hdZa9Kbs=,tag:L03hf/P7+4mmA0UAqChv4Q==,type:str]
    #ENC[AES256_GCM,data:p2cJWBR+8O8U7JARXG0DEZkk1sgZBsfTfv5DrTIm21fr/EEWsVIsm/uE2EynkbQ=,iv:PEi6hvke/J7TOzsi/En+vKDRNrBob3WCp1GiiO9ktPc=,tag:EtBoYzwiGrzoHj6ndeh5Vw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:foru/Xn6zhLnOezVvskZb4fm9MdgRoj+YA==,iv:zrG8QVOFbcl0GwLs5Cmmc6dbT5UZ9soSWpgo4CHFNEk=,tag:HIvdDONNuoaa4+tpJ7WMBg==,type:str]
    #ENC[AES256_GCM,data:AS4P2hJFlgik+73sY2Gd6bQm/5EfY1KS2eCR2OupnmtGeO2wsB3fEYSpnLb60aOxydh1Cna3JARHrHuke/t7ZVTQiQd8jz2HZqO9+WTZEgg=,iv:HLRZJ4IQcdoNXRqFopRUvAhmul3g4u5KDKsxuN22/00=,tag:gw23PIJw3i3FvlceTDVjwQ==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:J0M3wptuOGDPNcXn,iv:J07Kqh5x/4cAInlmXUmoMpHtNP6LFV7kUEfXMKFJEUg=,tag:laPshjDHwmUt82PkxbamJw==,type:str]
    #ENC[AES256_GCM,data:hrnxEaFYqIuJHVN3yWzNvlDqOhSxmN498RFsBKvCvHV8zc8tbZytYMGfJnoN9oI4TP13fXZpqxFb2x9NJiJpimckKYk=,iv:Tke0i/3nB1NsqMeVGbd/0PlmxvM8e3Nk0AXlIhcrUQc=,tag:WFqzju75Ut7zexWgtToBAg==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:QoGADRy5SviQYzdQ,iv:KVI72l+FSlnoALNB6MsVrsdsRuFgfqEZik/XMflP1oc=,tag:RHc4+pyYXhIv1yZ8HEelDw==,type:str]
    #ENC[AES256_GCM,data:jUCEnhzcpdWXuosqJO8rCs6615ckcm2kRaNcUc8D6viuSqgLpzLUcJ2k/F3zJndibyO3LBct8O8=,iv:cPWsjAwTX5FVi3jGcI0iLod3dEOyD5OYoFv4ozUoWJI=,tag:Hk15zVEjDj0zDCe18JBEgA==,type:comment]
    #ENC[AES256_GCM,data:vPA2GnAfWtPEtUSwyVWTOjW094ANIDxeFQ==,iv:z3wG1hvsPvQX2GleRTAUO/Qn0oBgJZiMlaAV9VxR9b4=,tag:tBARvnAJLKCWISemjx4B0w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:g7vCFUDHUTAm9dEpBCasP1slXsYvM7qRxmmXdwaCxzNUlGJ9+0Yi3XM=,iv:emakDJr+Cb+IdmEoSZ2o/YiooDQo9NmbXtXOgBWYwTU=,tag:Bjh8BluBFirkifEf7ODfJw==,type:str]
    #ENC[AES256_GCM,data:tHmMS+ryWVyNBttGjA==,iv:wul6CMGX8bHQzfoNOIO0/2EWFpTPVmOzCLSy2/HhORk=,tag:P5VwsW9rmVaHZiaFUMSn4g==,type:comment]
    PODNET: ENC[AES256_GCM,data:AD3EKjzC26X5btb5xQ==,iv:cmtvUbf6inoq1t7IZIYbvn9W2JhOE1knWz5ZfMDZMz4=,tag:zsquybYaDhvcLzUiNrYrXw==,type:str]
    SVCNET: ENC[AES256_GCM,data:MTzzxEaBZMWstBg4vg==,iv:0b4J5Jj8Wz3QhqYLaA/syDXQ2ROIc3XzM2L8VTfPAzQ=,tag:0xNc6cnEiMv2z948VKhSSg==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:KCX0Tg==,iv:R36Vzti/TCqSnkbGh9I2FYlss5JjERtn/yKHHg+eavg=,tag:DaMxbIvuEiLw/Cz8fJrQdA==,type:str]
    #ENC[AES256_GCM,data:ZzDXGzOFy0E=,iv:a6Psq1qZF7isqJ7E9+uccbedoVUMs12qFT4RFKB42Hg=,tag:P6PG7BuTEcO1EePeVMbNpQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:iWaGXhvsDJt4bCNA,iv:8bH4WpMGWdP84rrMmglSFdmsBGeM+tncnhmTf8SZFZM=,tag:i5r7AHhGqI5rUztZOGUe8g==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:I2Ja7YzOkVnnH3ht,iv:p9qW17LYGYP+mVF3MZvmy+GjcPAkoMDSSGFNgtv7ROo=,tag:UPcirlvPtIyMEOy8H4SbRg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:r6whmkwjKtilCpc=,iv:yjCZwa736mFh+0OyrCHz0oW7c9yBDVtXZwQEeM8tq7k=,tag:vYNausDHSKDPeZC8/SYIYg==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:/aE23JMRbfCsEA==,iv:MLabKSw+bCBQVMTBk2hDvbP+BUkf/CTeaZeGlJV+rBU=,tag:zf4Ukk5wuS5KeLYoFjLH7A==,type:str]
    #ENC[AES256_GCM,data:FdeF1jE=,iv:ANkfMRHeTce6bHmCPsxXPTrDvJ4tFLBC6gnDD4q70tk=,tag:eigI+PE/ZImZmxkPdjeSMg==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:qZIXkAEOChzy1drE,iv:YbB1Ci0EOyYI82QJyfheNoxbzIEfaTJe6f1O7dbgZRE=,tag:r1G9ny2QXCUxJL7Ct4VnCw==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:eBnSFzYe0gt3pLAG1J4g2+5lv9GRllDiV4MuKSVRZD9rQSocZ4g8Mxa1ZUFbfX2zOQRFuo/j,iv:GTdIGjRCn5abNi5J9/uylTUlJiBLa9BmKKVIUGTJT20=,tag:LgPOAU6jB5xAJrSEcn23PQ==,type:str]
    #ENC[AES256_GCM,data:fzbKzb/ikdBGD40=,iv:gheD+JD2dFXiOYRW3LDHbt7Oe+Pvt1ltkGiD4wHu4JY=,tag:dG7/yTUajwUu+xam1Cao/Q==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:J7R8dhSAs4nvT2wG,iv:P/tfN3AnNy7/fGJc0fb5Rj7D24NHKJhquPrVg8GJSKY=,tag:Se9pzvETynLm07YsWRueDg==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:HiGypXHHcERVGLf9dZldUS3DQA==,iv:O8AJBDx/GbqQglYk8j7aGDtyIAV+zJmo7NMc23VDMDQ=,tag:9MtZCXV4tKsl/59GMWKTNA==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:UHKipUb3dXry0ASyGjEAyg==,iv:kR6Ql+hsazHb3j6klPHjOugfq8xBrgy5At3q6DQowCw=,tag:p+yMD9dXmJixtKFUOKbHOw==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:kJdD+it/4ORmztla8+RbpqglrvCVtbVOjyAQgfiekNpp,iv:ECSsFyn5hdtXoI3YzbogqwepZcYGnYWJxWWH944yoS8=,tag:ael3nQU9mod5ORDHRejaOA==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:3gDTdUCHYbMzQwr1D7L0G7YKeQqg+9eK9OgRgY5Ks4DP,iv:741rxclkwWGNO139ZjR9/ZwYsd3KNNHib9HIEzd8/B8=,tag:qJsRt5zesA9HJY+zC9JI0w==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:kuARYKyiPXDwShcaAfEByu7YPp5xI4SIj2TorUDXp/k=,iv:2nHr0mhsHNOR7D+K4dt4Yex92XFo8nFZ3PSGpQvUZ8k=,tag:gSPRZUJGte/CSa0283/ZIA==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:9ry30ZUbPLBCjtMFtSB293qVI/5rRg==,iv:BqI/i3adJjX70jjy79Zi6/uInxS7vNzafGK04RCqoRk=,tag:pGJmNou/CX6clSHfI7ZMOA==,type:str]
    #ENC[AES256_GCM,data:OJPaPA==,iv:pNvnxKGnvp2V1wIOEcBtjN/5mBxrlMiHKD5jxWxT+Zk=,tag:A+wlut5FqmfQXSF9npbTQw==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:koJt45Pt,iv:KFP7oN2Ov6TmD7y5A9UDgPmVIbNOnCaEtK0AWATWVec=,tag:p3onSzVfmDWjkDP4MISxIw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tp3sK2MH6yGyqaLBSVJJHxG+pMb8qiYY/NmPAAzZpMU5WhAms3NfIsJ1ND8=,iv:RrZ02/4qFrpSfJ98KAFHEDjacftuRQVAu31krUrjNSQ=,tag:FeBIcWiEVTW7C7Vs9rw1XQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:ZrFvlS4D2V7iGpkPP8ox1/ql4Ycca2PcMX/J+QRAAk53eA/eXk0ijX/vfFQ=,iv:idz0mSH0doLQi70czZ244AkkDeRgkbwfLyZuXukdzyI=,tag:hWlHCNJ0Dn9zK6mYdMcLVw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:q4EWpBkZAHEr9LdhUIIAlLU=,iv:ejunhN5/rGkTN/AZborLb8LZ81MN5WMYx5DaRTZXaJc=,tag:7t7GSUuCNPY04KF2x4cdPA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:rl7JMYg=,iv:fM/2Nx0tZxB2KxFDfSSIgQz3vnwFWlYUdU3nQ1zPOUg=,tag:y8WJvQF9Ns7JVXzZi72Dng==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:2qAxM1TrxRzYmrQhw6F1cmMn4zI9ff2a0Ya8vC4kYFca,iv:4VnLgBSA5fGQbxQhjwqQi2+rlMud7igYY0HbQstve4A=,tag:+UrWl361ABpv8GVeqjRK4g==,type:str]
    #ENC[AES256_GCM,data:sqSD,iv:ESddANbbzhYXt3RpRhyYKd8luwMjiDiiG6XPx0Zlxa4=,tag:2TiOQKxwh9em2AfaA3/48g==,type:comment]
    S3ID: ENC[AES256_GCM,data:dRBby0jR3kenK7dzMr1INGQ5Kjg=,iv:zUBLc1dU7xlCpf3410ni8Y1a9TsmOONChLqJqTp3hbQ=,tag:HRJ73CwU519IP/1JoA2G2Q==,type:str]
    S3KEY: ENC[AES256_GCM,data:QNnHHxIQXqop3OenbVS2NtU6UVM/z4uQ2zjniIvgrjIiyiRdZM4rkA==,iv:kFQxNaGM4ipGGXiq7sWD+CmGk1zHYTNhJMt8O+w2QiA=,tag:bJI84q58qWSRB9W1lOcwlw==,type:str]
    S3URL: ENC[AES256_GCM,data:WLoX6NchGDRGf6knif4UdCz7615lvG0iwFTPKNFPY5p10Ypp6mJSTOFJ,iv:D/J7ROHMumABbyXVSR7ImUfuBDC/AZyMuCR5dLlwsCk=,tag:m7Z4jePE1JNWKX0Y5qy1vA==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:JY/3DqtW,iv:NGcixNvPxcnaOAA+3iIKfGvogIFTKT/pR61DCshj+sg=,tag:4rQzqVa9OASd09rUHIehfA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQXVvcFV6Umw2eUJIUnBM
            KzhNYlo2bisyMkkwV1BqYWxGZjY4WUlqMVQ4Ck1Jb2NRRVZBSDBUaDFOdEpxMDBR
            VUFMOU5LVjdGRE5BREJSVFArOGFCUEUKLS0tIFM1aWJnSlB0Wk41M1luQTFUWUdD
            K3JCMXQxSi84MlltcUduNUVhZ214ZGcKJPuVaUA7kCHlnfdgs682ANJ4tian4nOv
            Yl9wL0+kCiIA0YgSHeAXAmXCJcTgcBO0KRKsqgh+6qI1AdWqGWblZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T19:12:46Z"
    mac: ENC[AES256_GCM,data:Vh4yCI7rMN3fs2SgBnbEokKDXtb/fad3HbaqEF/y5bGmcq95CLogstVsqdgTcr0m386ch3AyJhmGmjOSh50P9HmSkWUlwE/C+xkaK6cFs8mb6YBQa6HFMmvJeBk5zcwm556FLyOYGZbjUfiNMzjOpigdvRP8bpmOQ6heDSgjXWI=,iv:LAq0YPSFS0QFqrQBRAPKU/ywXMDFgZft3fPZLbVoRe0=,tag:+V9VWgy7mHAj5GD0BpqizQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
