apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:VstXTEcfl2gugIpsg4lAxTsy4sNRcjMdXBwFcCCRcbNHuX3ngr8Y+bR/CkaD9F9qHi1gwzi7pA8g/rkvH+7w/m0=,iv:fJW3lr7U5JobzrcioFbsVpz7wrfzWVb9tFvtcJw/slQ=,tag:td8BSkpLJpBRI0etJN0RJQ==,type:comment]
    #ENC[AES256_GCM,data:ecx+qF3L05F3M3vAkVptBaJPRY66jiGneiHnfhbNuAydCO0Ls4QmVGFQnXE=,iv:9P1kylRwSKoD3IlKOitzXhz2T8WUcNHu47djyKLan3A=,tag:89FlGWZ6Iu/pCwE9frsh1g==,type:comment]
    VIP: ENC[AES256_GCM,data:5Nsb0pT/HL1VvYQj,iv:uJhix/rpgvCUDYMQ6iiaqxtn89VuzvyyehKWA89dzCI=,tag:lqpBPM4DpFX0Wn3S1ZB0Ww==,type:str]
    #ENC[AES256_GCM,data:QbJyTg+MQaJI7lW7DUJ/fUlttiSQ/IeT/JU=,iv:wqMfeKsPwYXze+l1Xo16+9TBoGMEWT9UDhvgigmfflM=,tag:dMzgIYDT3ojGtlIWbtifrg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:AU64M/ljwRO8VHrE,iv:J8avjnUOGL+QYOdPqjMdcpQXZG5WrX76wgwJCcuYA3g=,tag:UK26+Ct3I0szumPldNnD8w==,type:str]
    #ENC[AES256_GCM,data:aM4p7UWf6dS6oypIm5y7uAY7ZLSp71VJd0YYnK33dnbWsQ==,iv:TaZp5JOgYvvl4oBDpVtHTIBnRw42NVIS1DD1m6DywIs=,tag:tIh7xALeSHowkinocpBDig==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:UX3poneoxxWN5gM=,iv:AvEw//5d2pS10OPH+owGiKIYP/e810ICSst1nzS5XLM=,tag:LSWH58RKxrvatjllpcNh8w==,type:str]
    #ENC[AES256_GCM,data:aqI27pO1vzQcfv1Xb82in+X+PtP9+kkPVrcdfEIOi0RK3MxDZ+/vQLrxow7L+gs=,iv:h/kxsRlfWoBOOVtlWh+EzIe1RTmVvEOPxvQpbygvElU=,tag:sEURp5HswRRXFNWqZkhEVA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:MVA1mqIPHrAf2bsp6tyGaT5vysuWSbzcKg==,iv:edNcGkisjZmJ7zXMgXjRcVMtR/OQAOccQ+WI5g1j1i8=,tag:bnV4M7Tde1vtR5DTUZVSow==,type:str]
    #ENC[AES256_GCM,data:txnfY/YVZFO89vwnWU6lfgU9hRAx0nyCbzZAmp/tupWAUUlpOnaXmEraNHWocRdwtiyrH9v0blnXnk8ck+ItHU/NViS4FHINNffIPHhSink=,iv:sCksX7WzuNDy+ZjoSlfYJhkMBoHWcTVSAsp9vAW+c+s=,tag:JP5LCNj1VB3TF3CY7cRq5w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:yYTMg0gYMX2DU/c0,iv:4BfxflPKb2UaBMjua5jH0pI38VRJf2ODGAhq2XkkAH4=,tag:9pQIO/p0tQzfb3sfncxcfw==,type:str]
    #ENC[AES256_GCM,data:rIA+x94ar8o6PEu26arYeeazQ6xqK3UAVs1amKsegwyim9Z+KJsi96YVhR4TixZskvGrHQejdqRdwCV8WZTDYRVUKJw=,iv:2/fPMbYU4PNTtLFn8xlfjJmX1X8W1nmRbdhJF94UegE=,tag:htkw9uHLFH+vgqGpWOsSDw==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:buqBVJ1Vhex2mWID,iv:2BfsawZsY7qBl/AEtxTo8R2PHbT1f0jcZPU1/zA7dik=,tag:VH4zR4UgW7RF9bR55TeXYw==,type:str]
    #ENC[AES256_GCM,data:lfQUTCfQdsJNftApyczSiyCsGZ+AEpzxfa6f1/mTttFXBhx6TU9ky0LACIcX2rQ4kczCPtp9coQ=,iv:VWW3BEOx+8HMtO7IlvTQPv11+T1BBdbf0DdEbos20Og=,tag:aE2TdlVQ1LhxIH6adu1q3Q==,type:comment]
    #ENC[AES256_GCM,data:I1rJNFhXMlEXrU97mSZMoGqwfmuJyKgkzw==,iv:yaQL+WP46AbkUbRqB4LsBQzJNaYLu73B/+Nmo6z08/E=,tag:sDMpUL7xeVkPaYczukCvHg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:fNQLz23M25ZhInzVKVbafl292zvWlZJPFYBJYh+9nYhx4nSeoYuEDrI=,iv:BHCLi7LhGTun6K+KKe0pwXPjiQs5TsCCbatFEPIgRF0=,tag:ctkS6lrxh7DAK6cIgwJqiA==,type:str]
    #ENC[AES256_GCM,data:NYE/y26HW8IjlmD92A==,iv:nEJ694S0PJKLxQp0lalc4OrmmbslDhicEfciDkgfdbk=,tag:ZijOdggpkoRq80IwuQN55A==,type:comment]
    PODNET: ENC[AES256_GCM,data:0vrtrzOkSRSZdwSk9A==,iv:r9ic/fl+KBdOJlNMgnMw4ZQaUDk4+kPjznPwM51nyqk=,tag:pSfAZjMQwn9mgsQOiia7SQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:cXQDpN0T8PMYzlZWBQ==,iv:wizNf4RlQHZk1Df8HhXOzUcCkcLgZGsksR3wEY3Zq5o=,tag:KDQNQqSVj8xTM9GdGQFxuQ==,type:str]
    #ENC[AES256_GCM,data:zAwoPVsRkP4=,iv:2mS5k33uVyGYx12RlK/uZWY66p7N4acNm3olkYZP/7Y=,tag:8cA6dMwXhXUR99ePKAHzMw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:qzwMkR+3PyIsNFWj,iv:3mGmQZ+s99sXlmq0u5clpAe7BzUk5/5d9egdbSW0ls4=,tag:qmB4jNruk7sOLXAaxGGhWQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:DO3LvWHEm2S66LSx,iv:sQ39vaERO5SQoiQYR3yiTC0njnAwVjJpUW4f6QcpYek=,tag:3VijpxuFzDoZePaf0rhENg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:R12wqdWKaN5dLqM=,iv:DEHYBU3gWfpoD1rYYrZkxI+rwJhKeBjHBZFOEM1cQRk=,tag:n2ZN5ck3kOL96BRIJ3NgQA==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:J2pJEmL+ZaEY/w==,iv:7NQIVZ0Q1imnkgctzGF9KwpOn30VeVvfe31pidtlXTM=,tag:TL0n/tvXx6mygwBPtcYm0A==,type:str]
    #ENC[AES256_GCM,data:M9u6sOQ=,iv:YP+idwDoob3aQDPK7a/JXr6aknrUv3YPlv8DO7OLAKE=,tag:5FRlab3fVYqe/DhM3uC+Kg==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:Lns5vNWRMwuHYIbo,iv:r7MSYYn2oAW0eNwRjyyoLFwjQO8phYL1k5IySVbYaRE=,tag:sr17ee14x+r0bP863HhCpg==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:92VAMRBHPbOcXg1aVd6QIcK4q68tc+gigox3m+da7Xso6fqSPoJFrMYJ0dkPyMt282o5ygtg,iv:IXaOW99HwzaBcb0PnwItreQWW9u5chdnbWmqn2025Qc=,tag:eCYn5E5ThEDC+FomiGHdFg==,type:str]
    #ENC[AES256_GCM,data:t24Wca24aAIANRs=,iv:Rw2mpULhSgWk3BvrwEjnQnneuurXpgf1isFVcGD8l1w=,tag:OGZ4TzmN+n7d6FYZ5zi6ew==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:quDU0Htr+IzU636M,iv:FRopHMBiCApGrLp387hU/DZFmcOzUMGP917p9cDyZLY=,tag:PlMTXe/o21nEHLYH1ynEIA==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:vEGg2TWoufBm2yCfatNUZVfuvA==,iv:YjAUcLtMtgc90a7r6q4Ll6OxbwNlypxeXkTaXYaKJgw=,tag:fS7WoqN2SzqOQPbyQFsHoQ==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:IzxCzoRz4dtbeCausUQ8uQ==,iv:0ICv6RBP7V0Co6g2ZmUyv3kqS+EiC/ZAyp+0JbtEXS4=,tag:9Xb+FyIK0g3+hVuHrkbuMQ==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:Y8mVex0kydfq7SS3HJDTtO3Z36+xe3sD0qRPaiFIpUFO,iv:BAhUDdcfjDKanttboRf2dw1a74YjzOjPKNARNVf9GQU=,tag:QFV5elSCWB6CSBGKpldTZg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:CNdw49y6PhZgGnU643oLQgUmcAyK+TBgot7cDAmTqRCi,iv:BNXAuzwm98BLEXsupZ97B6T4mxS51HWCme1ytjzpcnY=,tag:pgTH7p1MilTmSYOXNyGDqg==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:Y0SRRPB52FwA+C9XeevhnEaxxV7S/oGoVTKpOQPLa4k=,iv:hH7n3x8ozyXOTALgbLmq2dlJcxQjWnRrda2R9mII5Do=,tag:6XJU4GHuB223R4sH4hpHig==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:XZTR71QeHmayQKMvwpbjZPrNaa23Eg==,iv:01UYe1eBH0ATGwj8cQtd/NLoVZQigwSYMmCxwIY6RqY=,tag:q4jgZBx97AA/M5XTNDIIrA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcWRxeDFUdy9QTS84OWl3
            MGdJMk5YVS9PL0RLNU1udEsxYUhLUzZKb3pnCmFmQzVJbUtRak1ScjZkc0ZNTjFK
            UjFtdzVoMFd5TkE2RnN5UC9KNmFoc2sKLS0tIGpWc0hneTNJZFh1QU9iMFpjVW1w
            enpNSXB3dmNZWWlMaGlRUHdQSnQ1REkKnTB+Qm3ZWiQz7jxiNPqpFTUG5XLvvja8
            XFdwaXrdToSry7wIqijNRXH6U6hsrSZJcsmz6nHjuahhPAcJIj/Nog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T23:13:12Z"
    mac: ENC[AES256_GCM,data:ubHdHvdJ+cOPu1b2gZmo9xZa3xglWB14/sKzzw2+WHBxF9z0C26gDALG7vPGadodXmhjhWTb2/MT3iqiSO3IiOmQu4neDtld7VA2/1frZo19HlAqK1AUwrPbnp1UNGJKOYLH+WtQBtzk2LwszeVsbC9ZABGbE6Vhgjgis2cP2sg=,iv:KGBMhzKVrVrBt9HIOKlziAgxR0zMWWxA7FkbpA4XuOM=,tag:mcMHojKu44GYk6BjLuiB1g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
