apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:jJZJpEnLTua88SAR8/hqeA+L61+VlCM0osjwX06/zvpo7VVF60zSWB41enFtwvfib9ewCZjjAddpA8PnsZyWUhk=,iv:M/UpfgAFbR5jduj14+sWBm7jzhwCKfpGtqvayKswBVk=,tag:6zuwCqiFrEiEiYO3ie83FQ==,type:comment]
    #ENC[AES256_GCM,data:2l5OcQcj8y5vNEx5JpKIQ96r2tmi7FsOmycxrj5yX6vXkfV0h49/4plRhVs=,iv:99Bn4dnGmYyvycsuysXwwP8W5OU/BlwPEUglw8Wo3Uc=,tag:4OleGOrw0vwgdswtlebrzA==,type:comment]
    VIP: ENC[AES256_GCM,data:yhOS2AVH+5NQDlNz,iv:T7PgoBKsimsJKITumpFEscbDgpuH2b4heu4iFYXOIIk=,tag:aYtDgSgHSxBO/CYHTDtVVQ==,type:str]
    #ENC[AES256_GCM,data:pH7E+FS+Gp2Zt+k/RONilQ4HL+8fSF2JPi4=,iv:MMbBoNNHRZzeJMt9xda8KmSOTFViMSio4PA36ERpF8o=,tag:oYYLlZlaRIggcM4GVfoI3g==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:JZDKtHN+NYzVapAv,iv:7GCjfQV+CphWy+ATz5AVvgtoEw4CNiKCjN2youyH+l0=,tag:NyoFaeAylMB1tHUU/8NpOA==,type:str]
    #ENC[AES256_GCM,data:VgapR/F5zalYPSWYBZ+8SL88y/k0uh/9CzeffH+gmuUQnA==,iv:n7pvPSlp5sW5vON5zGfHYlZiqEh7+IStdBJBGnKdO74=,tag:bHt6Qi6sl3Cn2Xk8EHKnIw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:PA81wGpO8sUbDb8=,iv:hjgTl1XQFSuwjmEoX+AKNwPSUN/FRv2BtMgDLt1yj9U=,tag:Dh1Fscdw/qowVD+9m+mzxw==,type:str]
    #ENC[AES256_GCM,data:KrvMlGXGsTiQgkevQnevtgrSRq1SxS+iXp08OYqYMBgU4E5P9jLVSwUvby95lzs=,iv:WBcCYxB+G+kXotths/MXRL3sAWpA9VfbKDv6VUB9Vjw=,tag:uxz6upxd1Z4eL5xeYmVRYQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:hhdX6+FRQ+PYBDCrtdiEggnySvnTFvyHgw==,iv:Iqe1MKEoUCuEUJGV3OJAFSTDuRgfewpgRXiSznH7YjU=,tag:g2aybGGNknt5wRQLGAW+bQ==,type:str]
    #ENC[AES256_GCM,data:qitpiMFZKCLZ8gjnuiPAoVDob14GnziKu5iFCXP2WgqNaFB86zwDw5NnWad0oNNuXIBQkElskQFJzHNTtnCrfoLpzXnyNpEHrGtygSdSero=,iv:dXAiZiC21dpJF8G+IpwfNgAO/2zPLDY/0w6Z6Fj2Ovg=,tag:1aB8q0/eMmHBKLyHomqZpA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:ruepbF+FhaVm53o0,iv:ZfNBMc/2wUjTDoGNMWFnh/ARQLBX/2a162ptKelW0YI=,tag:+6vX5BM2/9nF7aJ3zhOcyg==,type:str]
    #ENC[AES256_GCM,data:cD7FbQPgA40Fflcj6tV++tErFThNp4c9RiUuMH563y96nG56XFyosb4DbzIRO8jpnqU77uOXqFAj42QqIPPLIXpyjdE=,iv:OVMkmJnGyla6YtJLPr5hk4NmCuvk+EBg76YkSJ+vjEA=,tag:EANhE1ZW8xq2XFrivmHWyg==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:xysWTGoKZ6HIstwa,iv:SolYc2qmvvqMaZAg7qliUyA11YFIEf9mxckPWr42YZA=,tag:WhSOBktPqZfns19Kcygwzg==,type:str]
    #ENC[AES256_GCM,data:Wtj9xMcA9oZz1BeYDeQx6j6xA9kSV0q4x5LRC39MsyewaekB7jNf52cAbDEWEHd9a6yYIaHkT74=,iv:KDvQIqBbiUVeUh0tM+UpOBm/xPoV1JQjwMiBMPiDRXk=,tag:qJbV4xk7cln0PZpX/G547g==,type:comment]
    #ENC[AES256_GCM,data:rTajZMOlihaKZR9OXWSRaHDVJQ3aoqxRmg==,iv:yUOv8kSQXltRoyYmDtg7kyAIE+HoVIC6nNuOf/btqXs=,tag:4LIUh0lebFtqw8t2GxRC1Q==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nOH5tstT92PYRpbdnmLT2NGhyQ5cFXimzRMPBw2gEXLDHn7pELtk7mc=,iv:rkTn+oobMpHwObSCbBdjkP6KLRnM+IsyesD3vmKeO4U=,tag:jSYwZZfk49ZDAk6emdzz6A==,type:str]
    #ENC[AES256_GCM,data:Kygnm4tLcWzhPAaJuw==,iv:VzGFTwXKqF+PufbNG3r84xZ8BBhGUgQK10bsFVVf/mk=,tag:6UgItbdrGIT72F+nadN22g==,type:comment]
    PODNET: ENC[AES256_GCM,data:UMWn2OAQx9U93kbMJg==,iv:EvEBLizYMbLpaWWl805d6wFjNaf9Q0CcTTuLtwTfcLo=,tag:/lQEBoT8oeaupaAucTkbBA==,type:str]
    SVCNET: ENC[AES256_GCM,data:MinZLy9a6yAQmx1BsQ==,iv:ZUuz0OE0Tc0/aVyYUljDlTSQhIv8zWLI92+ZMwlQwyI=,tag:kgsaZ+Jz6Omkky4WxjhyZw==,type:str]
    #ENC[AES256_GCM,data:iDHTv28T8kw=,iv:540XzbmjJSVQueU3yWF1whx57E9PjFxgbwV+yfZLT10=,tag:iPnUPivj8etoW7K4WPTdTg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:5ddScieEbbyUK+Jg,iv:e6vpk73QHD2Pf7ZFh0tU34t9odHfQaDEcZRbHKG+oQE=,tag:3CQDl2AcIfthDH+HimoaqA==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:MpU0dGEMfBff0IRY,iv:q4HaxglKazrTOJn39o6Z0oNUlvoRAU09g9BDckAqcFY=,tag:SqjQb8hGxJLP17WcU5ruLg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:v96jwvaoWae6o8s=,iv:tpaFgKR7Lfd6FO9JKsYzGxSfW6vg3pNS9FjDvgYnvtA=,tag:iKXd97mTpFH1gWEIHr4sQw==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:XT5rs1nfqb5AiQ==,iv:orFemhy1BXuAMTqE/QLlM3BrKJ4H2EgeZWYkGHRPE7c=,tag:8xOaY4vfwVr9dPNCSM67Xw==,type:str]
    #ENC[AES256_GCM,data:KP+Uo6s=,iv:RMr6FquQ19ppiTC+LmFb5q2HJqESogm2jBCQj16bet4=,tag:mw3OGhLDgayRQHlrW9st9g==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:ly/+s5jdzljw8CfU,iv:oLMdz5sFi/kIvzP3a5WveUcAF5nDZb68426UMkN62Dk=,tag:puUi6ejEQmQnCvxZzXnrAg==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:oUtBI67SUCAnsy8YHYxoAr4qB4mR9HHhtGwAx78mzExaC9UTgEZ5/sbWr8ZkRpDUoWwss5RL,iv:liC0UjsdMoBsumQRrdpIxVJUcxijEXiac5usM842/Go=,tag:fXnGH0VarMDjCeqam2lQDQ==,type:str]
    #ENC[AES256_GCM,data:/cBy5so+wmSwRS8=,iv:YnTP7ZRkfQinEk2bnoIC1WvVUh3ht4q9ufl6txqO9cA=,tag:VBPM2xbSq5a4cFf3UDW06Q==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:dkSlSu0qwgTLNqiQ,iv:Ovb4xrCO7y0NQ3w0lDPxHSpSefR94fXR2P5NFLEG/rU=,tag:3U2rzw5JuxuGush1Tih6IQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:wGmqOleqCAtBfTnsOg2ejkOVxg==,iv:6oIFAUZUGqhaNM+Ql1ai8IOMnyMQG4bGzUc01pau9SM=,tag:Xvo5/c9rTqOoN6CfBcU+HA==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:7kZXvwDfKamhQlMFLjoKEw==,iv:MjpFZsmSd7OyMeiarpkY8JOCTJHXdhTzqYgIeXEfd24=,tag:i3bhXU/6OGA2Lz3qR+bfcA==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:BXa/eHNjWUi8+1QCAkYf8ubVXNyWGmKQGR4zIQ9PrHI8,iv:cWTXznCkLFmSlF+tq8y9Q5MTdVE6bM9Td/lpC46FToA=,tag:96J57ZK5Ns20uaT4oDxFqg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:tALF/6pGe5kJw1bS/+rTaIDRYEDC0uENVMbcTkbTiHfz,iv:4MG0jmG9JLdNSOzrqkIZswFXP0MQYHcf3F20myHqqZM=,tag:5VT4oYHYzCgKPmuelmTJhA==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:YjrLSHNY2dSUH62nk+Kds5ef/08eNP8iYol8v1pe55Y=,iv:TF1raYXRPTA5+YqVhao6t/UlHGMsRvRgnEulDKAlqT0=,tag:zL2mtrzKehAFPUi9mLW2Mg==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:1v1/228u1FpvSB/+cVDzDEsxV/Qd/w==,iv:PXhsyhV9D5qL4NdGXbBnl8gTQq5405pXkZFqHNiAG8M=,tag:fFzGsDPe+VQH2ayCpeY3TA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MDlWaEN2VUtvUk1MSG00
            NTNBUXVWb0NUcmlBSjRBV29aVitueUVySTNFCmtiZ0pOM3VNZ2RCc2E2MUp0R3dB
            bUtZYStUV2t4ekJTdmFySkNteWtuY2MKLS0tIFljL3AweWtLZVFsTFZtNDFRTi9D
            OEkrcHFVcUs4T1QzYVNjL3ZZWi9QUlUKrIXQ8n6+jghNag374mUAg35+YUYJ/Gr1
            rpmPJDDloU2yQPtx9ROv+IA9o6VZfJUbJAmIrJ8hB/3ldoeakmoa8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T19:24:50Z"
    mac: ENC[AES256_GCM,data:yUjQZTTyFzhE/gTP1/FuRjcc/NIZMWyi1PyscF0OtfhqGMgqTKa0hT94ZKXfa9bVdtfiHHkKXSAyda/alP+qGMiZmZsKxY1hu1OKDZRDSqQl09q/6NOoNuO4qx632XC844J2B4L52Ux4suJ0O3WzSCP2H9ReGpR61jER/VBFYiw=,iv:hVMVwTShboFDJJ9yzn3C7nSW0QnYTq93uhNywR2NQ+Q=,tag:iK6yMIhfh0dAhTjOwdDkHA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
