apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:ekP0hcUecQ/T1+Kqy0Hy8cvklPnx+d4NEGGlBDOGS+fTT3NuWNeVi5fU3A7hO6vzk6BAzObf0jtMbkclxNJWLq4=,iv:IvLhHCpI4Po9i7dFbt0TaO5NWEYSI/PYOtiW7ec7GhQ=,tag:GdvK7WpxjhLR//nDGYcp0g==,type:comment]
    #ENC[AES256_GCM,data:D4QTLObd/ch2L8tF+xsRvtdZjMAlZiSbdcbjzjXo6F+/UZV2UTSILYcpBsc=,iv:NziYpNX6fLmwW3sQCcCEWIr6m/KIKzz9oGpfW7TdYuU=,tag:S7E5UBU7PCFyTsZj1G5fhw==,type:comment]
    VIP: ENC[AES256_GCM,data:rI4dbTeLslY+dOPf,iv:4lKhio+h6Fko8WhTOG6gGPrDT1VDFLmEpkiop4oVW8Y=,tag:wAC4aph5LK7hYoBkwlWLCg==,type:str]
    #ENC[AES256_GCM,data:o0E7looenjVVxMzhXC3RK/gx1hFzHsKiNIQ=,iv:eHBlwfv6InWChwjtkuRsYvY68vljPSzDO8QQrHL+fmc=,tag:23K74b/Caby123uSbxzRcg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:A2Z/Ji0Fua1gYjDI,iv:GIB58gOjK1Wql12O3cShCGfhinwJu4HUmBUUGLVRPMI=,tag:FJBCZzA1IwxbzQx1aI+RyQ==,type:str]
    #ENC[AES256_GCM,data:KzxrGkNVsG4J3ThV/6Mmy8pU+qSF1O/3HKYKZimEuAMS2Q==,iv:0WiiTIg2bnreyDYcQPtSRw9DIdfcCeWMXFABBWgfd9k=,tag:KleNbw8tzf+vz8+H5I4EhA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:Jrv67/Tf5HGj8Qk=,iv:0cMeKwhQSRr6dfjgoq6z1kG9SpXJaQxNIfZDc6CqPqQ=,tag:tHhBPKd+okqc2bHYy6/dLQ==,type:str]
    #ENC[AES256_GCM,data:IO3gHSx4L95U4fJQHkfvTxgbUnQ6DEXn1ch64lbonnvD/SIeIWOU65lzILLBjwc=,iv:2jsO/IgJv2utBZ2tQl51B3AOBX1R0gEHaksdE1+9BHg=,tag:mTmuEY3D1fJgKH5/+IizCw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:IXqMG5aDjdipIVb9jei341POjiYhaoVE/g==,iv:sUT/6CH7TXKgLR/Mg6KZv70UDfs7lcXKQVLjioprKuw=,tag:rfmgUnLcsBkaYw5J1AB9iQ==,type:str]
    #ENC[AES256_GCM,data:axhNSu9ozufDU37gBu74TgQkW2sH+OovlNnPiwCi00YL0WjRoc/b+gPyibyKJ4BcXnuzktmhIFalF20pI6UejPNjEh9a1t/uO7Ej4cPztfE=,iv:1OBhT+r9sBqnLRWtCrGdmZsR2cg++IXJ0Fe+nhnYAXg=,tag:QLZ4NHsJLJdPwRI+EwJTXA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:IkOvm1mkCz99sEI2,iv:eVzBBnlrnwt2Dpzw2rwQccsglyTT20EIlQ+bU7UH9Vo=,tag:UxhvNQDEEpae9OB6Ge1CCQ==,type:str]
    #ENC[AES256_GCM,data:GKyPzRW1Xmgbl8g5QYRwdSODTkAJ0LV8EgarCdCsGST/59Ao5NsaRNfPADn1rQU0PY3w0LMkhb2CSOCky706rTxBZLk=,iv:vin/fCuYjFKI0o68ZR06hW0c1pP85Pj2wLSNYRayapA=,tag:hIHtNJ1mY3j+ML/Sp21BrQ==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:MBzYXVEUQW9lhLdH,iv:zEFcPdXMO8gAu2e5z/UJ+PyHNxHBZ0akyGoS2et33ds=,tag:SbTrb17EsiBhxarTyur3gw==,type:str]
    #ENC[AES256_GCM,data:iKhuEgzs2V36SlmWDmso+O8Kw5JplFdBxfYPhKHPCz+MFnCoEIOCATAiJOqeOP4z7Xg+IUJxfcQ=,iv:C3dDPlqwgeII5dQtyus7PXue4HdiaJ/GmFhPxQiFFDI=,tag:ESZsCErQKtSYfmqowhvo8w==,type:comment]
    #ENC[AES256_GCM,data:WWOHMPHfE2Vh2OzcAmXEdtQUm/b8pwzwNQ==,iv:1lSK5NFyru9u5SqhUXCQXNa4BVPEzwEI3ZVygH/MRxc=,tag:dvbzZEzGb4qNtdPBS92wJA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:NJAWR4o0sn9/TzJ11zUs2WPubhSsAHBJgIYLjga+ugPosmTw467IOms=,iv:BrB1kvMTwctG/7OYMeTbnWoGiPQ8WL449ETqvoWSEUY=,tag:ssj3tFGmTZzgHdCIH/bzKA==,type:str]
    #ENC[AES256_GCM,data:jPW+93yJOdOzc4Hrbg==,iv:wbyKgh7ZOM+30gR7wCJLQX0DKQJFDjCoQmOMXEajfrM=,tag:tlAdtC0b9CDEEtXxpwdw8Q==,type:comment]
    PODNET: ENC[AES256_GCM,data:VM+Mf+SQBOT44ZB0Pg==,iv:rrzv4Ep7oVTkHqy7qNLjsNDRzQiRTPvPG2CF7G7x8zE=,tag:7WTxb6zrQ9nq4gnyxrVHtw==,type:str]
    SVCNET: ENC[AES256_GCM,data:abKBA5huAgm0GitTfQ==,iv:QXK0Do+qVLcRBEPsATmXydxnW8rGARvqI8hPLQMUDkE=,tag:7yFhWQuLDs7x+Tjt4gsxkg==,type:str]
    #ENC[AES256_GCM,data:hJJgEp6MX/E=,iv:TU2M8Ln4YgAwOqBCZAuUOIcICB2OdMqj+/7u1V6YG6M=,tag:RWJT4iQMSHqsSWMr0FL1jQ==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:GFP/64imRQGRjq/C,iv:WZCBQzsMC02U9aJRs9e0P8g3BMggSDO667hHMx+OYxs=,tag:RHWtPyrBdJGJhUFKKUgf5A==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:I1DCIubVsdSzAuY7,iv:IGp8OLuKQXi2sxXStk1MMZyL5oXTl7lT4KdfZbFhokI=,tag:45aaQooMC484Bnv+KiUhIg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:wYxnWJOoEYZXBrQ=,iv:nyH1cZVuP3MBVo32A6X2wy2TFSJPSOCC952CStsbbVE=,tag:kEt3IdRk9jlD82VbONfwoQ==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:7vpa9Y/kXlFLcA==,iv:l/26azH/2PESA6cFgjsbpQD3h4Gw5GhuDtoI19aZyDU=,tag:qFFQHCeTMGUS679m5TkVWg==,type:str]
    #ENC[AES256_GCM,data:8aVNnyY=,iv:jLVhHwqfVsfJUIkF6y+enkrSFK+0bvGId3jpWkPwXmU=,tag:SffIU7qbEg+6YiSVI7VgOQ==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:YjwywyfuMH+bvYf7,iv:5ygNFs9iNJwMu/1x79DLYY+ZeIT1VHqt5gGayUOT0xM=,tag:JO3gIkZamwpmtt9+g9Eugw==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:38NmpVWAp6rnfOnTEwEw98gYaYmTAr3NjXdCdMyzRvHR0MFEg9s0g/Ok9cERgIFkkOqhmq+P,iv:QqW1U/kpmgLlMr2qJkfz25KMy2w0tRVAVpeSFSR2TkY=,tag:sTu4wL6nMsgUaQkjY3nnfg==,type:str]
    #ENC[AES256_GCM,data:iwsUwqq/f4C8RaM=,iv:M3iCXVyvTHM1XtyIhWzIw8L9O6vQpcs3Sx+58FyNIEs=,tag:Z4X9JCmpwy5optG/h0lysg==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:l2y8z3acQRKeaxch,iv:gAlrZa9DaqBB6wv08/TbJR2lAf4y53A3z6wrCn0V+rs=,tag:Bw4P7uSmHVZMcFIc7AXZiQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:9CLn3/ybQ/42NcqnRO8J24wxLQ==,iv:4h073DBZMZmtP7xGNi8p5iLurjZAc56eTZbLzsXztz0=,tag:mjKhgvihv58nun3b9Gd3RQ==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:8YMKP6K7oMirewKWLTzA4A==,iv:mMmru8Ww3K5tVPclQCB8ouXGZ5oqR00h8UM8y1v2gQo=,tag:EL4drwfMpANaKIMFbxlsGg==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:A2vFxS880DFzklEQ/8w5/mIuGaKbRinWKZjC3y1FZwpe,iv:qwhlfQz5GPREDqCvbf345EvoI0ZfxMeMJcDyVVoZ0HM=,tag:5+Hg/pGmhJtqi5MD6Q0aDg==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:/oqSzvlXgoxdYhVsvsG0NdvI5Xg5I2/InU/oROu5tH0m,iv:49Vcd+J0GnqIDUDA8WVp6rx0ot9Im7rowAOrJ5Lkp+k=,tag:qLjwcJ2PqRrg6H1gBEVNtg==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:S8E2dqnXU/oDVNR+rIxA2LhQLo05sIFaz6FQr2JuqNc=,iv:lqD9HCco5bB3OU4RADeVhjiodrATBt017FspS+Wje4c=,tag:Zl8NItGepEtqAy95Heb1ag==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:yCD49Gtupw9a/CblP1LltGV4KPQJ5w==,iv:nJ0woRR8StmR2gG7+rxwybvnISBokn8rfVNuQVaNXSA=,tag:wG6BW8gGI9jsMbn6zTaxGQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVEdDOUdXWUhpTDF3b0F2
            dnJvTlFIZ2dYL0sweDNrQ0FRVC9YNXB2R1Y0Ci9jMm90MTJjelVyQzRXcFRtUCtk
            UUFLdUR1RmlZcXBEcVBCVzNsZ0hlVHcKLS0tIGJMSTdKdWR0ZGRkYWhrdHlicHh4
            cWp2WU04WFVKcTNERGdkWDZDcTZvdncKTpPoHr+CQzjoAlN0xy7JnHbDmJLiMATE
            12/IBOtD6jv8zk2433KZ3VNi+Asibazm+obZlCLJeQoKKhby6D8LMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T00:00:24Z"
    mac: ENC[AES256_GCM,data:cn1UKqcg6o82/LY82/OnDknoP2gictmPN5nfPsLkD4aVDA/9wP4ODr2Fm4b82q3OTDmwtEKVx7KKVvfn6HFpq13wgXY+nwHEnllm78Ms7IXx9fHxn8N0dXM1PsjvMs8jhw8o+VwPxpgfqaTqPZscR56NoiKLF0kWj1zar3+wJNQ=,iv:LMM6DS3GVRzTV+vUA9owLgxQrdtEBVOzyVrCrMHGufU=,tag:k841bzJGyg4pj4tLNmx3KA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
