apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WSgY5bB/ZBwsuVYTr75oboExUcH46Q0VxJQY2hsdz9j67yk70E7xqz4DfN4clFBaHXkp6WvnC9h9b6c7YH8wIow=,iv:xbQPa8rkL3VyrhJxjwmcY1rlRLxodgvCRLFquUtyC6Y=,tag:7opLJbZxR4WiQWLBd0lNDw==,type:comment]
    #ENC[AES256_GCM,data:4PlxqfZH0RYcTvWxCZ2s2qCmKN+y+AwDiPPbXviDU6sVMU9LUhcF2WymFMs=,iv:YBZWmkefqSqd0kNA5RrMH88sMuWwkqbrkY3nSsXndFo=,tag:Ss7KoJa9yxKngwRHh5+NsQ==,type:comment]
    VIP: ENC[AES256_GCM,data:bghQtb2AnOMGGgrx,iv:FOzQTb9gcjNDoX+gU3e4pguoOAta7Gixy+Jk+ai2D+o=,tag:e/ivbrLbzbQPOjVHEaWMqg==,type:str]
    #ENC[AES256_GCM,data:YhiP51U412NXNMrpnn3bIOcjp5uYSoCNztw=,iv:fY/hcHdH0bZ9VDwBFh4qeV20dh0uB+iL4wYB+pU1jiI=,tag:OR0wdzH3ZickGdvo2vZhvQ==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:HcqlgO06neDJoOPu,iv:4y/ixHuUVZGNVOUL8xOoYllZAtmZRQ2HL7G+Cmmgzkk=,tag:YaOaeuL2SUKp58EEOqahow==,type:str]
    #ENC[AES256_GCM,data:Dx64nR3slxbdKWn2F21h8Bt4TrXvdHdmD9WHFKjRL0+dVw==,iv:MfqFwWIb/V7iNfx/n4Jh3mxgJqjr+5RS8o7VL4ymlgE=,tag:pVkb80ebXa8HH7+0MOfWEg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:PnxOZViFJccSefw=,iv:1LuS9V7A8dFDV1iIwpqj9A4r7iYNim58YzHEXEso/yI=,tag:6Dx5so6IseYw204D5+nLiw==,type:str]
    #ENC[AES256_GCM,data:JPAHrwQ/JWK261B2AiqudUPp6PsGSjEjRQcBXPl4j8m8jbqzeoDbqsrG0IwktJk=,iv:asOkW6BNILcVqUb/BDiVhtA5m7RC7VdkRnOLdNxEma0=,tag:3HQJee+6siUO7jbkfa9qzA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:XeK/BTub1ktdT2wP37I+ggTlKuhUN1FqgA==,iv:G0uX+8EVWSAnD9SGawD8D9bSWMjdg9WCd3fiDTMU93I=,tag:Jl9J6EEN9+kioa42O0neSA==,type:str]
    #ENC[AES256_GCM,data:m4Y1mvg80pAt5HBJzT18zod3IdjJ7rIVGR2yectUU5cYJVqqJyAtvkobJPiUTpM/jjfert77glLDVKKtO8cVoZrWijgicONoxyJdooIgGVA=,iv:SUtsF18EWqmv4AbmPPS+teSdvVBYP4D62ACN9uWhi6w=,tag:4/sKE7Kr71s9O9w7+S2Kvg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:PtfYkQEHEGYndZaA,iv:Y8PCG10AGlG2kCcm1T+bUY44gxMjUIuQWJTckNcIUJk=,tag:f8pZ0qYlwH53k4pXGFN0CQ==,type:str]
    #ENC[AES256_GCM,data:S8NA0yhGgav6o1tzFuLo+btwfjssf2mLEor/Mfr/LhrmnVfjql3czalYr9vInAP95HPst3xSZBHd/GFmTTuCtCbcfz0=,iv:NWhM2fDxlFw4RJ9jj/or/y6Alq1XqDN80IYivMpEhxY=,tag:RcPXDyVmxyRUFxvUF7R3fA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:Sbh4M+hjhf0s3E9Z,iv:6miGI5mkwJ18sLHM3nWqatWTEVfqQ3Zkz8LwgdcvtCk=,tag:uk9jbAUTrT/L/4etyENgbw==,type:str]
    #ENC[AES256_GCM,data:7ViXfyhK3fn7ycnegLCO0iOnzPT6llLuyY1DxKr+6C7l+pUXnTzP+wrNWktETvGLIDEeHDEOdVo=,iv:hIBmOgeUufyTwsuL/rWcWj+AyWBb3k94bu7xQiAPeEA=,tag:y7oqKT43jODun2ipffqZBA==,type:comment]
    #ENC[AES256_GCM,data:eCHPXIMBT+K+3xoNxAR2Qv6+KJTHRiRggA==,iv:8KIFAmD3+xNOVIvb8VFF6xcUr9VQOCOG79YtNaZMDAM=,tag:jNCsFMmM7mCwFOmf1zWzvg==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:yNO1ql5FB+348eC2md4snB5uS/f5SwgRew3lRopF6b9y4pU9eq2MxJw=,iv:woKQZbD/Su8qgti0aSvf85O/nhhw8t3CccmlR+VpK7w=,tag:gmef0vuprFUXc9qpv/RHkQ==,type:str]
    #ENC[AES256_GCM,data:LRXqVg6s4UJpQkjn+Q==,iv:NdW1pH8oMV6V/6WJfdZHj410h+Qu4pcuDclSr35an3M=,tag:zLV0WXM/fx+2c7/BanwRQQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:18aQGmWqsECB8haynQ==,iv:Ct2U9kH4J/SQkLSt6nqGfZutMMnLLTpeHisrccodkB4=,tag:tGAP3K5IBtJ3ka6Gp8XauQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:wGei6BqHsHe3EuFr7A==,iv:OPdCqH5nIN2A4Gh3M9rBnlFbfg7WaomZXp7SV+dnUxo=,tag:jc0HIe/btWFETOJG6GGm3Q==,type:str]
    #ENC[AES256_GCM,data:sW0eYW+zyuo=,iv:HDsuBXI45Ud/kms0K0Vw/QMVzXqx+k+QAQrED8DUMMI=,tag:M57u3Kx0hIp3M709JM2vsw==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:3hYFyOfQcHxEplk3,iv:oc7RUwTX0enUg/TawIlTj3mNmQu/WRV6waDkQVBECUs=,tag:iw/dqJyVOn1OmRRibJHsYw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:7DArKYCFV90lYL3T,iv:/eT9Az5vm0KX1pOEl1A3LU4rjYHwXA8YsGpnKOTrsaQ=,tag:405sbQeq6JBTbygUE51rwg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:8aX3LTyz2ojXbdM=,iv:Sbltoa0aZm4EIfUnfSgKlza/FW/rLZ7/ncwxNCVRhxo=,tag:flfeEhVvEtePdpt8Ja22eQ==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:8GNFJrHZz/LBYQ==,iv:dtovExGomU67U+qrgZg08KURxt42X8uFBLHUH0LJJOA=,tag:bYBGHyfU80G8S8gk4OAEJw==,type:str]
    #ENC[AES256_GCM,data:VYgmfPA=,iv:7LtUGwH95VmX+zrdAT16m4G/xOLoNKn7MmNPVCJANuE=,tag:BsUFnPEsnktf0YDtgWZ7Mw==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:d9S90FQSDqOXJMvp,iv:6GjnOeNr0AQrHvRK4OmsU9m01PGULOw83X7L0Ws4+K4=,tag:1QdzTSmOBxMJ5NXQ4hlZlg==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:EAt9RGhGVjiwH7YuXLb3hHXrD7xLf65KlNp878wRkxHIaDzHJ/Wr4thRJ5VfJKToukdvedHn,iv:x3UXH7vGqBnb6yy9ELP7ZT3J4pxCuPMN5A3jqQTUmkg=,tag:WQ3oxNao27vqrPH2t50pTQ==,type:str]
    #ENC[AES256_GCM,data:8zxib1TJMNo3D9M=,iv:5CyQFE+EpQ6PUynS+uEAJWFviIL9pDRTwSZDxohf2As=,tag:ziYqUMT6JHRCl7SNOZDZeQ==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:iydE7qsAtqQPCxhr,iv:neC+ZVLvB2oNqv1OL8JDkyhz6HdHzEQG+05nAVimUwE=,tag:2XsZEDXKvR+jKyEzNUiaVQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:HTWH5PC+It9v/do6q7/yubKcdQ==,iv:sgoikmWZyzu4/2Xun7NbWICW8wNVA3FtllHe2iqSI5Q=,tag:ZBynCy+8A6POr8bO+bwn+A==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:NSEDxr5PyGKH0cbzl4Mi/w==,iv:xWxpp/wECT3yoOAHW+oitQHMxjhJiCriXy+Qjnd/Mvk=,tag:gbQBbn0ikM2uz9FT6/fbPg==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:q8SVbqQnpd1snPcaDSUgeJAG0R56fNnhLKNPYN9O9my1,iv:3uEPo/H8I7tqDiRiDhCwMp4x/h/A2/mWXgEuhGWuK5g=,tag:bHYgQm7iciSYV9C3wWc9Xw==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:JfgBQzMlJt8tjZrus/t8X+QNa2Dz0J+SE7nSRgcPM0ps,iv:+0Zp4tdN0+CB1qJ+a2YeZ7BevsODLg1GRwLHpUIdrJw=,tag:C9kphPGraydixxILvowITg==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:28QNtKNhxmOK8eosIX1vina2LL0Exgfc+ulkngfX6fo=,iv:STMGBnDGUQFzSQ9vkb9lloKri3mMFHJ4pm6oowXt6gc=,tag:5iDLCoaPpIB7GyE84OPrQQ==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:lww9NZpCkow3cF5gv6H5K0F9Edec3Q==,iv:7dVnGnYoVwr8D10d2Bn9hdt6i8Jc4NVsqIFbKK3cWS4=,tag:a7Ve1ruJGm0ogH7a3JS3Mg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ckxNNmgwK0Q2a1F6d0x2
            Y0dpejhtb1lQdkg0WUhzYVhYbzIvdVdWVkQ4CmZCckVkVmtqUnFTY1p3TmxWWlpZ
            WEV5VFhCWDBTS1g1SkV6Q1I1VEw3UUEKLS0tIFg3OEU5cHFuZjlDS0lUWk9VWndB
            U256VmYzVll2UDJ4YVQ3Nk9BUUlqTGsK8V2i6hIpWbXrgwe1UexJtw250qdsQ86u
            hoc+Kofweb5y1Bsts/ucjKbMFXI32vPU2m75leQe4wiN9rUKVXWuBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T18:44:30Z"
    mac: ENC[AES256_GCM,data:0fcGtn19a5FSGuaa0zjlHJIPVOoWZ3vkhybBTpgiWr7Eaq9kfJVcWyl0E4oIzNeZD4EyvTBgO01utMaUOqpRaKixxqt4EmEdC4lHsH97YrPQxJQ7NI2/Vn2kvNvvqEUiD9xC2LQqE2RgZ0h7By7drEhyLCYwgF7sRirpHRq22+4=,iv:4UWU0UxM1wGiVA76Yev6lo8j1a8l9pX3EYLDtwA9Dgg=,tag:zb2BtMDse7tXLif5CWnLqA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
