apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:2HXa1YjeE0IPUJRSDVDfsvgTKIW0zbWM5YCRzEsvndCVIlY411W7Smk9pquKS1h8FsjzLZegM9CG6CPhZ1iE8UM=,iv:M8Zz4e9faBVVV96bMfeWyFU/gvSAUuwqVAfz59eUcYA=,tag:Vqp1sp/R9dWB03jjeGMklQ==,type:comment]
    #ENC[AES256_GCM,data:zLim1YEPbdBf1ZLwAEVz/Cak2FGtwI3fJ99bDuev2kTqc5NH6+/5tzI9u+s=,iv:gVM5yUF3B/1XnS/yT+nYrWQ2ly2nAMK08cbWUFRtl9E=,tag:LLUBn+y2mhr9/g4VTA7uNg==,type:comment]
    VIP: ENC[AES256_GCM,data:lZaHCz3O3tr3owON,iv:tG5jJ3zZY8D+RNU1eCnOYqZOF4ePe7VkwxBj8yaV2AA=,tag:hw8TeShA72h23ZsIDbJudg==,type:str]
    #ENC[AES256_GCM,data:MCXDvgYlSa/VpbvEqoZ2CvpZ9+67Ut3/JE4=,iv:zESKgknReJvnKNDVl+Kq0haJbyuyUk1/X5ZJX4xAKTY=,tag:xbTYNTfhXq/x13QM4kYQxg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:gConh9KkhFso0Zdl,iv:LxA4bDqxt9w6fagU1TZziEoaW6q8IChww7GTCbH7TJI=,tag:BY6kw3+L/c7e7rXmvc9PjQ==,type:str]
    #ENC[AES256_GCM,data:dMWpknru/TlXeIsb89VY+bajTq16Oylf8MNwwZVcSU1TjA==,iv:J8mEjklGWFBqBHlEonTGIrTGXk70VH0idwndcWffXD0=,tag:nuReOhtH9aHdVN674qm8kg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:lKj/VGsErHSJ354=,iv:W9CDi3MasLc2yxHGRUpPCe5lwjLQ6O3DMRJVITKhtDQ=,tag:3FcZIlq9JU7k8HGMC+BhVA==,type:str]
    #ENC[AES256_GCM,data:xOeen3c/bQ40Zsmp/+g3kpK4vPshkoqkkFOUi2qfQt8/AAb2ap60NFTFkcyMPNc=,iv:kD1Rhb/0N3REnEWE7dJ1aoXCf83Z6jH2KbLpeR4TcKs=,tag:Zlx4Onj0ktbLNhr4iCjqsw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:H69YtFljH7gTrQMPHbV/ul+OFAR8IaFT3A==,iv:ND3u907s0D0OgM0I7XRhZFGSxpEmEd2qhKI6UcTM7ck=,tag:a3kXXTPkjjYVgRgyyZJ3hw==,type:str]
    #ENC[AES256_GCM,data:92yLRLyK2yNJulv0B1C8r559H02nSO4blEH4X0BLyayK/7l8it6ZAMvv4f0zRlYH9xJyJMfSwZOyZKNftC4FO13tm7u/M8R+xWmFv31ty7w=,iv:3dfIFEUyZruuQ8ORBGcKC3hJjnQE8orM2Fl2fukZ6nA=,tag:CAttVjqPyV2oZvVrTnS5Cw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Y0h7Lk2iOdm3jqN8,iv:0Jg5ETMPxdyf5yP/OTy8V3B16SSN5zbdocc7LNl5aoQ=,tag:a0CssRmZL7hxussgErqACg==,type:str]
    #ENC[AES256_GCM,data:xMQISeTProLMO9H1Z56Bj5gTCmvISJ4UxAtMwoC24c29N0HDxqqZAf6L9pxRMIQHQ0ZzObOyskLOXVwNdoYgFltWyAU=,iv:MGLK7NR+b34C5hTCrd4WPB5E7m44aE5BTIYA8Bl87SY=,tag:XyU5z1wsCXUfKG6kt7H8EA==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:8BRSjDQKgQEf1QX7,iv:/rgwNeelA3+T/gL1HDX1y0ix87RLOH0NuOktWzX4hog=,tag:2mRf5hR3b1Fm3x0hDckAmQ==,type:str]
    #ENC[AES256_GCM,data:Dqq44Ok/gLT27VNVFLsZI29YgiG//tRXBK2lyuWrA09dKA73k0nhUhArrNbVfVMj/eUZv//H4Io=,iv:FYfEzERmzvBYOlAsYypwrYWKACv3GsMmr16AxxkRMBo=,tag:9U+shmlEjSCu01lQ26JC6w==,type:comment]
    #ENC[AES256_GCM,data:KvwMoSi3hDbtMsUFf4+HAYNG48paOpj7dA==,iv:SA5S63tZ8upjSyaujP28y6/N4jbByjMAxpwVryFMxqE=,tag:vV5hfqriFqPtokh7bSr/DA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:d4kX6yg5LkU8eNU/YAsH/+J94JJtDIzgurssdsiPsHzTCxrtB/1dMy8=,iv:bv1XDx6mXCURc+gUhiUorcgpq5ptE1jdUDBfe0wVfSs=,tag:x3vXByKFYUxmrGXWCf42mQ==,type:str]
    #ENC[AES256_GCM,data:tfny4nNKZGdc9Vzxag==,iv:xCt3BG/tSQQX5Oju6s0GXkwVwLZJ23bUwGfHbQoo61Q=,tag:FSnLMjxHivsJtg+sqLE0aw==,type:comment]
    PODNET: ENC[AES256_GCM,data:KbVqGi03B5QlsPF+YA==,iv:uxDPdOyEKpL1N/5I4zOw0TIZFEs7JWnFj8Cauc3lhqU=,tag:/1f3SHg5M3O7RJGHkYPg/A==,type:str]
    SVCNET: ENC[AES256_GCM,data:9FgEomOg7dqQvIRRGw==,iv:/A9MGydhGvX9U/cgDW4PVEIB1dLOZ6l7npUUnEW6Ks4=,tag:6sYFzV33FOj3C+Hkf+fdOA==,type:str]
    #ENC[AES256_GCM,data:UFWIePsuIWA=,iv:JRJYnGdy1QDPGUzcdM5A/wkQ2AyACx357r+pwa53GFs=,tag:+5xjkK8hkoQBtr0UDoWAjg==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:KwIZrAeALZKOAg33,iv:fQN1rqZGxRVMwRMF7qiDlq3id4HXoe47pMwm+oSr8nU=,tag:PQHKUkifK0X1jjADE52dFw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:+SONhbzdgsMoBcvv,iv:wNJqqeEg3d2qa0QEhbSNPkyo9aYItk82rhPAfl3JYxE=,tag:McIGdlJfHf2vx28CYf5SQg==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:8QSImokyPDNiqV8=,iv:MV/i41M8oCt7mGCF3bldC1j1lG//3YFa0jfLAsFR4U0=,tag:8lTAA+VYHH2jV5GuMsbvew==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:YkU6r3UQ7cXl+A==,iv:SCB5OvCSjSN1ur+1N1U53GwlKxp0cmOASK+f1+xAHMM=,tag:Tt9h2aO6RY0nQHKfYkjijQ==,type:str]
    #ENC[AES256_GCM,data:+vGGFe4=,iv:gP6+uUf0mRV2N4UFgF+RxkRqAwiLj1DTuGuNiAmsXKU=,tag:X9C2rnoJLGO47LkViNhxAA==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:utk7juwGE7k4M3vH,iv:K+gY4/TqAZzX9X4+mTUBkwqSreA+bglB5q7OJwMQV0E=,tag:rAJU+izBCPoMAEbU4LjEag==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:AVpPduDmcj8Y2XAC+nMNzZ1gOkvc1Ytn7KoTMyYufieQMx7rIvk98ZIBw/Jd4mN8xWyANGjQ,iv:VCkJWkYIPXM1U3YNugHPqJXw219McqZ9IIgqIySqkPw=,tag:NtzHHOAQIKTHD2BndUOEVQ==,type:str]
    #ENC[AES256_GCM,data:aL/IDLXzxGC6bNQ=,iv:MLlYGtDlS2y0C5up+aLhPajKwStOoxAzqIDHfRSpUBw=,tag:kcyp88CQdH+5+gUSSzzQFA==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:sD5EVq5NzHc0yn2d,iv:6Xvo9z1Jg8v3X4fCfVGFtwsCG2FPF3I+V/Hz732n+hM=,tag:4b0UM/TrDxeG6rejvxOcLQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:CntLWBR2HzeDOXZOn8PU6im5Mw==,iv:boQexERnTSxxrlg72CxG14YL6UlqDdaqQ7KbjtV6gj8=,tag:ZjC4ICl5Y1QqTraoNrE3Ig==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:CNzXXrtcIzsLOcxMnjoqkg==,iv:nXautgE0jT7oIAKNix5oQTwOZk8oHy9XISRViWMR7SE=,tag:BC8ClHz2OWHEkAn/uzTNXQ==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:lGft5mqLuZHAjb2X8+JpM80ON+ovZsuUec6OQaZ8EbtW,iv:Vh2uu54t2A2a6DX2zPIB0MLOHowgcVYEe+9rVWWBl0w=,tag:d5PMI/MOBQQMumHqZKusRA==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:196Hu5c/MXHXxZuvin5u09Eclj7z0vt+OawLEfJpgf/I,iv:zp2XMSW1mv9CqVH7N7wdRDDb6S6jn/SVIuy6uMqghXc=,tag:srJ/pO3XI/ETgjev7AOeWA==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:UsyamtMSeZpsd9CMuFpXPIaUFwJa4JMjouv2m+LAoQQ=,iv:vPCMp4dC9OH2LThhLYwgwjTbU1WjwItLg6brXLXAO2E=,tag:izV9z2s10FsB9g3ijJ2Tmg==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:P1HYT/pxL2+iyMc2x8pwlSRL6JUIrg==,iv:5ms1qKwZSPBETwLgsnBOjx435nyQic+0GGTIpuP2v+M=,tag:Bc2xemxo0L2dltWDsse8qw==,type:str]
    #ENC[AES256_GCM,data:PUXymw==,iv:1fxlOMlDPb9rZC+cX48AKQ7/RU26oj4eowvoYIdJaGQ=,tag:ip1fg7tVcU8DLgzDNX5SjA==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:5YzEOafY,iv:HIFIoXp5rUWAl5OgiRWPxVTjMiCucmly4x6BIxeHEW4=,tag:J4yphx+Q20ookpozCchmww==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:u1pu8CvvkvTVTzqtshYG8PEtCOitl+EI1HQs6AgH7Hrn3c+zUbuFYn0ebVc=,iv:EeaHarquu6JLXKEVTyJQG3iaBSeuGm21rwr3LD2KrAs=,tag:RG7W8kDVmr7Xs7Yxp7liGg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Z7TECv0UPEz7wWhfKOC+00aMpNInufbejB7wQ1CepiKVMj5I63Vgd5lZ6eE=,iv:rXVFAAorlwRHvGO9g0u5ehA4AQWO/z6CedXnF0y0heE=,tag:3qNq6186txz13R2mr0lVsA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:H3BsWaWObKMPoah7PibBEr8=,iv:+lYoqF5bzl+nnLWHIcoit6UAH95TaS6j/I7GPV96lIk=,tag:xFteVcAgvTq/KEhePcnTBA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:xX19hEI=,iv:X9r8N0oABGpov01HP+EST8KCzUHwp/CN5dyrmBT2tXA=,tag:zrdN9PBZNQx5UJQDGYHJSg==,type:int]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:mdFtSxz1SOU5IsvshoSePiwyMRtVNW3guZuWedrQvmjd,iv:spdzk5uNFAUgZl9uNDsWHjvUi5Hc1WmRPO/odHP2CIE=,tag:/ekTrZMKVujXoiXJxqgJeA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWDUxeWFLaFFrTWxGcHBr
            QnB3YWt3VG5jSS9WTWNCWnJrZTJFZ1NuNkVZCmZ5YU82QnIxVm9od24yS3lTVHNS
            K3g2NkZpUS9kNjR6cHFia3ZMOFR5REUKLS0tIEVuOWI3SkJrMnNkR2VzY0RDTjY4
            WDBBRlIvb1JXSml0ZzluUlJITkphZzgKGOHb2TyGp54wtxzJEXNZziS9F4/9NEzn
            8XS/XNUNHB/xD03FU70pdZ03tV7hZkF6V82cQxiDbLo/v+mFRjWR8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T07:32:34Z"
    mac: ENC[AES256_GCM,data:UuDUWQbU1PvjOoLDsAEP7Vuu1I1UswOaUyuXI/VPlryG1FRTVAtkjwPCKTCKUW3uXqR4JLPZKTR0vXUflH07R74Fttqz/2tajm0NKeE2+dxoEEIjP/+Csu1AhaLv4wvxl4QaChGaR8Ldp3DidO/y3ndvXSA3HWijo7FN4skyQ1o=,iv:1OAKeQO3LSp5IKQ/JrIWxMa7DgLIKUUV1X57Fmc9IT0=,tag:boWi8h5NV4shuiUMeM9yOg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
