apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:bIdl0RhokoVsDctZDP8W7AHcyC5vPmWqtgE9XgpMkturtOZDr54Mdc294CVzgUVl2e82NLrkO0Hia3L6zL8KzGg=,iv:tCyp7jvpwXF8c51BbBTYSXFN6guuTUzt3oUVK5LuOwM=,tag:WMA9b6+aNx4h4EhALcHJTA==,type:comment]
    #ENC[AES256_GCM,data:uyTV5hXo4Y4vanMfe6VJndrvli1M3tHrF3OcRb0tMv9KZ4yF3WOJuSAhgaU=,iv:sKSstAKMP3q2saKl84THwuu8mK7ooFCIgV6aMOFTGvQ=,tag:FdY0pwAiuzBgxWQA78rPlw==,type:comment]
    VIP: ENC[AES256_GCM,data:ciFBh0k6xZ7qwG7U,iv:QtBX9Nlw76fma+VRlPqHFK/rNZiZmIli9/mb5s533ik=,tag:65Xy6N1aMo7wm+n/85wchQ==,type:str]
    #ENC[AES256_GCM,data:Kw/unOuL0gF12y+qf3BmgVxHHhwbOSAhOkU=,iv:XhjG35e7W8FIP7qn/xr34wNl3edyaRiv+9rwebetX1I=,tag:raXNh0klmyGI0KyLtx+iHw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:R1hqIqoGlZyp7sn3,iv:KCATZeXe0FNjwgtKHxAgWiiM6Ef4xWF6wU84tvc79pM=,tag:yMu5fREZ/KuYMzoyVITfoQ==,type:str]
    #ENC[AES256_GCM,data:NGQhdXWy4ubmo8OwTnir1r6SldmsJYxg+a8eEFJ2QvDeaQ==,iv:d/mQ1ibEoaa0fyWbqaXyQYf37HiYdMjAml1jwmp/+U0=,tag:mjXtvWp57U56S+UsRfAYCQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:ULuqNObO6v1dIyY=,iv:ticqT49hN6938i6vPw4Ct5z2Xx8xD2PZPxLfzqYaJkM=,tag:BUQQCs0JdNK5ILRhP8/Knw==,type:str]
    #ENC[AES256_GCM,data:Zh1vmpQ/lJi3/AjeOkGmWvAJxnWoaPf/9XUbM7et8/oraSAL19prV1QeOoTqUeo=,iv:mMGty4Y50QlLQDbQXx1HqPmcreOJZ+CB7t8zjWm6KAA=,tag:AVU3oSTT+rCP64p0Wvc7Ow==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:g33PdlUP1ANu6I2ndiGXM3VJeNu8LaiTpw==,iv:IC0Keq2QjZtFXIUa8walVhWAXKr/g95Hld04yoJLICA=,tag:+wMZcKe3R4Vb0RYiYbb1kQ==,type:str]
    #ENC[AES256_GCM,data:W9cuIRcGMUaU/FIIFByafPKwhDSnhVugkFsUJH8CeSeWKQEFRyR4l7MIoRwTE9+Mgn/VPOgm4u814p+cfmhUdGqRt/1iuka49dMNdAbfBIk=,iv:lPK8unwEWDNnSFzQgXdKbXQ+poVB8jtRRpur0ixTf+g=,tag:pWpnszoCHwgX6w49AVykiA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:8KcrmHW/IPHLAUia,iv:b97KbvOqWTsbr4JeCfJyxmQEtdN7zxCVuMrmLb3Ci74=,tag:AwV9ptcxY5pwnzpHX6e+5g==,type:str]
    #ENC[AES256_GCM,data:K+B2zqfqneMo2bAogg/cQygMnCBidyXOMZZR51YJPieDypjqC5IqngaUHhKIzCy/fRuv9ASEpCK1npMu7Pn3kg8L3HE=,iv:43vJ83P0OFXn3jGe5Zxh0TnU8kkWcVWJHl+NGLC2sZI=,tag:xc+IiKDLONCPQe/RiRinVg==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:U9bPkPvl9YXksJVa,iv:SreviA8BMXzo70BqyjQc01AMW52TmnJliD/TW/EjXjA=,tag:SLL4NGM3DDG8cD7QENEcTg==,type:str]
    #ENC[AES256_GCM,data:USBT27WHJ0tq/rQe7Cq++A6Vg1mjK3kklJjU9mx7X8JycrIPUl7OzyAZsDfZI13EygWA9WFujjg=,iv:PcFp0RVvELPy/qBN5ASxWgfPr8Xdu8x6Q8JohKmhygU=,tag:kfkPFRPM9FDX3j9ZRjFp0A==,type:comment]
    #ENC[AES256_GCM,data:UssRJaEQvmQEmZxw4htoZAIVOUH46uS7Ew==,iv:D2rLqt2BMgXleTJFjSzj0LL0DEEse6QACN0A9x51m6U=,tag:n7UoNESxitjXADl8VRgx9g==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Qdjug4vsyHm7Vs3+TZ7ISd7wVjYQ3f8u9seQ7XY7czRLn+cQV/OB4G8=,iv:D7ujLmCn2Qyr+JCrseTtoBzTKJuQvgXcx71F7W8LkuE=,tag:hEHbFUaoLNf/QESdhFl9eg==,type:str]
    #ENC[AES256_GCM,data:uKYJSTzA7L7W9CHU7A==,iv:AongOqCtj6mml2cbx8UGej/IEduixGVSUChKRURhxtA=,tag:51ils442uWEYef751+9wuQ==,type:comment]
    PODNET: ENC[AES256_GCM,data:xh8Nh3mIP1Krw+wQPA==,iv:GLdtCO+eCfrFTMP2J+eMajbIbJrWRIeE8olZbX/sfjc=,tag:xk2w/X+aUTKn1Cr8MSd1EA==,type:str]
    SVCNET: ENC[AES256_GCM,data:B7YgodXWEHy/iYv/IQ==,iv:jZ9AfUg0s3jArpH4M7K1WTUesXbH6j3SSmIrCOwaJgQ=,tag:eoCmB6tnXMTsTjKE+cp5PA==,type:str]
    #ENC[AES256_GCM,data:u9DLLVyLWd8=,iv:u0d8k+7Eob6MOjXwA2d3PCMtMEnCLzETKmENH5foktM=,tag:yR350yG75NcSK8Jlp9JHmA==,type:comment]
    TRAEFIK_IP: ENC[AES256_GCM,data:k7u8HQXYEsqp+Nqm,iv:tmLaBy3BdNFRRUBKASptj0hg0MyVQwVLXdHLT6bfJhk=,tag:jj9upySkoC02WWqZZqIP+Q==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:VAFK4kiLhcKeErOM,iv:9jFgx/VAf9dDbFU8DbZXYytj2EidDTDWgOWP71eQoC8=,tag:qUNIO+sdBM0yJvZifA7x6w==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:PXj9ETkyutcLMWo=,iv:FRQWWErWsR+Tn09oYyh5q1GiOz+hhm4PpiY6ygJCHJQ=,tag:Ppc1YHQd7JvksKIv1weKAw==,type:str]
    CERTIFICATE_ISSUER: ENC[AES256_GCM,data:MIJGX0ZzwWxwpA==,iv:YMoHRU3egmFMDKDWV+LNsgeAfz7YoalmHlDZ7h5+O7o=,tag:Zd8t8AkzyWJmCywwoUGtZw==,type:str]
    #ENC[AES256_GCM,data:1wWS1uY=,iv:gRTOS1oSqoG4MQIR936VFuUEdKsyeTbaoyJH1q47s2E=,tag:Roti2f3QRVtOFY2doJxccQ==,type:comment]
    PLEX_IP: ENC[AES256_GCM,data:6yvfyUwim68D/RTZ,iv:e59c284bVVT3si+7nOPwKPAxx7m3SijMbSsuZ6ufPRw=,tag:Ee6jCUbefU/U3p2Qt5h3Ig==,type:str]
    PLEX_ADVERTISE_URL: ENC[AES256_GCM,data:+3XFzUvB7fCxW+L+551BnTnKBSs06D7bEBsBtmOlFc7XCDmfXNL38Hy5is9OUs4jE631iBZr,iv:AnG5tfqsKJW8rRtK9Qq6NNReAbSfpmlt+lLn6+l7mFc=,tag:NLBRGWF8KSqAoy0aI1atUQ==,type:str]
    #ENC[AES256_GCM,data:c8/lhbfDY5us6Pw=,iv:yX6aWtdfQ+Hw//VLoWsWC0I9nScmJU5UdvtL/1uaXR0=,tag:HyBcRipjsCIvaVtkaHiS1A==,type:comment]
    NFS_SERVER_IP: ENC[AES256_GCM,data:D+1SXSkuN1igxqPR,iv:zIDq12Z1srGUluPwe9djMu8TjUCD6L1PLbZQdqND3kc=,tag:cKpbKQ0XgFpP6/qBNJ19DQ==,type:str]
    NFS_PATH_DOWNLOADS: ENC[AES256_GCM,data:meBsTuEuu9dAwcSjiZxVOIvNig==,iv:tf+nrMPNYhe1Oz+ZpenutfCn6M0WBEcdvxnDDE503qQ=,tag:7m2DTkHXn8dqopYCjRUpQw==,type:str]
    NFS_PATH_MEDIA: ENC[AES256_GCM,data:2IY7Th+GAmu/78RRlm91Og==,iv:O+e6yGX7n6K7DPLvBadqDBfV1EWnqCBbKlFbabimz7A=,tag:vygrcBDzf+M1Oq9H92PTug==,type:str]
    NFS_PATH_MEDIA_SERIES: ENC[AES256_GCM,data:w0i06iALuig85/AnKF267FsmGefAbHPBM9xjRh1hVPrB,iv:BCxoG7KzEU2dkzMzgujN6Je7SU502zUSZD/KCXMm4pU=,tag:0lCeBkfUqPeolrlxoRGAfw==,type:str]
    NFS_PATH_MEDIA_MOVIES: ENC[AES256_GCM,data:Fc9NHLEenYorLIqwfXBXpTttzGJeFX0/KT2P/UOmwBpx,iv:kv7N7guScX7+VoH7ZS3qcbdm2e0wQ/nwincd6i1XZCQ=,tag:wHh05PUIX91kyACHdMov0Q==,type:str]
    NFS_PATH_MEDIA_ANIME: ENC[AES256_GCM,data:5IDZpwaoGt0o8fYTNThK6Q99FVh/cVE3LW/6CJvmC34=,iv:X20YVzzDGWeRPtqvAZsWma8j/6OXJD5r5Msp83e+k0Q=,tag:rgNTV6rBR8XV6wx1mD6Peg==,type:str]
    NFS_PATH_MEDIA_BOOKS: ENC[AES256_GCM,data:iPr/Ac6oQExMuBC1zijH8UtUxAaIcA==,iv:+o54J1mHY+tvzoQA4mCpDl4VnM+2iKoJm3Xut9ma3to=,tag:kZFcxMx9Byd0a0FmeLtq3g==,type:str]
    #ENC[AES256_GCM,data:Ssy+XQ==,iv:V3cNrM6hRl6fE84roK5XEJdr1WMFx9Qf3ndSRNedTNg=,tag:zDAN+gxSg4wJFrDbwAO5lQ==,type:comment]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:dAEnuNcM,iv:krdKAXG3LEGfhnvw/ugRKBjaRKVdCQbLNhnNzLx4MqI=,tag:F8QwMCXN5+tDT5l4uzI+6g==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:oe/j2THsxMvSJVrIze8Vh7HEzc/CblmecLB4UChnlOZlMXWK6Qu3mq7sRBs=,iv:Iwq0M9r3HD3rJow2iDrymhEn5Nf4CvBVIilJBPDhlTE=,tag:GsA8mKCChkC1iEhncU70pw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:s8NBYuEGvytHWglAfaeRBfzDA8p4+VnMZssDg4un0B5RcKQfn2n1tkmAY4c=,iv:k0kVDz6/pqvMi5UXKGDRM6nu6t5K9hgc/xMbC/7nVMA=,tag:0KYDWOWUVSfab+3etgQG6Q==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:rdmrdbduKu8MQn+RlXVvIBI=,iv:rcBx7iVVVnu42SS6L81eSrWyi6XmpJ4dlspKhI1JpOA=,tag:mKxdFBTXLPErWP7z/TgkGA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:F3h4FKA=,iv:EZN23yHtJ48tyMRJNSZ2IkA792/izOxJlOYCUUCJWCY=,tag:tgIhoZbchDLqOPAoTZia9w==,type:int]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:bX5SPumuIhiUBy5sh7qLC/4BDbxiR/HxgD+gGMDkC8tX,iv:Zk20ZyvrXcaAj0SCN3CmPltyP0chVzP1GvJo7vDq03E=,tag:CCTgxfyj7fl5rXViStawGQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQTd3ZDVrYU9wZ3pleGNi
            ZW1jOE8xSThvZEZXQnhnS3JTWTdXbGRubVZVCkRmNjBqaHZLVWR4djNNVDBvN2Vl
            TGNWR2lVeXQ0cmlvajZPWkIraE9hb00KLS0tIFlhbXlaZWFZUjNWT0ljeGFyMksz
            SzNHV3Z1MnM5bmFuUER6clZVcnJEc3MK8fLe8mPJ1DcjoiYCbPQYSL4tYwTcp3v6
            wr96upbN1giItqzPr05MoHzg41p8fzB/dbzzD2lnB9pKsoPmS4R7Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T08:00:21Z"
    mac: ENC[AES256_GCM,data:4KPjV7i3S3PCSc1MAQRfAo+ZWKaOdB7NjvE+9QrsQfNvXR3EBfQ+ODAj+FE4pRcUE7RXN+ZYNyuBIfwQwO5y4xV8Hgyt0cuN2b84j+80t8uOYjUj1IfYgVw4318ZmuObG/wqPpWzlBvHc4tqG7n2UNDw496bzXi83mnX0cpjwiw=,iv:fZplAav48PBxEnhBDaHxNEwGvmRVLYueYGxVc8HMmv4=,tag:QKRZ4I5vx4EmP9XHMyKmEg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
