apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZnPk4YcnDUPdmf7Q0L1pNXHlxEXha4pIiHc6Qmjm6sfPwtesOnhS9xBs2GGbOkEf+bkZN1hKMB+jrvoW8Gl80kcQX5/K5Sl9u+eMsPLz3AqbcfvN1EI1aSPp2/BNkHvtlp7P/8BbftvYe37eHnPZcm4iSMdGxnwoyiScgmFbjni/ld/BINDHE+CWTGhV8Z591RHggR+gAV+I2bSqzTD5YrCztUoas95dU/uK3lOAJjYRXlvMP1Vp4a9XVi8Z4JaeicNnrYzKb5AgvdWZFlmYSKqywbuUGNGZOpIuPxJ5Nyry/Fm5wRt9j1B8fcyStELd531xrVqvAPJzreesIbI0hdvBtPFrD2qLpzevIc6APRQi/w5vfB2fy4ZvV6QoSNup,iv:jXSfNj5sSsVi6jIs55+21D1bo6UdTYeyAN2OayocETY=,tag:2c9RMsDw7W1kdYBWWyrSaA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4tMlxckcW2qhddh3RLRz7cwoShDOQZnpedo1vifFVlILmG8nhgKLYXjWvdVaF4IrXfm/436zBWS5AUK06IZlf+3q9P0UkD6dn5qXxBmSrtFQdXb1w5OJd7dnYtvE/SYZIIICfQWlhWWIfTEfrTSlSEoAm2PniT4bzDGlzGw9deZf+Gb64L+2e1+bnzYlO+1RGk+w5GFFggtvaT4v5HeXs7VYYi0OYH4ZrrEzgmQMAF1JoYRs2PuW7o1Bfj1KfATcePHLwOafkXlaYBaJHg==,iv:G3XXI5mvmftlX+dDwJ6LMH+EZQvUIooOjiap1ewdYaA=,tag:ExG7ZdAzJM0FvLCNJvvBog==,type:str]
    known_hosts: ENC[AES256_GCM,data:20ZbyjihHI65IB5pkKoVjJ3RjKw5rRSRu7Dg38GqXV/SMRalGXB0Wt38N1OrYtos6EDQO8koxAE05aMz6z3sWKQiUZ3ar444TKj86hXTdRT+snmHQ27ZWehX62ANVVGoC72QAld0e1K77muUb7q9L6dMlZfaDVXvyUe4PPibMho8qeBkwVAW07MbJ87FT2LFeuBJcj3e7Mama8JFiA+nzQw5MVM9mSH5RH9E,iv:xKk+JlDTF/S5fvwrf6t4A8wcOCdQIWE+iuuHMZKFnYY=,tag:a7ZqkqyacP94i5+hMIKLVA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTmYyVnIxWGpKbHliK0pE
            S0xnVCtWdFFHMmc2OFhaS3N5OUdRT1l5V0QwCmw1UFV1MDQrTUpDSEJ4NTBuTStW
            WHcvN2g5dzFFK0lUeWxKengxVHExVjAKLS0tIFJFeTl2VEE2cmhtcmlneVlKaWo1
            ejl0Tzl5VU4ybTFTVFBOeWJyYmIzNFkKLH8/x39t7P5Qy4LonIj/TEygvLHqXClI
            D3jh3PQccP7f+EN5BAG6gNTDPTshbN+1Fb/LORJvbSpRqIRmN/0yaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T08:11:59Z"
    mac: ENC[AES256_GCM,data:V6namO8JYP34s/LjXWiD05TeHA+Hg9wIVot7iHO/O7G5FRAzXiF6G0wHO0PJHkEAkmc+fwyFQLKr+hHsqPSc15zULH/CVjAvQsvxn6rFcgeXyzs5G8eFUoE3zoiwyeuW6nQsri6Omv3pHQkuv/cdv14XQPudGXbGXVdyZQah4tM=,iv:hujGrGfUMdr4MYhHsHAuplQ7OBiRLSL+BBGr9Z06Ju0=,tag:70vw+EzllQ7SZl9WhN5dkg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
