apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:UZ7xGNAt4Moesiozg5MIcEBwZPgsxXkE3Jm6K7ULr8Cb57278Y2bnuEkxEhQuDrxyb7db7m1QWBb56bO1GqJ77KEoIrndHBX6FvRpOeQo1HqUgh0n7sL1EFaKGM4XkeDvcGD1FGPPwcxNwF2OY2zwKbmG0+h2NOZFbaP+W9nPNdtr+42agT2cIEVICLOkJ+OoplfWX1+BK7Oxw/wd2wnSAifhCQ94hdb1BjmrmEYyN1O5qc+oR8e3Ca/Lyj4hTvUFMpwej+M5f60fyNwdzhKXLxZmkapWAtFaMjjENSccBnBJIJ8qESf3Gui7a3e+w3Pw5BPG5OE5j7+wGsdhKyeDAtHF5Lg9pm8u9F2KrrMpUJXU9VaZDRRsImNJkNOOa3d,iv:So4WjbzaWgu6fiYxWZwNJdbsTWLVYOi+gZ2HJaLJYss=,tag:ih9JIVTgP55UFlk2aFByWw==,type:str]
    identity.pub: ENC[AES256_GCM,data:otvo/GkFPXdGPsc7GYzNVByLWkE0Dtmc6WH+/bBGpW6QpA9suyCVFXHf4jNCGfM6XO0HbDFrgyY0RkDtw4rL48PtL3Jj7QxNWyv2SUAecEFUakOlcedMvbbDMlZm2nVzJhx4O2RB4s4tX3mnauLd5EwCfXLG5gLHLdUobj567z2RVF5mST4I1F1qOSkW5tNNXcGj57t6exuRHnxIKf2eVCWLapjC+QTrf0PdztG6GOnILpVrk/rzZN169JpCeYrtUlpI8K6lAPcZW3iTLw==,iv:ZKbu+uODuG3B8AY26ByploxT0GpD/QMPft/F2AwKtjM=,tag:JsuqywB7dw9FW7nnerBDFw==,type:str]
    known_hosts: ENC[AES256_GCM,data:HxSwJCQBLzNM3bUOLN5oXIf2BBRLLKVbMrnrXPZ55SSGE5rWkRAgtcIZ4RI0/rqbkknYnK5oT7iItCbXPoXPkvL8byk22DPu+o+PuVR/eKhxTiHIUPA7ElOxKIVFFPBGZiyp+1QzBMxKQViSNYX0FeetZ9QfSn2/859dat4Ry+w2c1EACr+W2mBT4LPV39eEX6dGjOBF1XoPJ2DiIgx3F4uy8tvByMuEphYe,iv:nXrX1Uk11NjMmxguLQ4ynlOgM3FHI8Up3nEARmDE1EY=,tag:EIvRE+DJyrsbN9lYuspweA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1l8cqhhkfeffu54h4l4q9lp8smn0w2drkmmznp7wshqg2xcdgne8q6fqwu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMHZvb0YyWnhuZ05hVXpM
            aS90MlVyeDhjNnFvZi9INWhWWFZYZkI5Y1ZFCmVHaVZiZGwrU1pKbDVjR3F3R3Bx
            L0ZvZ3FRRW0wUUFySXVyNFJ5eVhjUk0KLS0tIEhwNlZPVkR4NlpKTFdJZ1dxTk9G
            QmdpSkcySnhqZmZ0R0tYM2lBM29MSmcKuHp7BfuPeSR/QBxjOHFNOEGPaWSOHBX3
            /+LDUT6ELib5UJy/iwGeNCc7zJpRsfxpiOguYw6pWyhZVRyOtllRVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T20:53:14Z"
    mac: ENC[AES256_GCM,data:qioLE6kCZUBvLBelf/8QebcHVeaW+rtvF794FNcvzx+kXwm9WrLMJ51tAgeBJA1USqFMX2vqvriC651OAxaznLQgcPH2e5kS1EWyvYNH2tPn2YAErO1XPIyG3b0LqXzsGzE0czjwYXQlY+BEpuS1P1nsgVdgZLb/Ljkys7MJEwo=,iv:kkj2H9nKZX04YfkoyFXEhpA3n0bz2F7uCED9VUyke6w=,tag:RmqqIKPWKY6Q1iaQc6N06w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
