apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3s8DQP2XOybOagNA3TQxhdTh5DRuxUZjzWTJbYJcI74o0YOS5bxA0TH2wrUmySC+0gAfL5K8376Q1Wy9yE7SEQs6g2Dvy9tIOFV/RxfTjhZuCMHC392F8swdcEbOPZJ/7IZjj3uPNwsuTt+IV7JVOsPF/4rPha8XbGppUswb2g2yuD6v/3tzHlWh4cFMNa5P4q+8Ll7pk9kFDTq47WVXfNaTNxaLKxz8AKZaRqmP9nUBepXQ+SniIuTIseJBd05xXXABcwQFw1j6uK+A4h5KAm2StTZXwQYjpkcoDkK9nC+yr7hpYqH5+ElyAxw9cKVsjI8OUnfz2Z7+jvA8U95NEfqptaAjdvB/FyXmbp/etOJ8ZuKTA0mdj/ZcGG0UbXvz,iv:yXnbRinV7pmHhPamoBUeckC9OFNyHnpoxTajXlZEomA=,tag:mx4mGgyqA3RSHzucNZj2/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:z2067PngxckQ65ff0lj8QkBHDn1YpPapIwy5gSf7/rZv5hmenxA5paHJZ4PjDP3HkU1BvB+VAsAGM8lp1YPK1QjVvqVHzQDSnG1+1VU7zoJ8DQu8eTS95k/mqg2S9cLupXrjS979nxcJbjFchExQUcnz/IvVpkp1jJ7/ZkVE1YhoOvfK+mfaZ60qzTvLuijhNKgtU3nlArWF5hzPGBWOQIRUijRYc8/rF5TpLKAMBzkFp9jGWxPyl2yhvTXjnqK1TVkkuGXYWbLjVlNNPw==,iv:vBDeDNx040mqAPjCY+E2e4WR9DgccaR+GOc5AnEe5S8=,tag:PVlAIjyUT90W6KU+cJUf6w==,type:str]
    known_hosts: ENC[AES256_GCM,data:D0LYE+V0/kSt8C60lsbrIwI81sfsxbpOoVc8JlSBofKb2wHuRrqzSS9u5N+o0iyg0Ab0aPo7NgghVsUMzcAq6vRNfooA5nfQ6fbEcdf1HVQ9BYXUM3N5fiR+42IXvm8FpA4UYT9wuF7KN/NvOpgghVnR2xYuWW/hZs+lg6PwO+aGVSxQD+RpR2dSpJU+g4jWV2zPQc3mLf7YTbWVF41usJWDrYF0VhSkLZbZ,iv:tuQkgGMeUyvyHPVuQupCqgNCV6aizXox7QH0mvK9Fa4=,tag:YWXZLjuPb68lYapisIp25w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOFpsV1JKRzUxQWJ4NHRS
            SmZWdmlwNlRtRXBCSXo1bEpqb2pMTkZEeTNnCndNQUxCdkRJazhYOWZHUy9qNEpS
            T3grZmJkTHkyd0hGYzI4TmI4VnVsdGMKLS0tIEdtbUNRRWJYRmZPMGJ0cnd3Qk9S
            ZE5vTDhFMlVQVitoTTJXSnQrSDNMbVEKpOzy89JuIZuJKTi7Et3s4EmpWxW/cxVs
            KHqk7oOvoxfhY+mTL/bNyeDb40V0ydQZJYKrwP2iD3RvKXNm62w0dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T08:19:12Z"
    mac: ENC[AES256_GCM,data:rcRFGJicSuInOVTA4W7tKMdb78wIenawt3eP+3XDhG4BguepGVW97dS/qFXCO+K7tiPpzNC2l7mqS+ejhY3692DG/lyIQQZTkgR9z1q494fKmfgAyojVoeJwxqwhntuOp7puoBnJUOo33rgdP/Yatn0RpXQRJ/1YJZrPpGyfRy4=,iv:iNRGH1atl2TPP93XSQzNGmFmLzPbSc1RQQCq107o54o=,tag:OBADj+O31L7F0KbLvs23jw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
