apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:BlH635pUDpCcPgWAFKLcMQiHPWqtwBzV1JrHWnosAJT6fT52gjvcx1zOjzRaVZeMBFe4Jk7r+aEMJlQ0Be3G5zE3waADm96YhZnxL0LI6Xv2PwBh48M7esaDgea0nLLWYrMIqAPkjG3k2tPOIGbwT4z5/ERHqxH/0bPhkp9BT3WT6FTeCFPt5iKhIfT1v5r/ADNRiKNt9FRoEQMu+S1dwIBNy/s4ky7IZ8NJ5FX8sk/Gbuv6G5xx7opzxpjz7HpIiSLMfILrlcOEsPfaoZ9qlf3cDpGhkHnsJkA+eAP/22+yNfLrRMu2LTeuEKeqbVLAo8YvLxsIlldpqu8ktXlpKF1PdZSIPIP8VpxRvRmujEUDX5wDz5j8iDPmkTq6IaNj,iv:T/e4ZAVKIJ62IymqNyNA20dXpsBE8jMg63jSSTyIOF8=,tag:VxmV35DKAusgAHHrqQ9zyA==,type:str]
    identity.pub: ENC[AES256_GCM,data:hKpJ+r4vX/+ZBZSZ7/z3FgpjJVO+ralJCyqrfraZarTOsCnZSbBPMhN73GwN77lHA+pWq2iz+4Q2wrORz9uxZIY+hq7FJWJtgprJMM4S8IAb3kKhAzHOBDeqgHFzBhXwpLrnMxkcG1jodbVXYuPWcvEGZevlJzwnJSjzn3lFxkYsY0Xouk4qJU23LY1SWiub1sDuAIqzazkHsPcYGp9MQz9HniYNWmbpLOi6rAxcJvk5i1ZIeTuG+Ne6XRIOmglXXFtlNIUTsSvbOHVg8A==,iv:RdReCHXUNNwYaU1JJxqBhxtLr2+rnYdUzuSBcyF3GUs=,tag:2ksqwV/OaTEFCQSQI1kxSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:au0LilVFyKHlZ7B0jL2l1/5lz2Xn4/E/LhRs8F032UqED2fIkza/UZ11GIk9YvqgUrjqNl3jQN+/5OYJK9kJFtulHEF6F0KAIlSGHw8ZHbAuVwoJWIdXhqYkawLDlHZgCHPJNU/e9st2APtEVeIGqvHeB3SfpCo6d8oXBd1AyWmNoUdl1HYEbrqmMyF6VjzRNLBt9p9QUUUwZbAatyG3omJlVTgDODJi0qOp,iv:/w/igIflphJ81GTw/Ax+BpfqRQ+4/PmsaXxYAYxp4Yw=,tag:WP3m0mDH3Rd0fsTM82mDsQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWmtTOTVtdkJRTHNsN0kw
            SHNKSS9FRWs0OTQ1MlUxdndMY243ajk3RUFZCjJyZU5CWjhoK3dmVzQzUXlDMlQv
            cSt5SFpwbmtYMm45VTdlVGxrK3RERXcKLS0tIHpIdm9CZkxuK1dVQjdwRnh5MHBX
            SUVqRVVhU1pmaHBmODJRWmxPbnFpMzAK9aJGEeC4A2Qk3Qc1q0YpxidpZVAkGjJQ
            hF7YpfhixDhp9NlsmjeEO1VY8uG9vg2hxs3y31GNzskAuNxB1kyJMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T23:52:37Z"
    mac: ENC[AES256_GCM,data:RNxY4bClK/AIqeHrTQMJ3dj4pmiR0Dawet8K2N9hsYKof+ZvI5Lm9NOXGl/iLQIFXQ7RWCuAgVGyHt77UjSqG51VDG7FZNZzn7jH6TuwxboEe2b5NeXtX7qJ1aXRXfyn/KNlEkv6T1m9S68QtcugblfGhPxQ0i7SaTPSPbG1BvM=,iv:8udn9Ae5PbqansFBORMneyBJDrnuygIYsiySj7nx+QA=,tag:9BSC+54aLnqDXSj8VRa89A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
