apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:H/B6kOfubQXiCUV2xPZdwLvVznygXe5eS8AqywMwcBz4uM4SMLIKjgZOYmGdzvBPHrEx4D+tHuyyznAy4Jgnpsr/kOKIJtMQxJ8gLuh78Xo7hjelUW0/J/3G3J2Jo4XA3GUCkQkpuxruIq545BO1SwKCRtdldxlWJAf5BTmJMWedNxMR5+7lEQ4QeHM46BBJdQplbFNsEqRdFVB8+dVevkQOEWHKe9gdWjGueVJxdyuyzdt3R8g8ZOxAZVndH8/k6yVOENRzvsYrMCis4U4XE7cxP1seBO6g8h8qXDy2UuE/J/ig3lvJma3lX6NBC+b/ZCQJwqmMEZidoQE96VIcjVOnZoA9UlXf+oGz2fBLip1dJf6knGydijN/BBhstMeW,iv:1eqHnmdfRF7XOVagFM9fK/OJYE9M7c3PDiwm3IJpcbc=,tag:iAXDwCJI0qWj3usjsnZQdQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:WlOTk6xzTuRze/H6tTCnBAJKdImEUJ4aCeudg1kGIuK1PYA++2j1sxP9paK4yTjoAU1th44bbyrvNb2RecOnZnhGJcvWrRa3SNI76fJd31hRvLlSVplPsgJmfpIEw6rZjIudzRXXAommiXI4+fkqZeSVqB//ddsXiGxtiaueOkIOQUQcRLnbAAufr17HV7eGDyxCd67NEE16Jm+XCiaGNrsuDbI5h+BehyDxsK0l8jF02GYLHRmjv/qLcsAZMI3cewVnts8iOjYR6aCAeg==,iv:SouvIQWBOhzRqsNkwXOSISuwQe8gLjq9AHrAq8jLZ2c=,tag:MB5PLDJsoAQyH7LlmQYS4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:WibkblbiRq6qYWwFFxMPzhE6HAuNf7ZAUwlGovGfbkGrf+qNSeLQ1tWXHR6NPLUFo+Rk3JTafqkea9eDVQKkvmbv+sYhl9h5qixEKPDVCuR1v7nAc9iqTlyRRFPUAz4qzXdNBkTIH6R3lwbvWicgzmfY/PcIe9LuMURz56RyET1jR6BKuNI9FQ108oeHx2/R5zPBdxBguJW3UFiZCiKWd3Scjuynm5NCI6wZ,iv:2lHqa+LQQ2jFXXzJzE34gkB5WFklztc38VNIs7xXNpI=,tag:+aErI6R0UGteVMy/Du2M5g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXNFZEpuUmlMTlYydm1x
            ampxeE5VRGV1dXR1Y2M1SjNNV2NPNFd3S0ZzCjBvbWZrUG1kMGZlNXJWaDNEbDVu
            bG5nYTdVcGFPd0d4NEdpaVkzbXBJK2sKLS0tIDZocUU0NFFRM2NuTmdDZG9TeDNp
            RitrNUxHV3VMWTBlS09Hb0ZONnBnN1kKLUuF5gO9CFVzgmDlnNH4YvBMRVcj+SVK
            qHEFfFC/JVNernlrWlmJ3EkKwMGMBz37UKqCqhpQgAJ7LwVbHwvFsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T09:58:14Z"
    mac: ENC[AES256_GCM,data:ExNn7LCtQK7m0mxXi797UcXYlcjZ/VhvcSEO5T6/Hr785upu24VRfWYgyEvYjLi82m3+3Qy/svVj2QG1kg7TMJizc+m7r9pmQPzgSUJufq8dALXDMkfHglo7D1c8fpFwBi8vP/hnGKgHVYiqlzcxOYpfvsuVKUvsPRV/cGc1tbY=,iv:QieALJX87664Us4YfTdg4axa9nSWv5IVc5SyGs5b4jY=,tag:XhRid80pMFRABAJ+5IaMeA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
