apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KQSdAIH4KhjASyKgI4LJGIgcfRo3Rx0MmGVY8/2iN6G6pkBlTH3dl+cBVgX8Wtj3yw8wTO/YtRitZNZ/FJdEMjXDGv+Recbdexy4missZOPBjJR8GN1WBpAUp5wYmHdD0BOGA29+2vMEIQgJs39ElYWBHiqeXy7OENPtMkncR+/zqfW0Cqodrn2IsF2dtKLFBIzNnFgfvSS3h5zNEc56iMkmVVCyIS5WpY6oKP13FJZctmzMKvOcl466wWbVP1FajJzMYRBcs041I+lc/SI/IEW2qPtwIxKolz2QVzk6zqvWAoJPqJ5j7Uu/UVtxKN/qRZwELKQKeYCmzDfkJUkVJ6sHlINB4pFpgtQuqcVL5DnCJ7S+zDvXDqPlWl1W3f4c,iv:gU/k/R9j+BTSQH8n4fg88g08jeuM9DwHc00Fujudl0g=,tag:4Ko2NFeZOlEAsP6sGMNb6w==,type:str]
    identity.pub: ENC[AES256_GCM,data:0syDG4y3mN+/IrI3iblz1JrOHLH1ObyCcWnVAgfvnHvTwGR/wr8cR820lbjCfzmI37vigx+Dp5ZSmU3rYC+QeB0o41S0vlIBGAr/P8ArOtsXdvD+sRYiinFk9Rg5P3qyZn97iBYu9IXf9zFOpnmYJNtHUURwc6bVsOAh0okeagrrjSCNnT4sVPdpMamvDMNQRbRz0F+ECaQE7IAejaJSJ1WP6qjcE2RLXQ8IMimonygmv47XvLGc07DhOzg+9cX0gS2kenx5yhxIoqplbA==,iv:37YZg3VbOTzLfikVeTiwKgifg7xSbRSwtNu6Xh1Jw7w=,tag:lyzRRjRANzu6IvJkgcsG+w==,type:str]
    known_hosts: ENC[AES256_GCM,data:dP8EDCXIsx1NunN8ywr5GsKW8fn+gJBHQvehBAWxUk9hzuEYjWAqSqvRzlSiYapGPegQzHzd8UgzK/ZU6qvED88/r4fvuwk0QpxMIhTMeROmuNreDp/7P3Jd7UfGYXPFzw/SlMw9XXkCQQg98ZuF0i23KMVIVQp/35Y12QkQHiQzAlRyjtvtj1euwpiQOp9iCqcqZsyd4obdRONx6p0L2VSs28Itw5TZEdyq,iv:Fjz90u07eQOZWudv67UooPmjkZAKOUuCjcAuzS7KHRk=,tag:skZ/HXgL/sIhPq2EWbIb2A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV0xFM1l2dXFkZnh6V0Zn
            Q2lGd0FSYXFDL2JmaWQ3eEJjb1FzaHRYNUIwCkhRVnFyQlI2YmxDaEtjQ1JIWFFM
            ZjVnc2xoSWRTOXJUYjE3TlZOZ2NLQk0KLS0tIDI3QXJFdmlSN3Rzb2U2eGxwYnY4
            cVlVbjRMMkxkSlFLdEZkTFUvdmMyRm8KDEZGA6OoUkl9bK0fdjPjkoDDnBAcvy+q
            x669Nm6/Pb2+0zC7YDRhAMSTj2r0kd/dmJracnteTW1nu8dx6evEBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-30T21:39:55Z"
    mac: ENC[AES256_GCM,data:CNeB+/Y6MIU4EqAspQDGmdoFBVmML6O4+kXuzxDXHjKxkJJ42kiFyD8NER9p86qoDFY1F8m4mHSBo0XIwRo2vHvu8kST6gEvPZRqBgNsm3UONHWIcNfZ7sKjgae2AXLNnXOn/yd1gRDxICv+3hig3xMQFPmYCuggIvtoHxxCtaE=,iv:6BoIePaKdHsvm+COefuI+UX0BVjCakHWBde59TSdePo=,tag:i1LK+QNVUpEO4EBfarnoZw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
