apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Lc7Wy698NcljrXdAM8PNpvsaQTCG28fI+DhXW8Wx3BtgNHPLsLpK4CS9ijLUNF1dUzwA5b+n2vrE658mhypv/NT/2m0d/FIT5MzGDLLc0mgRkDZc29e3nGe9VCwAJ8pLx8lptVKTqIf0JzIHI0i6YYzI3MBb5bNi/3qel7FnBBGUDOjylMvwNuVy5XhC33wEGPwgNY8U5tWI1CRz3z9hhH6F56T/OZJ5XAWH77WXB5Y7pfaF1HbBDOGwfJxtyu1WslDG2JVyLwqPqvQxvY7nNBp0KVRK0Dw5m0gHdwTU62Q0xHwjbx7PMp0qThxrHhAHmlkkRYL7hDJsC27RRWSxgcWtmSAWC+osn+pJNJH05hT6omhLcCAk/tIcMw3qOugn,iv:fkiOXqsKMY9YY0bRUlni6MmRfDSaA+EbGoG2H8Phnm0=,tag:9s1+Hv+x1jDJ/j4r4//WaQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:+aYqfx6ez03eO0ESippLjCKx2mmBj+mKDQMDvyEYrujfRo+VzbUatgi6qC45lYvS3EbwYdneHYMfsJBVgRmpdtiR6hUBlJzjoHz7f31csrcngMXqTEAdkQuX5gj6/lpm6U0vPv6qqCPsHD11vNUptra6YF6g48BsdXfn9gE++x74P4fm6dNgCRxy2dwMSI+QQhYOpr4vajH+jqXVziIfZnRXg+AFsg+QgHAaWKJD20U/poT8Ny5sFsQ6Mn6BYXbqWT5MHF772CeZ0G/AQw==,iv:+z6InIP8s7xq5EnvvVy7UKCuANl98Cn3sISDCPRLZco=,tag:Zwm1aA8GCM2spXP/cRm8vQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:oUQIBczts3p3MWiIOYnO+v0EnBHUbvfVuS0OVMJMsn9kJHeXIUJQ8qX+YE1AnKuAZFZRsElsIvYMjBtqLCZd2p/4ophn8YEnaeNZAAK6BEQ+yMMAenCZiDkSD4YuwprlAo/Xb3M3xwMrxBLyTix5PVhj48/u6S8re0p8DZm/zcSz+9lLHYdwMH4cAnH4kyTerLd5DIqw65ZdqQa6bLTfJGEbeNc/aldqHxXD,iv:iNK2nqk3HdHxZnmlDFADGqhl+s57BvtCXrhmKB04F3s=,tag:HK50eFPABCsjJ/Pkbk0Ftg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOG9mckNBQUt4NGh0dWw3
            QW9jb0Jnbnh5RThleEx1NWMwZGhxVnMwZFUwCnlJUXdKbVU0TXI5VnlxSkpIa01w
            ampuaEdobHYraXV4Ti95NWRRZGcyN28KLS0tIFZocG50b1BxbGgrY2VSUVVQSkNm
            SWlTMGJ0d0ZnNWhMRVZKZDNkUlBiOUEKEfIO7w3TAJsCXz19tAzslU7d78U8hyIB
            GJF3kGPg5GteevQ2z4CaFIL2ly41U/fh5CwhkapISY49zB9xewTxWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T19:06:38Z"
    mac: ENC[AES256_GCM,data:cEN1mA76zezikf1XnoqlXc9qBVutO1gPz+P9Y+4geBLBUm7gX0k/MJR66h1Gqm84ORiz0TyWudTmT7iX26ir+jeEG3JpRYsjPwlxOAXntlbMsO9XCX6Yr1pFvBMyu5eLtH+WH/DZV8r/bXQLrHROlY4GIZflZLHowaSVx6l4hOI=,iv:iZGnPNYu51RhPGHPopCQ8J2SDbabZBggqGJ/egdyaW8=,tag:dI5IEOAAtddQ/xQ/kMmNbA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
