apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZbBsnpv4C1X71O57zFf4CcQLYLGO8Yzf3byx9ylMRN9j8asVHfGjCN6Y3eqCIqYGxPM/7uzxUBCUuk1hYj7VL+0pU/ljWkxlQBiGuIQJnIVjJW9MGKffv1szP+lmIaCJVE+0uytUlHQClMLBTdpcIDtWMf9KzQAn+nm3u779L4T4+N4+XqnFYH13Vd+RNToOXN7eErzBTQg3P284kp7gAYgTfqo3q03qKoq+49wHSF70BrW9y3CpJ9PxOBeeaTunSRW680GfHYN2NW4EQ0hAMterpb0/DRFOeMIhHNxQMrSvocL4MR8R76tCLiFQNimTkBrbS1jw9mrNugHYPy4Ga3t6fVAp/4+ve9+ZeTKkwbv75PH3+SyWsFoYfF68i/5I,iv:uj3wZ+Jzfob/OQpUKZOJvKK1VaLGca/btmqCIjgb+zM=,tag:ekQU8bR/fPgVy+qXsHu0vQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:1FNz+6mEZZDb2jp4jTbL3KqQ1fBC3YUWQ3IKjLYMbDjSAqpW+Zqu5XcD48qRWsKD7a1np5ph+c/OQTHojYXN97gb3AO9r87iSL+22vInhoCAoHx/KQYMszh/SdHmNQHA6e9ogAqvE9L6FiB2NH2uatBLKsSG/v/Uu1GMH4wo+O2NllrzOSuTWnIj/uMaNHt7528Un60cdw5kbv3HA5mJigUUwpZeqa6W7jGr1sQNKV/7EyJKBTIC7ZrX5Owv2GVO1lZ0TDwJp7HX913/pA==,iv:CAz9Bv/PfPdWSO/H7Ywpc1ZzZAccCARwQgM3aDgIa54=,tag:UHWv/5wsxZX83Gb8jha1ag==,type:str]
    known_hosts: ENC[AES256_GCM,data:uLj5itAJoZOhUocEan9TBBZRRNEn+uZrhJPhpfAi1U9dE/9U5WkfmmyfKduFgayOZbWloznB1lKkHP8RO15IjM9PFHYvrULAWDgwjkPpDih6J+NuQTUbbZzuC58+dr90FJV4ODSfQ0IEaA8fCuj743XBkqzG1ZjWQbvg8xP976cJxDZoKJOjEirSm2qCCEW2GH2zaJMz4uoyiClq7tDU1xXKNurOXPGpnYsW,iv:a2+NLqq9NSVnow/oBJS3g8J/pQ8lDgRPA4vZwq0TjzY=,tag:NTDT3M4S+EXnDLJ28itusw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHc3NsRVV0akpEQnlpWEpn
            b1A0WExzdFExR3F0MjFIa1ptTFkycERyTUMwCjV6Vm8wc0VyaTNSalJFelJrb2Zq
            bStZSGhTWVFMVHVvT2xjRzZNOFBCZjAKLS0tIE5tUEVXMmZYMFgya0lldFNKNHlC
            ZGptK3FRanY0V2lpZUc3d0ErLzNRV0EKfD1ojc9FMA2CqkUbSkEfw6S3xxq1QjhL
            FWksDPpeysxi4aLLyEe7wqxGCWyU6ueoIMH+rtWCpTRRdcY3d+g5Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-29T19:50:53Z"
    mac: ENC[AES256_GCM,data:B1D20xxFXIWQAyRokNpoYV1fnMvEKSEthA3bK//B4WrwFAcBtdPk9fs+loGBYdJ3o73qrDtF7S3l7UlTDKSMS9U2olMbsYvW2suvZ+tV7RWEm7oqVIn/M0FV7Y2FwaDcPMFvD5v8VqhS3poRgWOIWMuSYUkZUUNRkm/1BqESR/k=,iv:9FomSgqTCYCduwbwG+rMaWIpppdojyboGrtMJRNh8qQ=,tag:V+FEXSprPFe7IRrLbzz+nw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
