apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Kb49EswsBOVv/qQnDDbUyLCcoAuFtCezVU+iKPGpB1kY1S/8ls5iX0XZN+SBouZykSfTBlpD1e29xgxdNTpTqvFpGavgyYIJVvhdBh4BfqZnO+t8eoIxmzdX0KLGglWILJUrn1Eg/JPXs8f7F5ZA0H39zB7fGFsxOfrT3SUjk0HRu+OnOBMXyZdn3AVERhB/uT45I+I7whaDzzG4XZX7O4qkIXd9FVb0Rg9jO4+UjGULd1NjfMjHkUnJNU+NniLOunGkOvS1bC9yMScabj4omlvPGZmFTt8/0m0TMsUoy7TBfDmVP8324kgNkOO+nGTnabeu5QU/S7xKDLee4cKQXWcZs5WyCxqFENDJG7ZeNfkk43EJeVKiFMy0j6ZUJ6MG,iv:YUjV2AI18Q5z+zcjSITCb/r0V9Ibd4X/hAJSI80mrgs=,tag:RrzsIebJdY7w+gTVBkRDKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:LSeyK7Gzo+1zWE1ZFPRgnNSj6GWRdg8Kiv36yXAaC5SKuBxu+B4yK3co1/NiArkh4NG0LRVKm9WngYTGaTlREt/vQrVWNo5Pl1C/o95BKdcwdI7GhE2PoENRgBGcsQ1LABOc+dmDbIkHRJv3QglBQfZp7UNqANrYnHBu0MaeOnegmhIqE7p2qCTRbQe4j39t3Tqc80251ELKx8vQW9I5ewYi3Nils1mIcvUz0H64gtvUHTaqRFiKTA3xKr0nO9wqbMxWtHcaxoCc5wFdIA==,iv:h1dpFkMEfcbvdJj3/NAIUuciL+XL+ApBsqcaW9VVMno=,tag:9hDnzidoxJ30n/0ffXs4Pw==,type:str]
    known_hosts: ENC[AES256_GCM,data:vEyEc1Y22B9AOHJfGh56hoO2EbpClbz+ugWCWrtRscWgRc49eadGpIkELwH+4DWgQpFhxpPfCN96L+biZgc0PhOju3OPK8bsDqmpp4qv1rV8YQaXXIwOj6JfhLNQLqajv+FkBLdM0PHjDiRitpzjC55rMPik6KGbiiYhcsGLZ8+MpsMDy7g/Jk+lxwF6TVP2RYZKOuED2bBDFZDcRvqWp+m31qJad9ZX4Wkt,iv:s9GBwwsAFN5H+npLHTpjeJQ2nEDql8Mu8DySA7CAElU=,tag:cxcF4rWHA2syKQMs/7herQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTFlySlBBUGRyb3FsZGZM
            T09BS0psNlNOQXg0WkE4VnYrRlA4UXBCRlFBCmRnclZKYnlSZVo2NnJDeHVVaEdR
            M1BmdS9KMjYydVlEbHFGcDlRQVJPK1UKLS0tIFZEL1Q1NWlPazVpT09mczMwT0Vq
            TTg3Rno4Mzg1Q0RrOUFwSVc1eVQ0RDgKyxop9A7KUhGbMoE/x4oV3lxwQh/EyQOw
            2bcVLVb5w94mEPXQ9hBXrZugeE64X/mfMcT/ljIZvp3ewGMMoZa8fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T20:36:36Z"
    mac: ENC[AES256_GCM,data:XuxeGl+k2KiJtdrEiYGzgLfn9YRJlxt11qXhv0n4kbbPS7xMUvx8JELTv9AdfwbpzPRTI93lCV5jG6Z/fYOVoeHUYFGxVoPGQyoKl9amXvBOHF6Vw9+QcM4uqp8aK1O78ilbhhuD3j2rtGjA+asBh9zT/ZpBZEjiSc/8E0mWKJI=,iv:c+BjSCh0w1Zj+uG2gxeYQqBgRrZEIu6DhGkyqFaHuPQ=,tag:D7PiC283sgefpxygPah8eQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
