apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:fhd1vWTF/MyEUaBItYYhU8IEMfQM/vuYY/vXDrmLkqiUUoc3egJjqjYlXuEwc4qTNpu91jChu8hjq8CRDxLiDi9fs9iWlFY1UQXC/XwcVQ6N8f7bk9ZR0nkuWB2rto+5nq/pyTSkNaee9ZpUApReW6NIg7jGdIFC6wtp0gE6HGc2gvSmzJ452XqmoNoFjzoBKIKFc+3J/31nMtY6bxDM7eSs855+7g4kk9ZdWBST2A/k+ZyO8UGzYVxBe7+0iV1wmzhkazflCh9OYrhrp4nYo+j2xdH7rHStTUgws3fGYT82DGwomb5tqU25bMQ3SahbIwtZgBC436zuxxZoNBO0j1invQRO71+wXxmO8/ohDx9Chhd1PMrCoZJo0lvWg4uu,iv:OFUn2TwqoUEsmqaNirx6pxrarvLlOuv1PcZ4uGmWe18=,tag:xpYQ7eqvhiUTpuaVuyHm3A==,type:str]
    identity.pub: ENC[AES256_GCM,data:z/20sLRf31TtoeFGr+PKjNxx9/FbiENYeYj38cpYsgLFDnBU1FukE1u5JFcx6erduM6A5qT5tiWjqzZruhPr8FFsdx5fJghh2Baab/uf2qHK39GHEkpAcKZoUNkkEAhYX+30gmwOc0d6ngTqn/ehg8bDZq1gLtqqodD6j8jgaDJ9BCX0fQuYv09bG8jnFTIaf5fHH5/KcQofAvniRXCokBkembNh7IYITI9s3Dz+ScTpDDGnDY5EiDiubJViGF4ZUkceebAV75U0DMcn/w==,iv:Gp1uJ1MY+tE4VEMVvCR4cEQ5vj8pOSDel1c9XUweGJE=,tag:A1S/aUtWYnGeb1G/6yv0lg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4RUETb46WJXxPbEZtsmQwdDgQx4j0C4pox7taFG0a8uC9vm4ERsy2ZhZ3iEGImmbfuYCHCVY76XcjKcALE/OVZVaFkorG6rmdRcOp6mCgh6RWgq2cZWES6y/o0YT5bbdDiPq+tawqba7mUGOZPYDrX0KFajERPWFfE5bbTGa9b3vPy8eqZ8BtlFY6qXVoMVl8ItFlhPDYmLySVuUDJLmqcBUUDvCPjXLHmHR,iv:0l9YPq9ngppO1qIwYHavpcvMbhVA/aOUjxV7hja2YnI=,tag:TE3/j+zzrlOX2mq4kRw32g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOXZ1aGNwMDJzaFNkMXNy
            SVQ3T3hvNGRYZXNPU285RG9ZaG9Fbmx6UGxRCkx6M2tEUUFUd3dzQXNKUWZaS1gy
            UG96MlE0N3J2NGh4YmZDdklaM3phSDQKLS0tIE5GUlpXQUk5US95WmhIKzFIbEh6
            LzFaVUJJVHY5bHZrbS9tN05OK294Yk0K+8PiP3ZE3bhn2yiIOL8lkx/6N+Ol7G0Q
            UeYsws18aPd7RX9rKEpSyHPxd0GVp3SRuFYG3KCyI7vsUeSO3lboJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T15:03:27Z"
    mac: ENC[AES256_GCM,data:T27AviZC3azAKRSAq4NJ2stuP7d7G/2XumstGZuRjCgQ+J9DExZYEeTETpWF78OLElXlH/YbXzm4mZldrbDdMUib+Lx0GxBUB7W2FAr2tcDgJY3VpZVToL+CHrmaM+EKB/w63F7hQ58ATi+BTCNG04JYVbJjAuemrbMYAMmro/s=,iv:XeeoUrCNwE/pwgo0s0XaKQtgditOZfJLFNhJ8U5v9Dg=,tag:vN3Fw4VYC8npfSx5vBX1wA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
