apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VeCIHuzwhQsoxg0Orm7lHUO37Cp0ETrv+12CM0h+v1NulHfL15QhX0neFiwYnOq2k7LAxDxJcYor9rijunN0iMv5Hu1X4honYIQ1Q4tApCqT0p80huiLH/s1Lm6ZVkw+9YBAUbDJH3rbJcM6UjAW3RWA/BO3adVzvKE/Gyon7XXjfZbq3q0gdxQUpn6tklj08OIF1qdUaZPec7yziHJLHwZncRFCRUAJKd5SD3J8hYyTmFFV4t8B4WdiqkWLRsjIAY832JVCH6BBBU2nX1dn0qovDnt73nvw1y6LDTr09zpowCtiMJs16lh6Bwu6V3GdfpWjBBiKFHnkgNPmVdORccXvFGDktKytcz0qrjvVp401f9Xy1RfZDTWiXrsQ14dO,iv:Jf5W7bvIhw8bRhN0f+8BnJBYAr0DM3Brg3CC5ANClXk=,tag:DkE0H9/x4NUnv6UcwJjCCQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:ryVUcMSc3mXcvPMDNCrhPcm/5hPg6vLgyIT4fz7lLnh2zgRYc5HX8TNd2PoxPlVoOXuMZAl+R8tlgFSpF9vQl3vNGED4J+PZ8+hFU6RtmRgscs4ac9IzS6OZEpAmPRg3Hg32hRmOe2GKWO00qIQzU4ByLCuhLb8ILXxqg7fIsTqEiSS3XxL1WUswwdcZ7Fjtj7brzo3FP7/div/vK+87xO8rODIhjn+lSdIA5d4uCYHrXIk+GhyEm43eCHLyfJIDCb74zta9oNB5EBtrHA==,iv:cEhdof7vTzi/O/GOz3WdGAgXUzEgiujudpUMQCxevG0=,tag:A65ZMTZYpAoA0/+OjEe2Fw==,type:str]
    known_hosts: ENC[AES256_GCM,data:yRI3Ab+y75eGZtxXQnCnvx3L85Hi7p6CSw1NqGvYQbAgokVMqzVN0e+qm6Nxgog1VoWGDdVd6+1iZwf5bE63C7OqW/gxq0gVgO972FaGqlGizZxmSFsXpVrtWRDbqkIToDiIqDhwZHZb2A9BZJQrdf1h6TKw3w4ZqD5dyxK0oYFARToxsQNmIAYbzv/bi5FyVTtpz8MudNF7MHvV65ZII0M3ZmWhggCvHx0w,iv:W4i9mCcYiF4yLF0J10QiOZ9JU5o6LVxEBV07CJzVO7s=,tag:NdhhSzHqzutorfQ8FhRl5Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaGVldXNIbWpBM0lYVXVl
            T1VMK1F3cGpNdElKSlBjelp0d3VhbzRzOUZZCjVyUU1SQ1ZCdjErQVFOeEhKOTgy
            d2dydEUwa25GdFVZSThLQXZPVmpwWDgKLS0tIEgyQy9SZW84L2lwZThZdmM4SzZ5
            TUtCelVGOU94blNkYlpoeVVNSWYyb2sKXzHLdZoVerjspunNQ171jhSw2nzo5+U5
            KE8LU0r0dGSs+0NTeoJg9tSCLqXCTYJMq/71SujZp3tGlyJCdd4Omw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T18:44:30Z"
    mac: ENC[AES256_GCM,data:hqZdIXE9dPchl2U2n4WgpwOO4dRYGzHB8FvBBUXP5/40a8mGixtFabR2NKyKIRfRJup0orGRsVSM4ISAy+dPfcW3LGNp80wXYyxrYco/3KKlSKMpeP6oKOZLp/IC/Kpsx6U3RfXWFSr4Ki07lidGTr2Nc6uhOSIx7fjsld2Ws0k=,iv:6Cm34I3mufqpSxiJsgOGSPcILhLhID/AGJXQTc4Ddfo=,tag:GXsFuiwbnHfQMgL6nTouxw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
