apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FwH82MO9RIMXApU5exoSJdaeMdMve4m8rE2MhyCjCU6u5aYAQuvTKGhveHVzOIzX7Pnu+8GTS+EobviGbXTOSb+TwfKlhqzjXl8HlOMUW9hySVZ4NEkDGF5s89HucjNwnjc/mE+AB35tpYS+LfTzhU5okArNH8tIDU5sGsHyRj8ckAkg0EiE7yLS9Ayv+sf99fUaSK4sDuiu++Cc6IoRm5E5zbXg7ZOerZiOOgWoYCZGdbsQNU2yllFQ0NyntwLnuapXGyh1sgqYdN/XAq7ik0OVGdiPh2vFY6BugxNMu256zWDBG51miDHMcI1nktYrdnnHf21cErgeRO2F8TgicadDtKynyG8ncA9XgK/HkAG3mEcBhqan7h681cOB26+7,iv:ntkEefrX1SFDYjWRAt6LQ6EOoEoYhBzVCnqB3U3IHPQ=,tag:kbmJttcpwuwGcbHUts/8TA==,type:str]
    identity.pub: ENC[AES256_GCM,data:JZdF2d5UMF1O/qSEcSnWSiyQtsOiF2tUu+m6d/96WXsawYAiQNVWtssKKgH12KebIR6hQ3cVz0XsxQKxPixjRdB+BjcF73TER1WIgL8rKC0KjIY0k0IIEUY4vC6Oijm1VUKkWC5ikLxEq33i3KEb5RDZxZb28Chvn5QhURkvsoY7UmR9eYkApjHfNo0944QfP3eiIEam7RmdIEcUj0pTMl8V67xsxcDw1H2yKW28PWAJsyLcn77WTMVTHnb8AvkzDxkfRpKc6do0TteiXA==,iv:rOa3aCdQb1/SV0Sf3Bex5eiJXZP61MGHBVKmPm08AIY=,tag:qQqkNOhdSuOAHX3NqmMnSQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VnztPU6nI2BwtQN+9THZhxhxfqyW+URisV/miTZyYLXcxAWsCtSXC4PrD5G1k0eDb92/+oK0fSIWNhyiG4UEErw2ENaakK9I38xwqj18haRhr3RpHDAu7Qy9BuaV2W6sfeSxo5da6wosP4PeE61cFQelHc3yOPYt4tLVxG7yaFHuUpTpsyv1cOC0Ba8UfoP6OyybnlLBu+D7Isrvnih3SDg875FzQG38oJia,iv:uK9pKdsmu/P+PmUOCVfWI+OXwBhNsFGSSdtrF9ZEX6g=,tag:I+uxOOvKVFIC7c2UMOZ0EQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1l8cqhhkfeffu54h4l4q9lp8smn0w2drkmmznp7wshqg2xcdgne8q6fqwu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sm5YdWI3UlFuR1NvVXpy
            ZEpaa05zUWxhbVRsTnA4RWtZOEpSZEErbmdJCjcyR3RWMkp1TzV2T3lFRWNWV3M3
            eEdwdzg5bDFobnpJL3hqM09Db0dka2cKLS0tIENtTklMWkQwS01tTFBKQUhWUFlO
            STU1ejlyc09rcktoOVh2alJnYlVINnMKvyMH/Kq14slVmPusx3Tt8Vn6trOg9HPG
            fPlbbf/rBJ0ZfnJlSaVVT57rm7ZmWcqfY7WhNC8Wf+KlisH1HqQxnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T20:39:34Z"
    mac: ENC[AES256_GCM,data:q03w2s2i/N7aHmq8JemFwl29CmLoX6f3v9EbNx4OuksjbYyw3s5rn3F1AcBefauU8L2PSi5RH2M1UfznUfYM0xYS7x5Rwq0Req5bIwNOChpqTrGJIqruQyOv/yZnReBDUvgUWs8ET0EvnYJrn+uoQM7en+zrbK016WvCcGwl3QU=,iv:266MsOP78MSsX229g1wAqKArFDqFKSZ/ENWRm0uqzIY=,tag:PORVJwrNiuB8ZxCxeyxlaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
