apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:prukwUXzFVBxXvelLtDFRgqXrWwXnrsLnXwa0pyWB1AOTX/sNyXo0bRokZYJPN94FDeOb5AhRLh2KGiNCD3fwT6NG8IusQ5wr1nJgj8MTqzcpYtLH6KGLmV3UFa3m9SA+3YVpq5etgW5WhVXbkdvoF6uioCnxudTQApOMGv+Oq3xCnH0s/Wp9RY6h/2mVCGkOHs1SVyGrEfAO0sw2aUQf8omFy6bLuuHZv/DtggmdM9UBBFkrQM0acek0jE55Wy7hM8W+OuWsPAKWR0WCE8LGgNIB8umtlKyXxENS0Neh3eNryXNZAjDU9CrplaZ9yXeftTRW7se6RddIb2vRe27tO/R7eJsZ+CXTKySD7aCyIGLO2XXGefPujPznGIIcEVF,iv:XFn1AZDE1buZnTO9gKZ0pRursYXHAC4c0yglhQV6RFs=,tag:fKKIHOl7iKRG1t19RPiGZQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:oc/joLcLkWzkwU/CQBYRfJoEaemA7HyOzl8hfCFFpRJIFre27lzKfKtxpmdW/1rS2tz6ZR9ZDmXfSmOwg/iaY1K+4m2gKotnGEl6IefXft2aMGpOCo8pNYCvz/3c52Vya1yUltezxrbo9a5K24d6NF8kjJH8p7QcHhjR3eH4wGP695RyFQ3Y8G1FKrbeEXVrvo7/z2/hpDH3qTSYD6qjhkBmEWmTNps1PJYByYyvGXeotZFprCWmlHdA/u/FMTDuK7aPyZbvzjPf74Lb2g==,iv:yT0vPqMsQQKUSHyXy64CmnLdfvXAUSa/DM3aR3+sCXs=,tag:B3onshwiLz6+yk+Ok/1VNg==,type:str]
    known_hosts: ENC[AES256_GCM,data:XwJakaUK94b8vtYdtRJGts5U5SQp7avCjsIqzr1DA/EveTjlQsxYzL1oQoZwloF/1SqO5Eu7rPzKSNe/g/azleYguN6Cb02U/odWzzAjUEw54Pho0cz0M4kG2sEGef2KUcXOB816MDnHKgo5BGVErNBUHJ6igGVYnmxDMyvHL6AIcgHBnN29aUK09j40Cf8m1KDaObxf9ubOgkKPyN8q0ipf2Z6KoSuH0dn+,iv:mus796NJhWdjzMaToMOXupAN7HYVC+JiTOIs9vslvIQ=,tag:6tJzV7mk0yMzUPttJdOeVg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTzQ1N2RiKzc2eWdtejVq
            SmJWUkFWODhUVFVja1Y3SUwxS0E5Skd4VUJZCmpQcDNoSnJkVzd6TTlhNVVNTHFE
            VkppSmp6VGJ2dGwxcU1IaVBJRGJEQXMKLS0tIGRMSlF3TXJtMTlWa0dTV2pkOG8z
            VUZZa3RnYnZPNmJ0cytWUXdzRFA4d1EK4taM6W20o9lzfpMclD6r1bk6Dz5Nro+k
            yy35zfxN/CHWBmKpxkzw8pnMUore7lNYfOnqtOl1bDwoyImv9EcoIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-12T17:59:30Z"
    mac: ENC[AES256_GCM,data:TXFPuQsLd7b/89DaZxczEVpduMRNAqIsQBTGxtrxUTw8F82CQN1BWckDvNA1VgOtmr4dRlWYBXtJgRPWXatEZ9etzwqAR8C9p46VLvZ/ZLa+AUa2AAgblAqGgpiOK7TrdBulIcXABjjd1r8Qus4Xj1+SifcQovhc76WaOdugyR8=,iv:Z1rLoHnO9Yk5IEZL65LaO7a+oZhrfx158+2Qx5e7AZQ=,tag:KHqu7br9jqlS3Kt2lyfi8Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
