apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Et6YgqpHAj+kJAvNgwMDGXkqEjr7a6d7gBMNSbXdHt07xN+0bPdbJWpvk/kiXVvwwmGqT5LOwhNG9SJyO2egPFWPBxrIB/XnmryyNjFTJ7jc8GgKBxWB1ajYWbHkayfxpW29S9TpoE84THRUVGyA/adfNrdnZCInOCt4HD28mnSeJW0qX+FeHlIB6bBP33gc7Vulp1UkBT1yjyDOWb7pg3KRXBie5Eo/w3Q9APHskDocnZwY6EEB6T2eCBMvIIA3L4fkCrqAU5GOWqq88xHEKAqwWyVOad644EnE6JM3fxEo5c6sCDNoU2IAyoItZIgd01og0xoX6DNRuOl3bLcfA1sPbMpgIh3kitL2fGxipcTPx4gH/Bn+KuNh6uE1Y3Ff,iv:iN+qvebTNWUaj5M8+iXaIeBK0+jkrYPsLRr86JuqZXM=,tag:ybq1NUtLBBFEN2eQyMoL3Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:9HxLVhTSUKl7+GSHdFwnvHoK3Ti2CKgx1pUpUmweB1WwNTz8tEeYaHHGxFkwuuFE4I+gPmd4QwEUgvMPX5GPRXDv+0Z37YguWESJZWTWOAOXl+LYUUOptmodohQXD4jq/U/UArXmpCx1w4FfdG7xwkZ041KF3DCYiUuHXdq52VW7hBk2TjOtiCGNwfWOBnXMPlrp9J/p+PzK5aRHQOaeY63Kw7Zq9EhTgMrHrJchghs6SNBJtrdMOhY1Pz4xFjMz3fwN3JQOE3ufOque5g==,iv:Kf5DR7GHATuiog4uNS3+IxljMmS2XNr/n728eeObPTc=,tag:iokGAUSGTCOJvg8CDZKwog==,type:str]
    known_hosts: ENC[AES256_GCM,data:2Nj7cM5QTzA3HxPtGXRXD59d03Z56h2pVcvj+DJhU6GH0Wq2pYcm7EF+bgX3fKiW7xqQ6uqTeUFuaC2mnfG/Lp5afX9m4fKpWyn4h0mPWuNCPIFjJa7mGb/70NjbbkTeLSLAOwVrE30fJVaoHHhYbOetV4oXxzuSfLgl9wpumy8x45PV2S5L6UFpro8H/Q76K1ywSkzXDmEfFU0Z5+ovT7zqDsvcWxiNjznc,iv:JhZKiJetAEm0y1Xip2+sJguCF8YH+OhbDQhsjGUFtLM=,tag:9PtQnenUfnu6/YZi0FMH5g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFBEcVRZSFBLT1pVZVd5
            UXFxQVZpcml5NzcrcEN3YSttMVNWanloUFc4Cmk3dG9KU29QYzNiUjA2OUxuT3Rw
            QXdDa1kxZDlRamNFNTZvdEo3aEw1NTAKLS0tIG5RcUFYTkNWdHE4WGREeHpiTFhs
            REl6enJKZVRkOWFLd0FKYlJPZnpOSW8K9PMSlJyusD9tPIYWFwFgI6Dtp6REPvsP
            WpmpyzCUNRhQQnNXMKcFr1opljBYnRIk9cDgUN9AfB/WJvcmPgfchw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T09:43:31Z"
    mac: ENC[AES256_GCM,data:NKdmalQc3fpdRzb9+NIf/52i8E4xJP6c4WLx1AIuPRAOtBvF3IM8ngRXZBoBfFM3m1OOIPnTHljAxs/CqFZ78JWGe+/5LJmovlrNbrQ+Z+Xx6VhwGSQLpwxmFhJER26J+7AhCihcHCZvVfLw9i3rSTTHgNlAsT8ZdFNgiZazDeo=,iv:XBwbCiJyZmFbkvSI43y70k5aHM2nSqJIXLYtUeHfo9g=,tag:rzQWdxOfwnTEHqEAH1eczg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
