apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RzkN/ecDXxjozIdH9oC9zy4tybBq81dwg0jlHGVSl+78TKNEbcbtO3oIzD1NehZKJS81Pnn4j4lbIU2RizMz2UD3CuizohEF4Tpz9tPOW7RkjRYA0GruQ19x5ufRY5VSeHaTS99rY7eAgYcpDuxQQvUlrfuHOMhpWO30ndvAlbT0YxqQsdENT4cYBuHsZeloLpgeKnDVAPjjL/gCwWofyvc6JKd3RZSZUarW/uqyctSQWnTJRJnrVxmujzjlGRJxR9ujiXuehe9fylraRB7pVNzlLL/7m1LjSsvxQYrpKbtBikYUlsmKCsYjCAaIQrYMFAR3b72Ek4/XtLbOjtFLZjkqYZVIRvqHekKtmzNIakvlGPjSRjDZNc0PczDKeob1,iv:RupBzovnohmyzsBTUo3N/PO4LSd1lR74MLgZrSPK/64=,tag:XLeEpoiO0z7Kl9VyTuhEJA==,type:str]
    identity.pub: ENC[AES256_GCM,data:4Qh9iNOVLA5Bw3wDkzo6VXjgYm6jK2+Ps+Du+iPYybmoJt2LeTncsOk5d+lNX6e7Nv4HHmIwWu86p4WeIhF+teHkodm4JjeKwSMpTJ2eW6/y0pHcFG8nIPVT9x15pIJVKJ7LeGR2+iSly0w/oem2+RldqkUnE0rZ67bPInM+smZuM8QrbhMmTk6QL0tlOyuA4nyny7+VkRYtmGAzDLmKvLnFVoHDknE5vVmG/kKgRH3VR303ESVj60zfjxpgqOkeltF7raykGMlTyIlOaA==,iv:FCJukGFPkdu1QF+OkMee/HU1N8sgVDR1rAbkmkzyKps=,tag:L5OgaePpEzO3ba02rxLoZw==,type:str]
    known_hosts: ENC[AES256_GCM,data:tya7Bkn5dmC8YoSdHyzN2N2vmOF7xAe3HVh3pOjawRwlDNQ93K2KTKjEgeLJqC7IajF6hWfQ1bHOExgae+P/m/8d1kr3zT+MAIZvNn/WT+PfTUWKErQzfbBVycJ3D/0TwGs3AfVjeTrkHljMJSgCtqx8mCRdj7AyUty84eaKpqGT5lLC7WF0tSBiwFrdFlzJYNOGX7jsNjmC1t04Uv7638x6SaHTtDr2W4bp,iv:cBkjWpp37Cl0y9IUHeA91Y8je5ZXp9BmGh3vW5snaXI=,tag:YpZ3hRoT9LvFfpJi7WNk1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbnl6VUVuYlY2R01qS3Bt
            OUdBRnBZTStwRHorTGxTRUs0ZksyTDVNVjFRCnJ2aG14d09oZUZmdTZQYlhmb1RQ
            T3Nmc08xUzltYUVRRDJWSUVkb0xUNmMKLS0tIENGR05LMEoyQ202VzBLUlhZK1h3
            RnhZa1Y4UHo1bXYrMll5Wm1XaU0vU28K+rtdCIX8PXACTZmfNNKcPLV4tMx1r8Tp
            LMLi+dFaoIaxb4tYXgKJY/yj0dvmSXSRG/bC5vimk7VftKLBJdlhVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T18:46:35Z"
    mac: ENC[AES256_GCM,data:vC597fYHKeFSpVIcF/OfNdl7scROrY+dl5e9dMb3SVcVoPn29MVkGDZwpR0B02tbfQjVTrlTlxMNQvqmse+wDDUO4yOEa2YfLJY+DAdqgWZOFobSDqOVDpWl+Unz/7SSszEE7XztRJGU1IJ4DZFVv4nWlQHj0wXt3+Yv7p0y/E4=,iv:1uQhcwdZtCy0ju0U25YHNmhv0fp7+H4yNL/fZxGOjI0=,tag:HMU9yDVYuvbwRchzLbr3ow==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
