apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uMilM3LNEanfnecnV2NJ4RDC4rsIb412cC13Ppczji5ubmtelpYEPhEqBFkYOZ7fkTFJ9GUshT6MKRlL1KaIsSk3fVY9hz10d1xRKFajeT/8TDKN7lJFquzbHCNvblqJKHQZ+Q2gEw/njXDt8MueTT2wrDktOpl7nLUb+izinuZ/yChSGBQOdGfnhSZjQeOPX6m93a6FtO5ENrHAQc0BzBHHwtK14M3FCotATSK+LQYLaWnJeDqWI206ooc0tqJYC++NtWlLCGuxbEDOa2pa8HwgO97teDWnsiUbFPDyyWtgs0wbK/qj2W6pvHQMwnetSWp5dSvDqRqETG4VKKNBzEnlKjKjZxTg3LNzlGYzEywsm/mU+h5s6WTzBcjNmmat,iv:g3QRUTw0gf31GMwEUEWFuYrMMAtUejdIFFdPJNwQwCY=,tag:qwSMtTkfTLiZfrE2jmNKvg==,type:str]
    identity.pub: ENC[AES256_GCM,data:HP3Uf5FnHskX+K4GN5YUcqfxeVqWmpnOhNKW26eyI8XEds38wm7Ms1FoRIn+UYe8f8+JKNPBUbYZf5cxwCeYmuy7pXhloO5mmyx1w0btjFnrLIXsHdOsvXDiSRkGUmeL95Vj2l7mHGqGTuRBxXxj5Cl3rDk1dll8/UckCIDJ53oLE6sbr8m4ZL7P8S7rlenpRrOmLYg5rVOzbaqQj0hBaq/3ztqQp+i3waF3LK+iSSKRqpwVhHKHWBoz2DepEl+HpznKb8qJw8jJDYnmuA==,iv:e5Oezf1Va05hZZUZ57M1jWoGznNenb/d7aaRuqKqChc=,tag:Hnlqn3CmdS+CrmmfR0etEQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:yvFWMYEnGoLp0si/7YoeH/kWZxrHh1Zb3PE6XjHAOhQkd02bR3JIwUAt2tO3SdoxbVEFFSIMnUXPJXvn6AXX4CJHC6Y3eqfnu6+wVFj4UZHP+z07qcTBF6fJx13bvAuc7zPWyv4Rn1PDicMBBK3ZYPd4fACdgiIbxvtQdnQaxVhYkbW8xEaICTJ/2kV0gJW7Dih8aQ9X4HFFtO3YWWJsPrSWaN6Ex8zCcSSY,iv:AocRsfNWiGpCkd6A9Rpl16f2pIbNYnPSZCabSKZiCiw=,tag:qeA/TV2lul2+ZAKcL47yrQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ajdVeVc4bm5UMk45Z2Jr
            dG0wZVFaenhPMTFCSEp4VzBnK0xCNS9taUF3CjM5MDhPajNGM0N0OWpFckZHanlk
            aDJzOXRsMnhCVjRub1ZndDR0dnhDUlEKLS0tIDBkRlhkaVZaaGY5MXRWWEt0YVUy
            WUkzcGhadUdDbEtzRTFzTFRvU1l3RFkKPj19/Lt6+P9ej5N6GxqpXaTcxC8GTR/V
            ym5yfzggpxwD8f5npJvdp9GgIpZ8obkddjGRKIt1Y0khp/dxhsHk1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T11:56:31Z"
    mac: ENC[AES256_GCM,data:O4AxFrddQt2FfEszvSGQ/TTczTKuQPsibGduI0yKdgdvzVKtAsjcMrV+bc15pwD83EJLdN5UMUuHjIYHu6t0NWbMOh3zpmbwELy7F6vVMox6zyQzgijQ4dmJf2Lm1vO9mRtY6XRcGi5IWbxpvpGVA380/kB//LtJF1JunldeM84=,iv:XxHhqOVsJklNpor/1IQbHtU5ZIUl6IvCsHyFItNd9AI=,tag:98wB9DGJI22vHvXy6+xoiA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
