apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5HlUAG76sHtqKIXUkmtzCntoqaq0j0n6MXiDGZ25CDx1kb+S63jCK31h7CMDxR50Tv4CcVgxd5cAXtofXhKxdcoesQ+7vb3FkoWgJv/LYE6F8vRDhCRj1LrEqlM9i0gDbxgEwIvyD+w6xlvicWo87Oq/SSc/VZGKMBx8JNwyejchKWN0I/q/JHQrrugExvlpe2mrA1xR6R8gd9GUzmoueoEO8WB9iJQS1ypqv+Xn64WpIcYvdHp+7rbOcD1h/kY9ZQ7prWSipbzV8hQk4BvXHVlAcCn+9/tKSIT+bvjslxtRPhRyJKX6lEaMO+CgZnGfUStKqNKaJ37k9K0hJALRWtwG+5YOVWIILyQAORcSad5S+0Y2CMc60sFZ89Z6n8Sx,iv:QpsP0ElwJsmNxxo7bQ4RD5H+RnD1LSseJB/r5WYHcvw=,tag:fgy2EjBAo6j6Whk8JjWsCw==,type:str]
    identity.pub: ENC[AES256_GCM,data:YBIN77p+H2i42cPcQ1YtTS6ggXJO/jmOOust+indfccEq/XjnN+YNJPwGoT9AAb6uSepq6uiJlAD2bnWp+Vi7w4l0XT1NtNwPUasazV/i1vbo2ySh2/pHK5338J1MjKR6G0V7HkvqQi9gUdTC+/uPwHMNM17qlLjZUkL7MhRGY0W2H0DBKzkF8wvP+ZFlvICpggimnEaLQSUGpr2tSqyWi85c3bUv3pDHKBkHJUcXFToIXfqeVYjMS5Obu2rK2y73ndCH9TadD4NAUMQww==,iv:NXPdo78wGbW0+l/CXcV2tQX2Iq1/ZOhHMdPwdG4Bvi4=,tag:Vua7RoV/43/cITr5DyBrHg==,type:str]
    known_hosts: ENC[AES256_GCM,data:bmdDLCgZX1F2rLncO2P1B9s/qutYp1PZNRcccXXUn0xFPB9P5lBeHOovTtTlaz6PLJidCxAZHdPNbNsb9T5+Y9UTqWffytdid5uChFF8BrhjwhNYHiFrdQ9vkst2KfzbnxiqyxXTMKtgH5Ej3ZgjmsFTE6bjfBlQUfa00b6camCfNGLN9pSHQHRrnOudKlBNQXkujpCraYRwSMOkMHepYsNkRCO+eQrCRp5i,iv:anVBZmDBks7eImqMTaUWc+4KPt+1toxEqYu20dJyXHQ=,tag:njmh9fyABjhM4q6/Fjl+TA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SDA4a3QvbEwwL2hGT0dz
            SVFKekVsMW42c3FxVjhtdEUydm1HVWZQOWdJCnNWVzczOHBPSzhpcEF2VWZMYm1t
            VGdkc1lZTHc2TWR6MHJndVdpeGxSQjQKLS0tIGxSdmhqdjFlUWVFdlhRdkRYVW1x
            ZnI5aFAxbld3Unkxb1Y4dU9vbEdTOGMKHHKHkJhDGRbI/kEb0L1zLhmJOR6IK3Ga
            6fvPPwQOaKPblRfuNKFaCLt5KKfaMnxEAMKhsP6ZZ1SM+fbNWuMfEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T08:06:42Z"
    mac: ENC[AES256_GCM,data:TpSyd+VNxkvk0RSNHO1Op1MmxK/oTW4zdl4Uh4kAqMqcHi/q0/EaHsn9QwlXmhEXPR+47QKejcK/148gskHXAPEDiWhx3Qp5mut9Gfb6nXt9heiqTH5WX04cKj1vcBmXIKZZpskPIztiHoIPZ96ssl8WZ5WWx8SYNNkFwqQOoGw=,iv:QSNCTu3b+9ZVRnqIZRaJyk20VQovA7q7wwQaXKKD+1Q=,tag:GPB4euCypRR9dT6aXQM54g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
