apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vM/OxwrQHBlxZHgJ75AimCl4N2t+LhjRT0ZLcOzIbAbgpG/U3ywL7g2rDpS2MecKaiVIQ/WBOKG8Brhh4MkuC3zQXyXQdAt6yDdKGoi3qkmRqpQcBQw0ciLw79f2FlXBzHWpzxjlQqj3AlvSw2CXrIpKeO1d/86lhvNk67+NbWFxAAN4eFfEpVjrBkrzLUX9xg3M88HdTQxKipblZywvXfzmx34uweKo+Qcw6U7/aKUqvnDzh0tDr9ytWQMPYRox++Z/YI7/ibqgPbg7aWrsrD25g9cmoaUWF7bnNqZOwftIFYeyq7J1Aj1DqFw1yWjH1yzDDFPzpWa2vGCdLO3GTY9+RXon4t/Hgi2iYMHnCXOWsBlZmr85n9+2EQpgU4Zz,iv:I/A2ltFZhCfX3vigryzoSZvwfBgWZcHBU0o9PITVzlY=,tag:Vo1yP97ikZgJYIQSvhVuGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:SOlTxsUK5XF1sH7lbUOK5XlvdiDcO9M5sWMcGHRCYRlHfcbhfZoER9fcMW8faH4n/GP4tCvdGXCMW8/djdjLmad4alCWSXX8+Jdhe3VJWWPzDa2kJeb9CfgEHB4ByOhhC029mAV87zuup+GSCNW8rVTWPm3IySZs9BVlnJ4tFKKRG7EN9kQnXIUXubCSkeQx7IILlvazGPD02bSdcJV9WPgP4K0IaqvxT9yJoV1ipW4GKp8VIKQlmVtnTeizr1Zr0S/1fUgBg0+/xyan4A==,iv:FBi+H9gk+9+5lGHlekG0Ad+AEZKDBkm8/2Q2fqVEw4M=,tag:hCM/sovkHwQ2e5Wt9ImhwQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:hzTRoTGgW+IoPO7I09ZPxII5LuaXBT8+VAQDH9DL9JzwRrR/tCQQrcG/hagiPTdVuX4+WFQAQcjP0sd2CgIu+bZr69VuF7sM+6TzjsFzHKaW4TWJVZEmQNQV1lszB6tU1cFWr7Un17p3WiixRmpEg2elXdgK2vXcAAVBRszPr5zxCZ5jMxlLCdwuNU+CvQshOoyHXsIfE16K3iJUYo3b0Rapi/dWBYGNe3g2,iv:n3fGs1Z9oM7wziTRn5jLWEb3s4jYe8+JzeOsTcgtObc=,tag:NZTstIgr3e58ybxIiqSIbA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gsn23uksk8rgr8p9llrwgt4d004thy326meuwpdp8vgnh20qqufsc9qc6l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMLzQ3VUoxTUt0bXRtT2th
            dWVCUjlzdkk0MlFTMUFFWWdpRmFKcnhNZ1I4CmtzcFh6cWVNTUNsZ2JVM2Z5WG1t
            SlFVZWNaRUR2VGZKU25VNVFWYWRqcFUKLS0tIHBQZ2JMay9BUmsxVWpnWXkwdDlY
            RTFaYjRDY0R1Z0thb3puK2wveUdWazQKELG3UkXV7fje+5Owcj3YeNvjzzZRB6b5
            xIi63JVDOgoLr5zvHLZ8tcmZUoY5q3ot+hjkh7a+Llxy7YocaIv+ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-01T08:02:49Z"
    mac: ENC[AES256_GCM,data:s/S7HNrN4ySI8ncJGCAQNmf9c3LSDXC5qbz6fRXCvP8J6228TlB3J3air7u3EGB7nOmDTzATUPskHPnJbON1W5Rq5vdoh3qJs7d8XKx37j/xZ9ZoJ0xHRKenTGEB4p8haUFvBHgx2p3BqqB8D+UaIPc2AIPA5k4bow6uo8uO8Kg=,iv:UUmqA5BjxIct9XY4lNOquZ6kxQDDf4/ENG3oXuUHvvU=,tag:h15R2yKDKUlMpm0iNbt2VA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
