apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:30ICFpbWOgc0G+Q2msED/18O0/VssK4MOGFeqwBATvRvlybq8zhY6lUMT6Wdnggy6R91IaW8aOji1u5sZ6b7X1b62EEWe9AFDasuao7KkuxG81A5q4u6uBk7ZmCaBOr11bmJ0Lxxmx7ZftFEBDqNY1aPvUqOoofPSac1Y4VURACcncXtRYdlEMAFZSQJYiSLe1rv2TZ9c8hBHK8kS5l/4XZHQNOQ+sQTSXpwFEdO3qSERok98s5U0lMcm0hSx/X9J3MCNS4acgblEiVaenokKp1MnzJf+abZvH84eBekrIw1nCOc6NtXanWdkSpWTfUDSSEXzdZw12DOMa9sxDxNLUtwj3avqYYxJsdTj3dBOSRXRXs1LB2Swuxs9yToPE3u,iv:81h/XE395eM6jLHjhd9//34WEf/Wm5uRMTJaS0xOgos=,tag:cUvTFlfnk7aRZfWSLRGT4w==,type:str]
    identity.pub: ENC[AES256_GCM,data:sSJcxpgTJRxNehtehyGckyvKA2Bd8tYz6rZmuKAMUd/jz1rRwTFJDAKhQIdo8Sp1NyxhPAPtCayw/CIjd87V/RQhtHbaPY8Lwa5AzBLLYutDeG0uNyvl26kpK4RmVTgjWemne51L4fRrQ6GyXkJGaQ1lbeSumHCYWB0/mWryiyQCsDPzEkgshwTtljmUoHlImMuGmxActZYQFNxEdEabO6RFIsYf1YJdldUeuiH/VN3QZr+1iesietbvxfyuamh4nRgjkFuFNh1q6gmFDw==,iv:Ol6a6J88jPyT0mPuzFiWT66iARM8COokkYDsffmFGQM=,tag:yEcUQj8Kleor8+SDPkQylw==,type:str]
    known_hosts: ENC[AES256_GCM,data:l92ZhVoLJB+B+BdDY2GTemvJPr3Z8yJEx1n4pnyAhmcdp71138MCFl5bw6+LPXgn27JJDwswBioBb38EsCGz5JnamElAvY68bJD9CQC5HlX6p7MW+E5kYqq2bbg4WoQBGiDfxo6AvhtjwySLQK8QpHI4Y4g4oaReDn6dX13scC13ykBZ+nFd2IU7TIf0UKEwxXRWkrqqJYRzywfndATMbu4xB9vF1AWuu9Nv,iv:ZDZL6WRLxcXoOVmHDKdNbzFuWxGarfFPtWbLNQ6vDaI=,tag:AjysU72NLSph8HTExn04zQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kmynsjg5gpaajldz6luj3hvdqma3dg6pylrg7f39qed9j7vcpxsvt0d9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Q1QxZXdQR0JVTThNNENq
            ekIzUXRvOGdZNlZuYzZpay9BSFJHN0tjV3k4CnVBNHZ1dW9RWW9CUHYxekdlSnll
            YWJOejZrRUVRUFo2Q3lnMDM1MWYwdFEKLS0tIDRCSDJmZC9SdXQ2dnZ3RmpiQmVL
            ZDVtMGZsQTZhYmF3VmRDbzJLbEF0M1EKBb8jSkO8SrMYZ1wXe1oRdlWuMioqurNX
            VU51C6rslCJM4PZ6Crfj1JMTNW1ghhtLMobH5kVv4XmiIGR8ACZ04Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-31T08:15:59Z"
    mac: ENC[AES256_GCM,data:6yfLpurudjJjZ5BanPF8QDVLjhKBWw5Nir0JaA4pVLI4sJMXB2oVyNHt4XZyRSqFM5CQL80glrCS3ivCyMp06feaiJ8kN2v9y6fZ+kChW6lsVZgepFax90Ymh+b29Hpy1z5cKy8372KV/uZDwMMx2r3ZmK5X5iuyLdhYQW+sipo=,iv:d+ryU0M7a9aD5aV7gBMbWfHTOmUUDiwz7BnnBoJs+as=,tag:zNnCuwupWMIV40qoZVk3/w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
