apiVersion: v1
kind: Namespace
metadata:
    name: system
    annotations:
        volsync.backube/privileged-movers: "true"
    labels:
        kustomize.toolkit.fluxcd.io/prune: disabled
        pod-security.kubernetes.io/enforce: privileged
