---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media-qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      s3:
        type: s3
        url: "http://${S3URL}"
        bucket: "${S3PREFIX}-qbittorrent"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"

    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 6Gi
        cpu: 4000m

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        tls:
          - clusterCertificate: domain-0-wildcard
            hosts:
              - torrent.${DOMAIN_0}
        hosts:
          - host: torrent.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: false
          homepage:
            enabled: true
            group: Infra

    persistence:
      webui:
        enabled: true
        mountPath: /mnt
        type: nfs
        path: ${NFS_PATH_K8S}
        server: ${NFS_SERVER_IP}
      downloads:
        enabled: true
        mountPath: /downloads
        type: nfs
        path: ${NFS_PATH_DOWNLOADS}
        server: ${NFS_SERVER_IP}
