---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: readarr
      version: 23.1.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      exportarr:
        enabled: false

    metrics:
      main:
        enabled: false

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: selfsigned
        hosts:
          - host: readarr.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        type: emptyDir
      books:
        enabled: true
        existingClaim: media-books-nfs-pvc
        mountPath: "/media/books"
      downloads:
        enabled: true
        existingClaim: downloads-nfs-pvc
        mountPath: "/downloads"
      # backup:
      #   enabled: true
      #   existingClaim: media-backups-pvc
      #   mountPath: /config/backups
      #   readOnly: false
