---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.1.7
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      privileged: true
      readOnlyRootFilesystem: false

    plex:
      # User Defined
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: ${PLEX_ADVERTISE_URL}
      disableGDM: true
      requireHTTPS: false

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}

    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
            middlewares:
              - name: local
                namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: selfsigned
        hosts:
          - host: plex.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        type: emptyDir
      media:
        enabled: false
        existingClaim: media-nfs-pvc
        mountPath: "/media"
      series:
        enabled: false
        existingClaim: media-series-nfs-pvc
        mountPath: "/media/series"
      movies:
        enabled: false
        existingClaim: media-movies-nfs-pvc
        mountPath: "/media/movies"
      anime:
        enabled: false
        existingClaim: media-anime-nfs-pvc
        mountPath: "/media/anime"
