---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omegabrr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 14.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/autobrr/omegabrr
      tag: v1.14.0
      pullPolicy: IfNotPresent
    
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-omegabrr"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    
    workload:
      main:
        podSpec:
          containers:
            main:
              probes:
                readiness:
                  enabled: false
                liveness:
                  enabled: false
                startup:
                  enabled: false


    service:
      main:
        type: ClusterIP
        ports:
          main:
            protocol: http
            port: 7441
    persistence:
      config:
        storageClass: topolvm-provisioner
        enabled: true
        mountPath: /config
        volsync:
          - name: backup
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true

    # persistence:
    #   config:
    #     mountPath: /config
