---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: omegabrr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: custom-app
      version: 14.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/autobrr/omegabrr
      tag: v1.12.1
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          - port: 8080
            targetPort: 8080
            protocol: TCP
    ingress:
      main:
        enabled: false
    # persistence:
    #   config:
    #     type: emptyDir
