apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
  - volumeSnapshotClass.yaml
  - node.yaml
  - standard-storageclass.yaml
  - premium-storageclass.yaml
