apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-control-1
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    premium-tier:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/premium
      storageReserved: 82044861235
      tags:
        - nvme

    standard-tier:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/standard
      tags:
        - ssd

  evictionRequested: false
  instanceManagerCPURequest: 0
  name: k8s-control-1
  tags: []
