apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-control-1
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    default-disk-fd0600000000:
      allowScheduling: true
      diskDriver: ""
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 82044861235
      tags:
        - nvme

    ssd-disk-longhorn:
      allowScheduling: true
      diskDriver: ""
      diskType: block
      evictionRequested: false
      path: /dev/sdb
      tags:
        - ssd

  evictionRequested: false
  instanceManagerCPURequest: 0
  name: k8s-control-1
  tags: []
