---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests

on:
  pull_request:
    branches: [main]
    paths: [clusters/**, .github/workflows/tests.yaml]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  KUBERNETES_DIR: ./clusters/main/kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux kubeconform kustomize

      - name: Run kubeconform
        shell: bash
        run: bash ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}

  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        cluster_path:
          - clusters/main/kubernetes
        resource:
          - kustomization
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@v2.6.2

      - name: Setup Kustomize
        uses: syntaqx/setup-kustomize@4331ea02eec887906c9adbf7f431ca3db09908fd # v1

      - run: kustomize version

      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@8c41682a7ef704f883d800a8676a68f1da038689 # 6.1.1
        id: diff
        with:
          path: ${{ matrix.cluster_path }}
          resource: ${{ matrix.resource }}
          sources: cluster=${{matrix.cluster_path}},flux-system

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2
        with:
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            `````diff
            ${{ steps.diff.outputs.diff }}
            `
