apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  interval: 5m
  releaseName: topolvm
  chart:
    spec:
      chart: topolvm
      version: 15.3.0
      sourceRef:
        kind: HelmRepository
        name: topolvm
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    # lvmd service
    lvmd:
      managed: false
      env:
        - name: LVM_SYSTEM_DIR
          value: /tmp
      # lvmd.deviceClasses -- Specify the device-class settings.
      deviceClasses:
        - name: thin
          volume-group: topolvm_all
          type: thin
          default: true
          # thin-pool:
          #   name: "pool0"
          #   overprovision-ratio: 5.0
    node:
      lvmdEmbedded: true

    storageClasses:
      - name: topolvm-provisioner-thin
        storageClass:
          fsType: xfs
          isDefaultClass: true
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          additionalParameters:
            "topolvm.io/device-class": "thin"
