apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - downloads-nfs-pvc.yaml
  - media-nfs-pvc.yaml
  - autobrr/ks.yaml
  - plex/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
